Clean up obsolete documentation
zonemaster/zonemaster-engine pull request #1018
Opened 2021-11-30 15:16 UTC by mattias-p

## Purpose

This removes a piece of obsolete documentation.

## Context

The separated config and policy system was replaced with the combined profile system in #446.

While it's late in the release cycle I believe it could be included in the release without problems. On the other hand it isn't urgent either, so it could also be postponed to the next release without problems.

## Changes

This PR touches documentation only. It doesn't add anything new but it removes a source of confusion. I had a look and I couldn't find anything in the removed file that isn't already documented elsewhere.

## How to test this PR

N/A

2021-11-30 16:09 UTC, matsduf approved these changes

2021-11-30 16:11 UTC, matsduf requested changes
You have to update MANIFEST too.

2021-11-30 16:13 UTC, mattias-p commented
> You have to update MANIFEST too.

Yeah, the CI tests noticed that too. I made an update.

2021-11-30 16:24 UTC, matsduf approved these changes

2021-12-01 09:37 UTC, pnax approved these changes

2021-12-01 10:20 UTC, merged