Config SOA values
zonemaster/zonemaster-engine pull request #1032
Opened 2021-12-23 18:38 UTC by pnax

## Purpose

This PR...

## Context

Addresses #945

## Changes

...

## How to test this PR

...

## TODO

- [ ] documentation
- [ ] test cases?

2021-12-24 12:51 UTC, matsduf commented
I think this looks good.

2022-01-04 15:43 UTC, matsduf commented on lib/Zonemaster/Engine/Profile.pm
> +Default C<86400> (1 day in seconds).
I think these could be shorter by only having
```
=head2 test_cases_vars.zone.SOA_DEFAULT_TTL_MAXIMUM_VALUE

A positive integer value.
Default C<86400> (1 day in seconds).
```

I think it would easier to read. The remaining information belongs to the test case method.

2022-01-04 16:20 UTC, pnax commented on lib/Zonemaster/Engine/Profile.pm
> +Default C<86400> (1 day in seconds).
To be honest I followed how it was done for `test_cases_vars.dnssec04` items.
Do you suggest to shorten the documentation for these items too?

2022-01-04 16:28 UTC, pnax commented on lib/Zonemaster/Engine/Profile.pm
> +Default C<86400> (1 day in seconds).
see https://metacpan.org/pod/Zonemaster::Engine::Profile#test_cases_vars.dnssec04.REMAINING_SHORT

2022-01-04 16:28 UTC, matsduf commented on lib/Zonemaster/Engine/Profile.pm
> +Default C<86400> (1 day in seconds).
I understand that, and when there were just a few it works, but with many I feel that it should be shorter, and I feel that the extra information does not really belong here. What do you think?

I you agree with me, please shorten all to make it more readable, maybe even on one line.

2022-01-04 16:31 UTC, matsduf commented on lib/Zonemaster/Engine/Profile.pm
> +Default C<86400> (1 day in seconds).
I guess one should use `perldoc` to inspect the POD before merging.

2022-01-04 16:33 UTC, pnax commented on lib/Zonemaster/Engine/Profile.pm
> +Default C<86400> (1 day in seconds).
Thinking about it, I'm realizing that if we remove these sentences, we might be losing some information on how these parameters interact with the tests. Since I can't see anywhere else where we have specified this interaction, I think it might be good to keep it here.

2022-01-04 16:39 UTC, matsduf commented on lib/Zonemaster/Engine/Profile.pm
> +Default C<86400> (1 day in seconds).
Could a short section with the headling "test_cases_vars" be put before the list of "vars" that shortly describes that these are related to messages with the same name as after the dot?

2022-01-10 17:45 UTC, mattias-p approved these changes
LGTM. I have a small suggestion.

2022-01-10 17:45 UTC, mattias-p commented on t/Test-zone.t
> +    Zonemaster::Engine::Profile->effective->set( q{test_cases_vars.zone.SOA_DEFAULT_TTL_MAXIMUM_VALUE}, $old_ttl_max );
Maybe use `Zonemaster::Engine::Profile->effective->merge( Zonemaster::Engine::Profile->default )` instead of restoring individual properties?

2022-01-10 22:18 UTC, matsduf requested changes

2022-01-10 22:18 UTC, matsduf commented on lib/Zonemaster/Engine/Profile.pm
> +    q{test_cases_vars.zone.SOA_DEFAULT_TTL_MAXIMUM_VALUE} => {
The already existing variable have variable names with the test case identifier where it is used. I think the is a good principle, i.e. for this variable:

test_cases_vars.zone.SOA_DEFAULT_TTL_MAXIMUM_VALUE => test_cases_vars.zone06.SOA_DEFAULT_TTL_MAXIMUM_VALUE

2022-01-10 22:18 UTC, matsduf commented on lib/Zonemaster/Engine/Profile.pm
> +Default C<86400> (1 day in seconds).
My error. They are values used in specific test case, but they are not directly settings of messages.

The structure of the name, so far, is "test_cases_vars." + %Test-Case-ID% + "." + %VAR-NAME%

2022-01-13 14:17 UTC, pnax commented on t/Test-zone.t
> +    Zonemaster::Engine::Profile->effective->set( q{test_cases_vars.zone.SOA_DEFAULT_TTL_MAXIMUM_VALUE}, $old_ttl_max );
Thanks for the tip. I made the change.

2022-01-13 14:17 UTC, pnax commented on lib/Zonemaster/Engine/Profile.pm
> +    q{test_cases_vars.zone.SOA_DEFAULT_TTL_MAXIMUM_VALUE} => {
Updated to follow the suggested format.

2022-02-16 12:07 UTC, pnax commented
@matsduf can you re-review?

2022-04-04 09:32 UTC, matsduf approved these changes
This looks good, but I have two comments that are not crucial. I approve.

2022-04-04 09:32 UTC, matsduf commented on lib/Zonemaster/Engine/Constants.pm
> +Readonly our $DURATION_180_DAYS_IN_SECONDS   => 180 * 24 * 60 * 60;
Why not provide them as 300, 3600 etc?

2022-04-04 09:32 UTC, matsduf commented on lib/Zonemaster/Engine/Profile.pm
> +Default C<14400> (4 hours in seconds).
I do not think the exact message tag should or need to be documented here. When the tag is updated (the current tag does not match the current template) then it has to be updated here too. I think it should be enough to refer to the test case specification and test case implementation. E.g.:

```
A positive integer value.
For its use, see the implementation in Zone.pm (in this repository) and zone02.md
(in the zonemaster/zonemaster repository).
Default C<14400> (4 hours in seconds).
```

This comment also applies to the definitions below.

2022-04-04 12:37 UTC, mattias-p commented on lib/Zonemaster/Engine/Profile.pm
> +Default C<14400> (4 hours in seconds).
Since this is a configuration parameter rather than a method, I don't think it's appropriate to say that it "returns" something. I suggest simply stating what it represents.

```
A positive integer value.
The lower bound recommended for SOA refresh values.
Default C<14400> (4 hours in seconds).
```

2022-04-07 08:59 UTC, pnax commented on lib/Zonemaster/Engine/Constants.pm
> +Readonly our $DURATION_180_DAYS_IN_SECONDS   => 180 * 24 * 60 * 60;
I kept to way it was done before. While implementing it I also felt it would make it easier to review the values.

2022-04-07 09:55 UTC, pnax commented on lib/Zonemaster/Engine/Profile.pm
> +Default C<14400> (4 hours in seconds).
I updated the documentation, trying to take from both suggestions.

2022-04-07 11:21 UTC, matsduf commented on lib/Zonemaster/Engine/Profile.pm
> +Default C<14400> (4 hours in seconds).
You still refer to the exact message tag, which I find unnecessary and will increase the risk that it is not updated when the tag is replaced. It will not break anything, but the more configuration items there are the more important it is to keep them short.

2022-04-07 11:25 UTC, matsduf approved these changes
I have left a comment, but I approve anyway.

2022-04-11 09:25 UTC, pnax commented on lib/Zonemaster/Engine/Profile.pm
> +Default C<14400> (4 hours in seconds).
There is a tight coupling between the tag and the configuration item. I think it helps to have the documentation highlights this coupling.

2022-04-11 09:26 UTC, merged