New implementation of Nameserver11 - #993
zonemaster/zonemaster-engine pull request #1034
Opened 2022-01-03 17:31 UTC by tgreenx

## Purpose

This PR proposes a new implementation for Nameserver11 as mentioned in #993 . The corresponding document specification is provided in another PR.

## Context

Addresses #993 .

## Testing

zonemaster-cli --test=nameserver/nameserver11 nkb.ch --no-ipv6 --level=DEBUG
...
1.07 DEBUG     Nameserver ns3.securedns.ch/77.109.136.195 responds with an unknown EDNS OPTION-CODE.
...

2022-01-04 15:12 UTC, matsduf commented
The process we have followed so far is to have the specification completed before implementation starts. In that we lower that risk of have work to be redone.

2022-01-04 16:49 UTC, vlevigneron commented
I agree with @matsduf. We should follow the same process we had before. Specifications first, then implementation.
BTW @tgreenx, some links in your PR are wrong, for instance you refer to zonemaster/zonemaster-engine#993 instead of zonemaster/zonemaster#993 in many places

2022-08-31 19:57 UTC, matsduf requested changes

2022-08-31 19:57 UTC, matsduf commented on lib/Zonemaster/Engine/Test/Nameserver.pm
> +        push @results, info( NS11_UNKNOWN_OPTION_CODE => { ns => join( q{;}, uniq sort @unknown_opt_code ) } );
The specification and the message defined on lines 363-365 says "ns_ip_list", here it is "ns".

The example in the PR description indicates that it is outputted as `ns_list` rather than `ns_ip_list`.
```
1.07 DEBUG Nameserver ns3.securedns.ch/77.109.136.195 responds with an unknown EDNS OPTION-CODE.
```

It is not wrong to have `ns_list` but then the specification must be adjusted first.

2022-09-01 08:09 UTC, tgreenx commented on lib/Zonemaster/Engine/Test/Nameserver.pm
> +        push @results, info( NS11_UNKNOWN_OPTION_CODE => { ns => join( q{;}, uniq sort @unknown_opt_code ) } );
Indeed, I missed that, it is fixed now. The example in the description is also outdated (it will not output the same thing anymore), I will remove it.

Note that we also have no unit test for this test case, could you maybe create test zones for it? And I'll then make the unit tests.

2022-09-01 08:26 UTC, tgreenx commented
Commit 39bb1c7 addresses PR [zonemaster#1093](https://github.com/zonemaster/zonemaster/pull/1093).

2022-09-02 19:56 UTC, matsduf commented on lib/Zonemaster/Engine/Test/Nameserver.pm
> +        push @results, info( NS11_UNKNOWN_OPTION_CODE => { ns => join( q{;}, uniq sort @unknown_opt_code ) } );
> Note that we also have no unit test for this test case, could you maybe create test zones for it? And I'll then make the unit tests.

I will do that, but it might take a while since it cannot be done by a normal name server like Bind.

2022-09-19 15:39 UTC, matsduf commented on lib/Zonemaster/Engine/Test/Nameserver.pm
> +        push @results, info( NS11_UNKNOWN_OPTION_CODE => { ns => join( q{;}, uniq sort @unknown_opt_code ) } );
We may have found a tool that permits the creation of response that we need for the unit test.

2022-11-10 11:27 UTC, matsduf commented
@tgreenx, can https://github.com/zonemaster/zonemaster/pull/1111 be merged and incorporated in this update?

2022-11-10 13:21 UTC, tgreenx commented
> @tgreenx, can [zonemaster/zonemaster#1111](https://github.com/zonemaster/zonemaster/pull/1111) be merged and incorporated in this update?

Yes

2022-11-22 19:22 UTC, matsduf approved these changes
This looks fine, and I see no obvious error. There are, however, not enough unit tests or test zones to verify this implementation. I think we can merge, and then let the upcoming tests zones that are defined in https://github.com/zonemaster/zonemaster/pull/1113 verify it. In that PR there is a test-data specification for the test case.

2022-11-23 21:43 UTC, mattias-p approved these changes
LGTM. I found one small thing that could be improved but from my understanding it's not big enough to block merging.

2022-11-23 21:43 UTC, mattias-p commented on lib/Zonemaster/Engine/Test/Nameserver.pm
> +            elsif ( defined $p->edns_data ) {
This check is more general than what is prescribed in the specification. It doesn't seem like a huge deal, but I wanted to point it out.

2022-11-23 22:57 UTC, matsduf commented on lib/Zonemaster/Engine/Test/Nameserver.pm
> +            elsif ( defined $p->edns_data ) {
I looked at that, and since the query has no flags and no other options in EDNS, besides the undefined option, which the server is expected to ignore and not include in the response, I think this should work.

2022-12-01 13:56 UTC, merged