Implementation of Zone11 - #1028
zonemaster/zonemaster-engine pull request #1035
Opened 2022-01-04 12:53 UTC by tgreenx

## Purpose

This PR proposes an implementation for the new Zone11 test as described in #1028. The corresponding specification is provided in another PR ([here](https://github.com/zonemaster/zonemaster/pull/1032)).

## Context

Addresses #1028.

2022-01-04 15:28 UTC, matsduf commented
The process we have followed so far is to have the specification completed before implementation starts. In that we lower that risk of have work to be redone. I suggest that the implementation is paused until the specification is done.

2022-01-04 16:47 UTC, vlevigneron commented
I agree with @matsduf. We should follow the same process we had before. Specifications first, then implementation.
BTW @tgreenx, some links in your PR are wrong, for instance you refer to zonemaster/zonemaster-engine#1028 instead of zonemaster/zonemaster#1028 in many places

2022-11-15 17:31 UTC, tgreenx commented
Unit tests are not updated yet and thus will fail. More soon.

2022-11-16 10:16 UTC, tgreenx commented
Ready for review

2022-11-25 17:37 UTC, matsduf requested changes

2022-11-25 17:37 UTC, matsduf commented on lib/Zonemaster/Engine/Test/Zone.pm
>                      }
0 is a legal value of SOA serial. I think `if ( not $serial ){` can be problematic. On the other hand, `@serial_ns` can only hold SOA serial values as far as I understand. If it is empty, the code will not enter the loop. What case does the test want to catch?

2022-11-25 17:37 UTC, matsduf commented on lib/Zonemaster/Engine/Test/Zone.pm
>                  }
0 is a legal value of SOA serial. I think `if ( not $mname_serial ){` can be problematic. Could `if ( defined $mname_serial ){` work?

2022-11-28 14:26 UTC, tgreenx commented on lib/Zonemaster/Engine/Test/Zone.pm
>                  }
Good point. Updated.

2022-11-28 14:26 UTC, tgreenx commented on lib/Zonemaster/Engine/Test/Zone.pm
>                      }
Good point again, it is not supposed to be here. Updated.

2022-11-28 14:26 UTC, tgreenx commented on lib/Zonemaster/Engine/Test/Zone.pm
> +                                }
Updated

2022-11-28 16:09 UTC, tgreenx commented
@matsduf please re-review

2022-11-28 21:49 UTC, matsduf commented on lib/Zonemaster/Engine/Test/Zone.pm
> +            push @serial_ns, $soa_rr->serial;
If several name servers report the same serial it will be stored several times. That is why I suggested a hash.

2022-11-28 21:55 UTC, matsduf approved these changes

2022-11-29 08:45 UTC, tgreenx commented
@matsduf please re-approve. I just added a reminder for untested message tags in unitary tests.

2022-12-05 10:34 UTC, matsduf commented on lib/Zonemaster/Engine/Test/Zone.pm
> +                        soaserial_list => join( q{;}, @serial_ns )
I agree. Either that or turn "serial_ns" into a hash as I suggested above. Compare with %mname_ns.

2022-12-05 10:43 UTC, matsduf commented on lib/Zonemaster/Engine/Test/Zone.pm
> +                        last;
I agree. There are three foreach-loops and it would maybe be easier of the enclosed ones are labeled.

2022-12-05 11:12 UTC, matsduf reviewed
Besides one minor comment and the two comments by @marc-vanderwal it looks fine.

2022-12-05 13:44 UTC, tgreenx commented on lib/Zonemaster/Engine/Test/Zone.pm
> +    }
True, updated.

2022-12-05 13:44 UTC, tgreenx commented on lib/Zonemaster/Engine/Test/Zone.pm
> +                        last;
Updated

2022-12-05 13:44 UTC, tgreenx commented on lib/Zonemaster/Engine/Test/Zone.pm
> +                        soaserial_list => join( q{;}, @serial_ns )
Updated

2022-12-05 13:46 UTC, matsduf approved these changes

2022-12-05 13:48 UTC, marc-vanderwal approved these changes

2022-12-05 13:50 UTC, merged

2022-12-08 10:56 UTC, marc-vanderwal commented
Unit tests pass. Also, I was able to elicit the following messages which are not covered yet by unit tests:
- Z01_MNAME_HAS_LOCALHOST_ADDR
- Z01_MNAME_IS_LOCALHOST

However a more complex setup, which I do not yet have at my disposal, would be needed to check the following messages:
- Z01_MNAME_NOT_AUTHORITATIVE
- Z01_MNAME_NOT_MASTER
- Z01_MNAME_UNEXPECTED_RCODE.