add new basic00 implementation
zonemaster/zonemaster-engine pull request #1040
Opened 2022-02-21 15:42 UTC by blacksponge

## Purpose

Implement new Basic00. I implemented the updated "test case" as sanitization methods, it is not used anywhere yet, I am waiting for design validation before using it.

## Context

https://github.com/zonemaster/zonemaster/pull/942

## Changes

* Add `Zonemaster::Engine::Sanitization::sanitize_name` that follow the procedure described at https://github.com/zonemaster/zonemaster/blob/3fb8ee822592034650f4309c7529d6178b603c69/docs/specifications/tests/Basic-TP/basic00.md
  * The method return the normalized domain name if it is valid.
  * Throw an error of kind `Zonemaster::Engine::Exception::DomainSanitizationError` if it is invalid.

TODO:
* Documentation (waiting for design validation)

## How to test this PR

* A new test file "t/sanitization.t" is testing the method.

2022-02-23 16:38 UTC, mattias-p reviewed
In general this looks good to me but I have a bunch of comments.

2022-02-23 16:38 UTC, mattias-p commented on lib/Zonemaster/Engine/Sanitization.pm
> +    };
I'm thinking this procedure should take decoded strings. After all it is a library function. Decoding from octet strings to native Perl encoding ought to be handled close to where the octet strings enter into the process. That way it's much easier to know what variables hold octet strings and which ones hold strings with Perl's native encoding. What do you think?

2022-02-23 16:38 UTC, mattias-p commented on t/sanitization.t
> +use Test::More;
We should `use utf8;` in all files to make sure Perl considers the source files to be UTF-8 encoded.

By the way I recommend using `perlcritic`. It'll probably tell you the same thing.

2022-02-23 16:38 UTC, mattias-p commented on t/sanitization.t
> +            print Dumper "$@", $@->{dlabel};
Have you considered using `diag` or `note` here instead of `print`?

2022-02-23 16:38 UTC, mattias-p commented on lib/Zonemaster/Engine/Sanitization/Errors.pm
> +use Zonemaster::Engine::Exception;
Is it intentional to have `extends` first and `use` after? (Maybe that's how it's supposed to be, but it does look funny to me.)

2022-02-23 16:38 UTC, mattias-p commented on lib/Zonemaster/Engine/Sanitization/Errors.pm
> +    $params->{message} = 'Domain name has characters that can not be decoded';
`can not` -> `could not`?

Also, all the other messages end with a dot, but not this one.

2022-02-23 16:38 UTC, mattias-p commented on lib/Zonemaster/Engine/Sanitization/Errors.pm
> +use Class::Accessor "antlers";
Have you considered not using the antlers interface? I'm not sure what that would be like because I've never tried it but since this is new code I think it's appropriate to at least consider it.

2022-03-01 16:09 UTC, blacksponge commented on lib/Zonemaster/Engine/Sanitization.pm
> +use Data::Dumper;
Fixed.

2022-03-01 16:09 UTC, blacksponge commented on lib/Zonemaster/Engine/Sanitization.pm
> +my $FULL_STOP = q/\x{002E}/;
I did not, now it is used.

2022-03-01 16:09 UTC, blacksponge commented on lib/Zonemaster/Engine/Sanitization.pm
> +    my ($label) = shift @_;
Fixed.

2022-03-01 16:09 UTC, blacksponge commented on lib/Zonemaster/Engine/Sanitization.pm
> +        # TODO: handle when libidn not installed?
Yes I thought about that, I am not sure what would be the correct behaviour here.

2022-03-01 16:09 UTC, blacksponge commented on lib/Zonemaster/Engine/Sanitization.pm
> +    my $alabel = eval {
No I did not, after looking into it I might keep it the way it is. What I would have needed is a `try / catch / else` statement but Try::Tiny does not seems to offer that.

2022-03-01 16:09 UTC, blacksponge commented on lib/Zonemaster/Engine/Sanitization.pm
> +    $uname =~ s/[\x{FF0E}\x{3002}\x{FF61}]/\x{002E}/g;
I actually did, but when I do, it replaces with the literal value `\x{002E}` and not the unicode character u+002e.

2022-03-01 16:10 UTC, blacksponge commented on lib/Zonemaster/Engine/Sanitization.pm
> +    };
Yes I think that in most cases the string passed to this function will be decoded. I originally this that because the spec states that `If the input *Domain Name* is not a non-empty string of [Unicode] characters this test case cannot be run.` so I wanted to make sure that it could be correctly decoded to a unicode string but this job can be delegated to the caller.

2022-03-01 16:10 UTC, blacksponge commented on t/sanitization.t
> +use Test::More;
> We should `use utf8;` in all files to make sure Perl considers the source files to be UTF-8 encoded.

Okay, I'll do that.

2022-03-01 16:10 UTC, blacksponge commented on lib/Zonemaster/Engine/Sanitization/Errors.pm
> +use Zonemaster::Engine::Exception;
It is not, fixed.

2022-03-01 16:10 UTC, blacksponge commented on lib/Zonemaster/Engine/Sanitization/Errors.pm
> +    $params->{message} = 'Domain name has characters that can not be decoded';
I removed this error type as it is not useful any more if the strings are already decoded

2022-03-01 16:12 UTC, blacksponge commented on t/sanitization.t
> +            print Dumper "$@", $@->{dlabel};
This was some debugging for myself, I removed it.

2022-03-01 16:31 UTC, blacksponge commented on lib/Zonemaster/Engine/Sanitization/Errors.pm
> +use Class::Accessor "antlers";
I updated the module to not use the antlers interface.

2022-03-02 09:07 UTC, mattias-p commented on lib/Zonemaster/Engine/Sanitization.pm
> +    $uname =~ s/[\x{FF0E}\x{3002}\x{FF61}]/\x{002E}/g;
Hmm, interesting.

2022-03-02 10:18 UTC, mattias-p commented on lib/Zonemaster/Engine/Sanitization.pm
> +    my $alabel = eval {
Interesting. I wasn't aware of the `try / catch / else` construct. I see both Python and Ruby support it. But yeah, Try::Tiny only has the traditional `try / catch / finally`.

But in any case, I don't the need for fancy constructs here. To me something like this would be more straight forward. WDYT?

```perl
if ( $label =~ $VALID_ASCII ) {
    $alabel = lc $label;
}
elsif ( $label =~ $ASCII ) {
    die InvalidAscii->new();
}
elsif ( has_idn() ) {
    try {
        $alabel = to_idn( $label );
    }
    catch {
        die InvalidULabel->new();
    };
}
else {
    croak "non-ASCII not supported"
}
```

2022-03-02 10:32 UTC, mattias-p commented on lib/Zonemaster/Engine/Sanitization.pm
> +    };
Yeah, that's a bit weird. The precondition that the domain name is a Unicode string is already stated in the "Inputs" section. I don't see why we need to specify a runtime assertion to make sure the caller isn't breaking this (or any) part of the contract.

2022-03-02 12:32 UTC, blacksponge commented on lib/Zonemaster/Engine/Sanitization.pm
> +    my $alabel = eval {
Indeed this is a simpler way to do it, thanks.

2022-03-02 12:32 UTC, blacksponge commented on lib/Zonemaster/Engine/Sanitization.pm
> +        # TODO: handle when libidn not installed?
Okay, I reused the error message from the backend for consistency

2022-03-28 10:19 UTC, matsduf commented on lib/Zonemaster/Engine/Sanitization.pm
> +            $alabel = Zonemaster::LDNS::to_idn($label);
Before this, I expect to see down casing of all characters that can be down cased.

2022-03-28 10:19 UTC, matsduf commented on t/sanitization.t
> +        # TODO: special I case
The special I case is only special in Turkish or Azerbaijan locale. Here we only do down casing.

Turkish and Azerbaijan locale:

- U+0049 LATIN CAPITAL LETTER I --> U+0131 LATIN SMALL LETTER DOTLESS I
- U+0130 LATIN CAPITAL LETTER I WITH DOT ABOVE --> U+0069 LATIN SMALL LETTER I

Other locale:

- U+0049 LATIN CAPITAL LETTER I --> U+0069 LATIN SMALL LETTER I
- U+0130 LATIN CAPITAL LETTER I WITH DOT ABOVE --> U+0069 LATIN SMALL LETTER I + U+0307 COMBINING DOT ABOVE

I am not sure if the last one (the combination of two code points) is legal in U-label. Maybe it is.

2022-04-07 08:51 UTC, blacksponge commented on lib/Zonemaster/Engine/Sanitization.pm
> +            $alabel = Zonemaster::LDNS::to_idn($label);
It is already done in `to_idn`

2022-04-07 10:17 UTC, blacksponge commented on t/sanitization.t
> +        # TODO: special I case
From what I read in the basic00 document, both u+0049 and u+00130 should be converted to u+0069, but from what I see when testing with libidn or firefox both convert u+0130 to u+0069 + u+0307 resulting in xn--i-9bb.

2022-04-07 10:19 UTC, blacksponge commented on lib/Zonemaster/Engine/Sanitization.pm
> +        croak 'The domain name contains non-ascii characters and IDNA is not installed';
done

2022-04-07 10:19 UTC, blacksponge commented on lib/Zonemaster/Engine/Sanitization/Errors.pm
> +    $params->{message} = 'Domain name has an ASCII label with a character not permitted.';
done

2022-04-07 12:00 UTC, matsduf commented on t/sanitization.t
> +        # TODO: special I case
U+0130 LATIN CAPITAL LETTER I WITH DOT ABOVE are only meaningful in a Turkish or Azerbaijan context (locale) and then it is downcased to U+0069 LATIN SMALL LETTER I (without the DOT-ABOVE). The sequence 0069+0307 is problematic.

2022-04-08 08:45 UTC, matsduf requested changes

2022-04-08 08:45 UTC, matsduf commented on t/sanitization.t
> +        # TODO: special I case
Down-casing LATIN CAPITAL LETTER I WITH DOT ABOVE to the sequence 0069+0307 does not make sense in a domain name context. In a normal text context it is different. The sequence 0069+0307 is a homograph of U+0069, which makes the sequence unsuitable for a domain name.

I see three ways of handling the code point:

1. Down-case to the sequence 0069+0307. That would most definitely create a label that does not match what is registered or used in DNS.
2. Down-case to the sequence U+0069. That will probably match the domain name in DNS, but will apparently mismatch with how how Firefox down-cases the code point.
3. Refuse to handle LATIN CAPITAL LETTER I WITH DOT ABOVE, and instead return an error message saying that there is no unambiguous down-casing of the code point.

Alternative 3 is probably the best way to go to create the least confusion.

The specification should be updated.

2022-04-19 14:39 UTC, blacksponge commented on t/sanitization.t
> +        # TODO: special I case
Will go for option 3 as discussed in meeting

2022-08-19 14:16 UTC, blacksponge commented
I have updated the implementation to match the changes in the specification. There also have been so design changes, mainly a shift from exception to returning errors. This was motivated to better match the spec and allow returning multiple errors (ex. one per invalid label as opposed to only one for the first invalid label).

2022-09-19 08:16 UTC, matsduf requested changes
This looks good. Besides two small code comments, I do not see neither downcasing of non-ASCII nor conversion to NFC in the code. It might be included in `Zonemaster::LDNS::to_idn` since there are test domains with upper case non-ASCII, but then it should documented that that is the case.

In the test labels there is no example of NFC conversion. I could create one if you want.

2022-09-19 08:24 UTC, blacksponge commented
> This looks good. Besides two small code comments, I do not see neither downcasing of non-ASCII nor conversion to NFC in the code. It might be included in Zonemaster::LDNS::to_idn since there are test domains with upper case non-ASCII, but then it should documented that that is the case.

This is indeed done in `to_idn`, I will document it.

2022-09-20 07:51 UTC, blacksponge commented on lib/Zonemaster/Engine/Normalization.pm
> +Readonly my $VALID_ASCII => qr/^[A-Za-z0-9\/\-_]+$/;
done

2022-09-20 07:51 UTC, blacksponge commented on lib/Zonemaster/Engine/Normalization.pm
> +    if ( $uname eq '.' ) {
done

2022-09-20 07:52 UTC, blacksponge commented
> In the test labels there is no example of NFC conversion. I could create one if you want.

That would be great if you can.

2022-09-20 09:13 UTC, matsduf commented
> > In the test labels there is no example of NFC conversion. I could create one if you want.
> 
> That would be great if you can.

Left side is non-NFC, right side is the equivalent NFC.

"d\x{006F}\x{0308}d" => 'död',
"aq\x{0307}\x{0323}a" => "aq\x{0323}\x{0307}a",
"aḋ\x{0323}a" => "aḍ\x{0307}a"

2022-09-20 09:27 UTC, matsduf commented on lib/Zonemaster/Engine/Normalization.pm
> +If the label is ASCII only, it is untouched, else it is converted according to IDNA2008.
It is not untouched, it is down cased.

2022-09-20 09:27 UTC, matsduf commented on lib/Zonemaster/Engine/Normalization.pm
> +The downcasing, unicode normalization and conversion is performed by libidn2 using L<Zonemaster::LDNS/to_idn($name, ...)>.
"Downcasing of upper case non-ASCII characters, normalization to the Unicode NFC format and conversion from U-label to A-label is performed by (...)"

Please no long lines. It makes review in Github harder.

2022-09-20 09:27 UTC, matsduf commented on lib/Zonemaster/Engine/Normalization/Errors.pm
> +Returns the transated error message using the parameters given when creating the object.
"transated" -> "translated"

2022-09-20 09:30 UTC, matsduf commented on lib/Zonemaster/Engine/Normalization.pm
> +Normalize a single label from a DNS name.
I suggest "domain name" instead of "DNS name". It fits our terminology better.

2022-09-20 09:30 UTC, matsduf commented on lib/Zonemaster/Engine/Normalization.pm
> +Normalize a DNS name.
"domain name"?

2022-09-21 16:45 UTC, blacksponge commented on lib/Zonemaster/Engine/Normalization.pm
> +If the label is ASCII only, it is untouched, else it is converted according to IDNA2008.
fixed

2022-09-21 16:45 UTC, blacksponge commented on lib/Zonemaster/Engine/Normalization.pm
> +The downcasing, unicode normalization and conversion is performed by libidn2 using L<Zonemaster::LDNS/to_idn($name, ...)>.
done

2022-09-21 16:45 UTC, blacksponge commented on lib/Zonemaster/Engine/Normalization/Errors.pm
> +Returns the transated error message using the parameters given when creating the object.
fixed

2022-09-21 16:46 UTC, blacksponge commented on lib/Zonemaster/Engine/Normalization.pm
> +Normalize a single label from a DNS name.
yes, it is better indeed

2022-09-21 16:46 UTC, blacksponge commented on lib/Zonemaster/Engine/Normalization.pm
> +Normalize a DNS name.
done

2022-09-21 16:46 UTC, blacksponge commented
I added the NFC conversion tests and updated the documentation.

2022-09-21 16:56 UTC, matsduf approved these changes
This looks fine. I have not run any tests on it though.

2022-09-22 13:16 UTC, tgreenx reviewed
LGTM, tested and it works as expected.
One thing though, overall I think the code could benefit from an editorial pass on the spacing in every conditional blocks (e.g. `if ( ... )` everywhere) to improve readability but I won't be blocking the PR if it is not done.

2022-11-04 09:37 UTC, pnax submitted a review, later dismissed
lgtm

2022-11-04 09:37 UTC, pnax commented on lib/Zonemaster/Engine/Normalization.pm
> +use Data::Dumper;
Might be safely removed

2022-11-21 10:59 UTC, blacksponge commented on lib/Zonemaster/Engine/Normalization/Error.pm
> +Returns a string representation of the error object, equivalent to message.
fixed

2022-11-21 10:59 UTC, blacksponge commented on lib/Zonemaster/Engine/Normalization.pm
> +use Data::Dumper;
fixed

2022-11-21 15:32 UTC, matsduf submitted a review, later dismissed

2022-11-23 10:18 UTC, tgreenx reviewed
One typo else ready to approve

2022-11-23 10:18 UTC, tgreenx commented on lib/Zonemaster/Engine/Normalization/Error.pm
> +Returns a string representation of the error object. Euivalent to message().
Euivalent -> Equivalent

2022-11-24 10:34 UTC, blacksponge commented on lib/Zonemaster/Engine/Normalization/Error.pm
> +Returns a string representation of the error object. Euivalent to message().
Fixed

2022-11-24 13:46 UTC, tgreenx approved these changes

2022-11-24 23:15 UTC, matsduf approved these changes

2022-11-28 09:25 UTC, merged

2022-12-13 16:15 UTC, matsduf commented
Updated by #1157