Remove some unintended network dependencies from the unit tests
zonemaster/zonemaster-engine pull request #1045
Opened 2022-03-23 09:29 UTC by mattias-p

## Purpose

This PR make the unit tests no autocomplete fake glue by sending out DNS requests.

## Context

Fixes #888.

## Changes

A new method Zonemaster::Engine->add_fake_delegation_raw() is factored out from Zonemaster::Engine->add_fake_delegation(). The new method performs the meat of things but without the bells and whistles like autocompleting fake glue and returning a boolean. (I don't think the return value is ever used and it's kind of nonsense anyway. Maybe I should have removed it altogether.)

## How to test this PR

1. In one terminal run `sudo tcpdump -nn port 53` and keep it open.
2. In another terminal run `make test` and wait for it to complete.
3. Make sure tcpdump didn't list any DNS requests from the tests.

2022-03-25 08:41 UTC, matsduf commented
If a "fake delegation" is something like
```
        'lysator.liu.se' => {
            'ns1.nic.fr' => [],
            'ns.nic.se'  => []
        }
```
then the IP address or addresses of ns1.nic.fr and ns.nic.se should be looked up on a resolver (built-in or external). As I read it add_fake_delegation_raw() will instead output 'FAKE_DELEGATION_NO_IP'. Do I read it wrong?

2022-03-25 09:26 UTC, matsduf commented
In a second inspection, I think the idea is to use add_fake_delegation_raw() for unit tests and add_fake_delegation() else. Is that correct?

2022-03-25 09:37 UTC, matsduf reviewed
There is also a Zonemaster::Engine::Nameserver::add_fake_delegation() but I cannot see that it is used.

2022-03-25 09:37 UTC, matsduf commented on lib/Zonemaster/Engine.pm
> +    }
What is the purpose of this test? Does not add_fake_delegation_raw doing that job?

2022-03-25 16:24 UTC, mattias-p commented on lib/Zonemaster/Engine.pm
> +    }
This is one of the differences between `add_fake_delegation()` and `add_fake_delegation_raw()`. The former has a boolean return type and the latter has a void return type. I kept the return value semantics of `add_fake_delegation()` unchanged for compatibility reasons. However I can't see any use cases for the return value. Maybe it would be better to just remove it.

2022-03-31 06:44 UTC, mattias-p commented
>  The two methods, add_fake_delegation_raw() and add_fake_delegation(), have very much overlap in logic. Why not have just one method and a input variable, say $raw, and if that is set it does not do any lookups for IP addresses?

Good point. I'll change it to use some kind of flag instead.

2022-05-16 10:17 UTC, matsduf requested changes

2022-05-16 10:17 UTC, matsduf commented on lib/Zonemaster/Engine.pm
> +addresses.
If the name sever name is an strict in-bailiwick then a missing address should never be looked up. What is "ib" in the flag name? Wouldn't "fill_in_empty_ob_glue" be better?

I suggest that the terms *in-bailiwick* and *out-of-bailiwick* (hyphened) are used (https://datatracker.ietf.org/doc/html/rfc8499)

2022-05-16 10:17 UTC, matsduf commented on lib/Zonemaster/Engine.pm
> +returns 1.
I think the specification says that undef should be returned, depending on what you mean by glue. The se zone should never include glue for ns1.nic.fr in this case, but I am not sure that `add_fake_delegation` judge that.

2022-05-16 10:17 UTC, matsduf commented on lib/Zonemaster/Engine.pm
> +    }
Will this fill in a strict in-bailiwick name server's IP address? It should not.

2022-05-16 10:18 UTC, matsduf commented
The milestone is till set to v2022.2.

2022-05-16 14:19 UTC, mattias-p commented on lib/Zonemaster/Engine.pm
> +    }
It does not. However misnamed the flag. I'll fix that.

2022-05-16 14:20 UTC, mattias-p commented on lib/Zonemaster/Engine.pm
> +addresses.
I'll make updates.

2022-05-16 14:34 UTC, mattias-p commented on lib/Zonemaster/Engine.pm
> +returns 1.
Yeah, I don't think the return value is meaningful at all. I only kept it out of the principle to minimize API changes. And I only documented it out of a sense of duty. I was thinking I'd remove the return value entirely in a follow-up PR, but I might as well do it in this one. WDYT?

2022-05-16 14:47 UTC, matsduf commented on lib/Zonemaster/Engine.pm
> +returns 1.
Here I guess fail and success are the possible outcome, if anything is missing should be determined by the testing.

Fail: The data does not match the API for this method and cannot be loaded.

Success: The data matches the API for this method and can be loaded.

Data can be with or without IP address. I guess data can be with our without name server too.

2022-05-16 14:56 UTC, mattias-p commented on lib/Zonemaster/Engine.pm
> +returns 1.
Do you know if we have other breaking changes in Engine? I looked but I couldn't see anything obvious. I'd rather not force a version number bump just for this.

2022-05-16 14:57 UTC, matsduf approved these changes

2022-05-17 10:10 UTC, tgreenx reviewed
Two comments else lgtm, ready to approve afterwards

2022-05-17 10:28 UTC, mattias-p commented on lib/Zonemaster/Engine.pm
> +                if ( !@{ $href->{$name} } ) {
It's actually not redundant since $href->{$name} might be updated on line 130. But I guess there's a better way to express this. I'll make an update.

2022-05-17 10:31 UTC, mattias-p commented on lib/Zonemaster/Engine.pm
> +                Zonemaster::Engine->logger->add(    #
It's just there to force perltidy to insert a line break.

2022-05-17 13:56 UTC, tgreenx approved these changes

2022-05-17 15:36 UTC, merged