Implementation update for DNSSEC02
zonemaster/zonemaster-engine pull request #1051
Opened 2022-04-14 09:11 UTC by tgreenx

## Purpose

The purpose of this PR is three-fold, according to [#1056](https://github.com/zonemaster/zonemaster/pull/1056):
 - Fixes handling of unimplemented digest algorithm.
 - Changes default level of two messages from ERROR to WARNING.
 - Adds checks for DNS responses.

## Context

Fixes #1049
Fixes [#1036](https://github.com/zonemaster/zonemaster/issues/1036)

## How to test this PR

```
zonemaster-cli --test DNSSEC/dnssec02 --show-testcase 249.200.193.in-addr.arpa --raw --level INFO
   0.00 INFO      UNSPECIFIED    GLOBAL_VERSION   version=v4.4.0
   3.96 ERROR     DNSSEC02       DS02_NO_MATCH_DS_DNSKEY   keytag=13114; ns_ip_list=94.228.98.98;94.228.99.99
```

2022-04-14 09:23 UTC, matsduf commented
> ## How to test this PR
> 
> ```
> zonemaster-cli --test DNSSEC/dnssec02 --show-testcase 249.200.193.in-addr.arpa --raw --level INFO
>    0.00 INFO      UNSPECIFIED    GLOBAL_VERSION   version=v4.4.0
>    3.96 ERROR     DNSSEC02       DS02_NO_MATCH_DS_DNSKEY   keytag=13114; ns_ip_list=94.228.98.98;94.228.99.99
> ```

There is also recorded data in #1048 to be used if the problematic DS record has been removed from the parent zone.

But the result here does not follow the specification. The problematic DS recod should just be ignored.

2022-04-14 09:27 UTC, matsduf requested changes
A DS record that is used with a digest algorithm that Zonemaster does not have any support for should be ignored.

2022-04-14 09:55 UTC, tgreenx commented
Changes addressed in latest commit, please re-review @matsduf.

`zonemaster-cli --test DNSSEC/dnssec02 --show-testcase 249.200.193.in-addr.arpa --raw --level INFO
   0.00 INFO      UNSPECIFIED    GLOBAL_VERSION   version=v4.4.0`

2022-04-14 10:16 UTC, matsduf commented
I am sorry, my comments were unclear. The DS record should be ignored in respect to its digest matching the DNSKEY. The test case should still verify the DNSKEY that the DS record points at.

In step 5.3 we check if Zonemaster can handle the digest algorithm. If not (5.3.1) we skip verification. If we do (5.3.2 we will take note if the digest check fails. In both cases we continue with steps 5.4 to 5.9.

There is no reason to handle digest algorithms 1-4 special. The specification says that we should handle all digest algorithms the same.

```
    5. For each DS in *DS Records*, do:
       1. Find the equivalent DNSKEY in *DNSKEY RRs* by key ID (key tag). If
          there is more than one such DNSKEY, select the correct one.
       2. If matching DNSKEY is not found add DS key tag and name server IP to
          the *No DNSKEY for DS* set and go to next DS.
       3. Verify if the Zonemaster installation has support for the digest
          algorithm that created the DS:
          1. If no support, then ignore the following test if the DS matches
             the DNSKEY.
          2. Else, if the DS values (algorithm and digest) do not match the
             DNSKEY record then add DS key tag and name server IP to the
             *No match DS DNSKEY* set.
       4. If bit 7 of the DNSKEY flags field is unset (value 0), then add DS key
          tag and name server IP to the *DNSKEY not for zone signing* set.
       5. If bit 15 of the DNSKEY flags field is unset (value 0), then add the
          DNSKEY record key tag and name server IP to the *DNSKEY not SEP*
          set.
       6. Find the equivalent RRSIG in *DNSKEY RRSIG* by key ID (key tag). If
          there is more than one such RRSIG record, select the correct one.
       7. If matching RRSIG is not found, add DNSKEY record key tag and name
          server IP to the *No matching DNSKEY RRSIG* set.
       8. Else, if the Zonemaster installation does not have support for the
          DNSKEY algorithm that created the RRSIG, then add name server IP,
          DNSKEY algorithm and DNSKEY key tag to the *Algo Not Supported By ZM*
          set.
       9. Else, if the RRSIG values (algorithm and signature) do not match
          the DNSKEY then add the key tag from the RRSIG record and name server
          IP to the *RRSIG not valid by DNSKEY* set.
```
(From https://raw.githubusercontent.com/zonemaster/zonemaster/develop/docs/specifications/tests/DNSSEC-TP/dnssec02.md)

2022-04-14 15:12 UTC, tgreenx commented
I believe I have made the appropriate fix, please re-review @matsduf.

```
zonemaster-cli --test DNSSEC/dnssec02 --show-testcase 249.200.193.in-addr.arpa --raw --level INFO
0.00 INFO      UNSPECIFIED    GLOBAL_VERSION   version=v4.4.0
```

PS: The specification says, [line 156](https://github.com/zonemaster/zonemaster/blame/develop/docs/specifications/tests/DNSSEC-TP/dnssec02.md#L156): `If there is more than one such DNSKEY, select the correct one.` How is that choice supposed to be made? In the implementation, that choice seems to be made from this loop, [lines 1501 to 1510](https://github.com/zonemaster/zonemaster-engine/blob/master/lib/Zonemaster/Engine/Test/DNSSEC.pm#L1501-L1510), which looks at the digest between the DNSKEY and the DS. In our case (i.e., when that check can't be made due to unsupported digest algorithms) I have made the change so that the first DNSKEY with the appropriate keytag is selected for further testing, even if others (with same keytag) exist. Is that ok?

2022-04-14 15:46 UTC, matsduf commented
> PS: The specification says, [line 156](https://github.com/zonemaster/zonemaster/blame/develop/docs/specifications/tests/DNSSEC-TP/dnssec02.md#L156): `If there is more than one such DNSKEY, select the correct one.` How is that choice supposed to be made?

The DS record uses the key tag to refer to the DNSKEY its digest is based on. The key tag is calculated from the DNSKEY. If the DNSKEY record does not match the DS by key tag, then it is ignored. If key tag matches, DNSKEY algorithm must also match.

Key tag is a 16-bit integer, which means that the could are many DNSKEY records with the same key tag. And it is possible that there are more than one DNSKEY for the same zone with that same algorithm and key tag, even if it is unlikely. If so, even if it is unlikely, the DS comparison should be done against both (all) to select the correct one, and then that should be selected.

Will the code get too complex for an unlikely case? Should we warn in DNSSEC05 and then ignore one key in other test case if a zone has more than one key with the same algorithm and key tag?

> In the implementation, that choice seems to be made from this loop, [lines 1501 to 1510](https://github.com/zonemaster/zonemaster-engine/blob/master/lib/Zonemaster/Engine/Test/DNSSEC.pm#L1501-L1510), which looks at the digest between the DNSKEY and the DS. In our case (i.e., when that check can't be made due to unsupported digest algorithms) I have made the change so that the first DNSKEY with the appropriate keytag is selected for further testing, even if others (with same keytag) exist. Is that ok?

I think that is OK if they have the same algorithm, but then that is a design issue, and we should update DNSSEC05 an commented above.

2022-04-27 09:59 UTC, tgreenx commented
[...]
> ~I think that is OK if they have the same algorithm, but then that is a design issue, and we should update DNSSEC05 an commented above.~ After thinking about it again I think we must have more correct approach. So what should the test case do if If two or more DNSKEY have the same key tag as the DS record?
> 
>     * If only one of the DNSKEY records has the same algorithm as pointed out by the DS it is simple, select that DNSKEY.
> 
>     * If two or more of the DNSKEY records have the same algortithm as pointed out by the DS, then a comparison with the DS digest must be done.
>       
>       * If none matches, then report that.
>       * Else take the first that matches.

Thanks for the explanation. I understand, however here I am talking about the specific case where that digest comparison can't be done (because the digest algorithm isn't supported by ZM, which is the root cause of this PR). So to be clear: if we have several DNSKEY records that match a DS record by keytag and have the same algorithm, and if a comparison of the digests can't be done, then the first DNSKEY record is selected for further testing.

2022-04-27 10:12 UTC, matsduf commented
> Thanks for the explanation. I understand, however here I am talking about the specific case where that digest comparison can't be done (because the digest algorithm isn't supported by ZM, which is the root cause of this PR). So to be clear: if we have several DNSKEY records that match a DS record by keytag and have the same algorithm, and if a comparison of the digests can't be done, then the first DNSKEY record is selected for further testing.

Yes, that could be fine. We should update the specification. This will, however, be very rare.

2022-04-28 09:52 UTC, pnax approved these changes
lgtm

2022-04-29 08:54 UTC, matsduf requested changes

2022-04-29 08:54 UTC, matsduf commented on lib/Zonemaster/Engine/Test/DNSSEC.pm
>                      }
Let us say that we have one domain with DS digest algorithm 3, not supported by the installation. Then on line 1506 the code will ignore that problem and do not output a message that there is no match. Fine.

Let us say that we have another domain with DS digest algorithm 5, also no supported. But because it is not included in %LDNS_digest_algorithms_supported the code goes another way, and we will get another message outputted, DS02_NO_MATCH_DS_DNSKEY

There should be no difference.

2022-04-29 08:54 UTC, matsduf commented on lib/Zonemaster/Engine/Test/DNSSEC.pm
>                  if ( scalar @matching_keytag_dnskeys == 1 and not $match_ds_dnskey) {
If exact 1, but if 2 or more?

2022-05-02 16:46 UTC, tgreenx commented on lib/Zonemaster/Engine/Test/DNSSEC.pm
>                      }
Actually in that case it will output DS02_NO_DNSKEY_FOR_DS, which is the current behavior of DNSSEC02 (unchanged by this PR). Is that not expected?

2022-05-05 14:32 UTC, tgreenx commented on lib/Zonemaster/Engine/Test/DNSSEC.pm
>                      }
Fixed, behavior will be consistent for any unsupported digest algorithms (either because of unknown algorithm or missing library)

2022-05-05 14:33 UTC, tgreenx commented on lib/Zonemaster/Engine/Test/DNSSEC.pm
>                  if ( scalar @matching_keytag_dnskeys == 1 and not $match_ds_dnskey) {
Fixed. First DNSKEY in matching set will be selected for further testing in case none were correctly selected before.

2022-05-18 17:39 UTC, pnax approved these changes
beside small suggestions, this looks good

2022-05-18 17:39 UTC, pnax commented on lib/Zonemaster/Engine/Test/DNSSEC.pm
>                      if ( exists $LDNS_digest_algorithms_supported{$ds->digtype()} ) {
I think the `if ( exists ... )` could be moved outside the `foreach`.

2022-05-18 17:39 UTC, pnax commented on lib/Zonemaster/Engine/Test/DNSSEC.pm
> +                    }
In case the `if ( exists ... )` is moved outside the foreach, I think this `else` block can be safely removed.

2022-05-18 17:39 UTC, pnax commented on lib/Zonemaster/Engine/Test/DNSSEC.pm
>                      if ( exists $LDNS_digest_algorithms_supported{$ds->digtype()} ) {
maybe add a comment that we need to check that Zonemaster supports the algorithm to look for the correct DNSKEY in case there are several ones.

2022-05-19 08:04 UTC, merged