Implementation update of DNSSEC01
zonemaster/zonemaster-engine pull request #1059
Opened 2022-04-28 16:48 UTC by tgreenx

## Purpose

This PR proposes an implementation update to DNSSEC01.

Regarding the digest test, I have not found a workaround other than what is done for DNSSEC02, i.e. create a new DS from a DNSKEY and calling _hexdigest()_. Thus, it requires a DNSKEY which means I had to add a DNSKEY query (which is not a step mentioned in the specification). (See lines 1357-1372). If you have another suggestion let me know.

## Context

Fixes #1057 

## How to test this PR

`zonemaster-cli --test DNSSEC/dnssec01 --show-testcase . --level INFO`
`zonemaster-cli --test DNSSEC/dnssec01 --show-testcase zonemaster.fr --ns ns1.example.com/192.168.23.23 --ds 12345,3,1,123456789abcdef67890123456789abcdef67890  --level=INFO`
`zonemaster-cli --test DNSSEC/dnssec01 --show-testcase 249.200.193.in-addr.arpa --level INFO`

2022-05-02 15:00 UTC, matsduf requested changes

2022-05-02 15:00 UTC, matsduf commented on lib/Zonemaster/Engine/Test/DNSSEC.pm
>      if ( my $parent = $zone->parent ) {
When is this false? There are possible cases when the domain in a predelegated test does not have a defined parent. Would such a test be skipped? - If, in my example, DS data is provided, it is still valid to run this test case.

2022-05-02 15:00 UTC, matsduf commented on lib/Zonemaster/Engine/Test/DNSSEC.pm
> +    }
I think this is a deviation from the specification. According to the specification, if the root zone is provided as a predelegated test with DS data, it will be tested. But not in this implementation.

2022-05-02 15:00 UTC, matsduf commented on lib/Zonemaster/Engine/Test/DNSSEC.pm
>          foreach my $ns ( @{ $parent->ns } ) {
If this is a predelegated test it is not meaningful to ask for parent NS. They might be unknown.

2022-05-02 15:00 UTC, matsduf commented on lib/Zonemaster/Engine/Test/DNSSEC.pm
> +                    my $dnskey_p = $ns->query( $zone->name, q{DNSKEY}, { dnssec => 1, usevc => 0 } );
It is of course possible to get a DNSKEY record in that way, but it is also possible to use a canned DNSKEY record. Here we can test on any valid DNSKEY from any zone or just a constructed DNSKEY. If a canned DNSKEY is used a look-up is saved and the risk that look-up fails is eliminated.

2022-05-02 15:00 UTC, matsduf commented on lib/Zonemaster/Engine/Test/DNSSEC.pm
> -              NO_RESPONSE_DS
The message N_RESPONSE_DS is also referred to on lines 226-230 in subroutine `all()`:
```perl
        if ( none { $_->tag eq 'NO_RESPONSE_DS' } @results ) {
            if ( Zonemaster::Engine::Util::should_run_test( q{dnssec02} ) ) {
                push @results, $class->dnssec02( $zone );
            }
        }
```

2022-05-03 08:57 UTC, tgreenx commented on lib/Zonemaster/Engine/Test/DNSSEC.pm
>      if ( my $parent = $zone->parent ) {
I am not sure if there are cases where this can be false. Anyhow, if a parent can't be determined, Engine will crash before this testcase can be run, during the processing of DS data inputs, see [here](https://github.com/zonemaster/zonemaster-engine/blob/master/lib/Zonemaster/Engine.pm#L159-L161)

2022-05-03 09:00 UTC, tgreenx commented on lib/Zonemaster/Engine/Test/DNSSEC.pm
> +    }
Fixed

2022-05-03 09:15 UTC, tgreenx commented on lib/Zonemaster/Engine/Test/DNSSEC.pm
>          foreach my $ns ( @{ $parent->ns } ) {
In the code, DS records submitted in the case of an undelegated test are added per nameserver. They can't be treated on their own as the specification suggests, they are linked to a Engine::Nameserver object. See [here ](https://github.com/zonemaster/zonemaster-engine/blob/master/lib/Zonemaster/Engine.pm#L155-L168) and [here](https://github.com/zonemaster/zonemaster-engine/blob/master/lib/Zonemaster/Engine/Nameserver.pm#L355-L380).

2022-05-03 10:08 UTC, tgreenx commented on lib/Zonemaster/Engine/Test/DNSSEC.pm
> +            foreach my $ds (@dss) {
Fixed

2022-05-03 10:09 UTC, tgreenx commented on lib/Zonemaster/Engine/Test/DNSSEC.pm
> -              NO_RESPONSE_DS
Fixed

2022-05-03 12:45 UTC, tgreenx commented on lib/Zonemaster/Engine/Test/DNSSEC.pm
> +                    my $dnskey_p = $ns->query( $zone->name, q{DNSKEY}, { dnssec => 1, usevc => 0 } );
Fixed

2022-05-03 15:06 UTC, matsduf commented on lib/Zonemaster/Engine/Test/DNSSEC.pm
>      if ( my $parent = $zone->parent ) {
There are cases when it is not possible to determine parent zone of an undelegated domain, but I do not know how the Zonemaster implementation handles those. It should be investigated.

2022-05-03 15:07 UTC, matsduf commented on lib/Zonemaster/Engine/Test/DNSSEC.pm
>          foreach my $ns ( @{ $parent->ns } ) {
That is a problem because that can give nonsense messages.

2022-05-03 17:15 UTC, tgreenx commented on lib/Zonemaster/Engine/Test/DNSSEC.pm
>      if ( my $parent = $zone->parent ) {
In any types of test, if the parent zone can't be determined, it will default to _undef_. See [here](https://github.com/zonemaster/zonemaster-engine/blob/master/lib/Zonemaster/Engine/Zone.pm#L27-L38).

2022-05-03 17:18 UTC, tgreenx commented on lib/Zonemaster/Engine/Test/DNSSEC.pm
>          foreach my $ns ( @{ $parent->ns } ) {
Yes, I am trying to find a workaround to still be able to run this testcase according to the specifications, but so far I've got none.

2022-05-04 10:17 UTC, matsduf commented on lib/Zonemaster/Engine/Test/DNSSEC.pm
>          foreach my $ns ( @{ $parent->ns } ) {
There are three issues (deviations between specification and implementation):
1. DS record for undelegated zone are connected to parent's NS.
2. Undelegated zone must have working parent NS.
3. Undelegated zone must have a determined parent.
 
I have listed the issues in order of severity. Issue (1) is definitely the most irritating limitation. It is an expected use case and gives nonsense messages.

Issues (2) and (3) are not very expected. It assumes that you do an undelegated test of a domain that is below some zone with many issues.

If it is possible to resolve (1) then it would be good, but it does not kill Zonemaster.

I think we can continue to live with (2) and (3), but we should either decide not to handle it, and then update the specifications (in several places), or resolve it in the implementation.

2022-05-05 14:38 UTC, matsduf commented
Unit test script needs update:
```
t/Test-dnssec.t ........... 33/? 
#   Failed test 'nic.se gives DS_ALGO_SHA1_DEPRECATED'
#   at t/Test-dnssec.t line 27.

#   Failed test 'nic.se gives DS_ALGORITHM_OK'
#   at t/Test-dnssec.t line 27.
t/Test-dnssec.t ........... 37/? 
#   Failed test 'seb.se gives DS_ALGORITHM_MISSING'
#   at t/Test-dnssec.t line 27.

#   Failed test 'Only one (useful) message'
#   at t/Test-dnssec.t line 80.
#          got: '2'
#     expected: '22'
t/Test-dnssec.t ........... 48/? 
#   Failed test 'dnssec01-ds-algorithm-ok.zut-root.rd.nic.fr gives DS_ALGORITHM_OK'
#   at t/Test-dnssec.t line 27.

#   Failed test 'dnssec01-nxdomain.zut-root.rd.nic.fr gives UNEXPECTED_RESPONSE_DS'
#   at t/Test-dnssec.t line 27.
t/Test-dnssec.t ........... 55/? 
#   Failed test 'dnssec01-ds-algorithm-not-ds.zut-root.rd.nic.fr gives DS_ALGORITHM_NOT_DS'
#   at t/Test-dnssec.t line 27.

#   Failed test 'dnssec01-ds-algorithm-not-ds.zut-root.rd.nic.fr gives DS_ALGORITHM_MISSING'
#   at t/Test-dnssec.t line 27.
t/Test-dnssec.t ........... 61/? 
#   Failed test 'dnssec01-ds-algorithm-deprecated1.zut-root.rd.nic.fr gives DS_ALGO_SHA1_DEPRECATED'
#   at t/Test-dnssec.t line 27.

#   Failed test 'dnssec01-ds-algorithm-deprecated1.zut-root.rd.nic.fr gives DS_ALGORITHM_MISSING'
#   at t/Test-dnssec.t line 27.
t/Test-dnssec.t ........... 67/? 
#   Failed test 'dnssec01-ds-algorithm-deprecated3.zut-root.rd.nic.fr gives DS_ALGORITHM_DEPRECATED'
#   at t/Test-dnssec.t line 27.

#   Failed test 'dnssec01-ds-algorithm-deprecated3.zut-root.rd.nic.fr gives DS_ALGORITHM_MISSING'
#   at t/Test-dnssec.t line 27.

#   Failed test 'dnssec01-ds-algorithm-reserved.zut-root.rd.nic.fr gives DS_ALGORITHM_RESERVED'
#   at t/Test-dnssec.t line 27.

#   Failed test 'dnssec01-ds-algorithm-reserved.zut-root.rd.nic.fr gives DS_ALGORITHM_MISSING'
#   at t/Test-dnssec.t line 27.
t/Test-dnssec.t ........... 758/? # Looks like you failed 14 tests of 762.
t/Test-dnssec.t ........... Dubious, test returned 14 (wstat 3584, 0xe00)
```

2022-05-05 15:17 UTC, matsduf requested changes

2022-05-05 15:17 UTC, matsduf commented on lib/Zonemaster/Engine/Test/DNSSEC.pm
> +    },
If there are many IP addresses the error message is not as visible. Suggest:

DS record for zone {domain} with keytag {keytag} was created by digest algorithm {ds_algo_num} ({ds_algo_mnemo}) which cannot be validated by this installation of Zonemaster. Fetched from the
nameservers with IP addresses "{ns_ip_list}".

("ds_algo_num" and "ds_algo_mnemo" must be added to https://github.com/zonemaster/zonemaster-engine/blob/develop/docs/logentry_args.md. I will create a PR.

2022-05-05 16:07 UTC, matsduf commented on lib/Zonemaster/Engine/Test/DNSSEC.pm
> +    },
The messages needs to be adjusted, but else it seems to work as it should.

2022-05-05 16:10 UTC, tgreenx commented
> Unit test script needs update:
> 
> ```
> t/Test-dnssec.t ........... 33/? 
> #   Failed test 'nic.se gives DS_ALGO_SHA1_DEPRECATED'
> #   at t/Test-dnssec.t line 27.
> 
> #   Failed test 'nic.se gives DS_ALGORITHM_OK'
> #   at t/Test-dnssec.t line 27.
> t/Test-dnssec.t ........... 37/? 
> #   Failed test 'seb.se gives DS_ALGORITHM_MISSING'
> #   at t/Test-dnssec.t line 27.
> 
> #   Failed test 'Only one (useful) message'
> #   at t/Test-dnssec.t line 80.
> #          got: '2'
> #     expected: '22'
> t/Test-dnssec.t ........... 48/? 
> #   Failed test 'dnssec01-ds-algorithm-ok.zut-root.rd.nic.fr gives DS_ALGORITHM_OK'
> #   at t/Test-dnssec.t line 27.
> 
> #   Failed test 'dnssec01-nxdomain.zut-root.rd.nic.fr gives UNEXPECTED_RESPONSE_DS'
> #   at t/Test-dnssec.t line 27.
> t/Test-dnssec.t ........... 55/? 
> #   Failed test 'dnssec01-ds-algorithm-not-ds.zut-root.rd.nic.fr gives DS_ALGORITHM_NOT_DS'
> #   at t/Test-dnssec.t line 27.
> 
> #   Failed test 'dnssec01-ds-algorithm-not-ds.zut-root.rd.nic.fr gives DS_ALGORITHM_MISSING'
> #   at t/Test-dnssec.t line 27.
> t/Test-dnssec.t ........... 61/? 
> #   Failed test 'dnssec01-ds-algorithm-deprecated1.zut-root.rd.nic.fr gives DS_ALGO_SHA1_DEPRECATED'
> #   at t/Test-dnssec.t line 27.
> 
> #   Failed test 'dnssec01-ds-algorithm-deprecated1.zut-root.rd.nic.fr gives DS_ALGORITHM_MISSING'
> #   at t/Test-dnssec.t line 27.
> t/Test-dnssec.t ........... 67/? 
> #   Failed test 'dnssec01-ds-algorithm-deprecated3.zut-root.rd.nic.fr gives DS_ALGORITHM_DEPRECATED'
> #   at t/Test-dnssec.t line 27.
> 
> #   Failed test 'dnssec01-ds-algorithm-deprecated3.zut-root.rd.nic.fr gives DS_ALGORITHM_MISSING'
> #   at t/Test-dnssec.t line 27.
> 
> #   Failed test 'dnssec01-ds-algorithm-reserved.zut-root.rd.nic.fr gives DS_ALGORITHM_RESERVED'
> #   at t/Test-dnssec.t line 27.
> 
> #   Failed test 'dnssec01-ds-algorithm-reserved.zut-root.rd.nic.fr gives DS_ALGORITHM_MISSING'
> #   at t/Test-dnssec.t line 27.
> t/Test-dnssec.t ........... 758/? # Looks like you failed 14 tests of 762.
> t/Test-dnssec.t ........... Dubious, test returned 14 (wstat 3584, 0xe00)
> ```

Done. Not sure what to do with test zone "seb.se" though (see [here](https://github.com/zonemaster/zonemaster-engine/pull/1059/files#diff-9b39f87b4d45d87eef8e1aad7b0c399ab07e140747d776984307c4aa5c421aafR79-R80)), it seems to be correctly configured now? Should we remove it from the test units? Or we leave it and change it as to expect no outputs messages. 

`zonemaster-cli --test DNSSEC/dnssec01 --show-testcase --level INFO --raw seb.se`
`0.00 INFO      UNSPECIFIED    GLOBAL_VERSION   version=v4.4.0`

2022-05-05 16:27 UTC, tgreenx commented
Also, note that test unit behavior will change (i.e., partially fail) for zone "dnssec01-ds-algorithm-deprecated3.zut-root.rd.nic.fr", which uses digest algorithm 3 (GOST), as the output of "DS01_DIGEST_NOT_SUPPORTED_BY_ZM" is expected by default but dependent on the underlying OpenSSL installation.

2022-05-06 14:32 UTC, matsduf commented
There are errors in the unit tests:
```
t/Test-dnssec.t ........... 33/? 
#   Failed test 'nic.se does not give DS01_DS_ALGO_SHA1_DEPRECATED'
#   at t/Test-dnssec.t line 38.
t/Test-dnssec.t ........... 41/? 
#   Failed test 'seb.se gives DS01_DS_ALGO_2_MISSING'
#   at t/Test-dnssec.t line 27.

#   Failed test 'Only one (useful) message'
#   at t/Test-dnssec.t line 80.
#          got: '2'
#     expected: '22'
t/Test-dnssec.t ........... 765/? # Looks like you failed 3 tests of 771.
t/Test-dnssec.t ........... Dubious, test returned 3 (wstat 768, 0x300)
Failed 3/771 subtests 
```

2022-05-06 16:47 UTC, matsduf reviewed
Besides the issue with the unit tests I am ready to approve.

2022-05-09 08:26 UTC, tgreenx commented
> > Also, note that test unit behavior will change (i.e., partially fail) for zone "dnssec01-ds-algorithm-deprecated3.zut-root.rd.nic.fr", which uses digest algorithm 3 (GOST), as the output of "DS01_DIGEST_NOT_SUPPORTED_BY_ZM" is expected by default but dependent on the underlying OpenSSL installation.
> 
> Since it is possible to make Zonemaster support GOST it would be better to have a DS record with some non-existent DS algorithm to verify the DS01_DIGEST_NOT_SUPPORTED_BY_ZM behavior.

This is covered by this [test](https://github.com/zonemaster/zonemaster-engine/pull/1059/files#diff-9b39f87b4d45d87eef8e1aad7b0c399ab07e140747d776984307c4aa5c421aafR119-R120).

```
zonemaster-cli --test DNSSEC/dnssec01 --show-testcase --level INFO dnssec01-ds-algorithm-reserved.zut-root.rd.nic.fr --raw
   0.00 INFO      UNSPECIFIED    GLOBAL_VERSION   version=v4.4.0
   1.79 ERROR     DNSSEC01       DS01_DS_ALGO_RESERVED   domain=dnssec01-ds-algorithm-reserved.zut-root.rd.nic.fr; ds_algo_num=157; keytag=10591; ns_ip_list=145.239.76.200;145.239.76.202
   1.79 NOTICE    DNSSEC01       DS01_DIGEST_NOT_SUPPORTED_BY_ZM   domain=dnssec01-ds-algorithm-reserved.zut-root.rd.nic.fr; ds_algo_mnemo=Unassigned; ds_algo_num=157; keytag=10591; ns_ip_list=145.239.76.200;145.239.76.202
   1.79 NOTICE    DNSSEC01       DS01_DS_ALGO_2_MISSING   domain=dnssec01-ds-algorithm-reserved.zut-root.rd.nic.fr
```

2022-05-09 09:24 UTC, tgreenx commented
> There are errors in the unit tests:
> 
> ```
> t/Test-dnssec.t ........... 33/? 
> #   Failed test 'nic.se does not give DS01_DS_ALGO_SHA1_DEPRECATED'
> #   at t/Test-dnssec.t line 38.
> t/Test-dnssec.t ........... 41/? 
> #   Failed test 'seb.se gives DS01_DS_ALGO_2_MISSING'
> #   at t/Test-dnssec.t line 27.
> 
> #   Failed test 'Only one (useful) message'
> #   at t/Test-dnssec.t line 80.
> #          got: '2'
> #     expected: '22'
> t/Test-dnssec.t ........... 765/? # Looks like you failed 3 tests of 771.
> t/Test-dnssec.t ........... Dubious, test returned 3 (wstat 768, 0x300)
> Failed 3/771 subtests 
> ```

I can see why this unit test is failing. Looking at the unit test data, it is equivalent to `zonemaster-cli --test DNSSEC/dnssec01 --show-testcase --level INFO seb.se --raw --ns ns1.seb.se`, so it is an undelegated test, with no DS record provided. Unless I misunderstood, it is compliant with the specification (see [here](https://github.com/zonemaster/zonemaster/pull/1057/files#diff-e32acd6b6ef413ca567996c8cd252590362b3e294129de4e17c740222f6eaddbR118)). Can you clarify this @matsduf ?

2022-05-18 12:39 UTC, mvw-afnic approved these changes
Looks good to me.

2022-05-18 19:52 UTC, merged

2022-05-18 20:02 UTC, tgreenx commented
@matsduf I'll let you open an issue for the [aforementioned ](https://github.com/zonemaster/zonemaster-engine/pull/1059#discussion_r864672867) discrepancies if you want

2022-05-18 22:15 UTC, matsduf commented
> @matsduf I'll let you open an issue for the [aforementioned ](https://github.com/zonemaster/zonemaster-engine/pull/1059#discussion_r864672867) discrepancies if you want

https://github.com/zonemaster/zonemaster/issues/1063