Installation instructions for CentOS 7
zonemaster/zonemaster-engine pull request #1080
Opened 2022-05-23 16:19 UTC by pnax

## Purpose

This reinstates installation instructions for CentOS 7 but with support for DNSSEC algos 15 and 16.

## Context

based on [zonemaster/zonemaster-ldns#](https://github.com/zonemaster/zonemaster-ldns/pull/134)

## Changes

New section for CentOS 7 in installation document with specific instruction to install Zonemaster::LDNS.

## How to test this PR

Following the installation instruction should result in a properly working Zonemaster instance with support for DNSSEC algo 15 and 16.

2022-05-23 17:30 UTC, blacksponge approved these changes
Tested by installing Zonemaster CLI on containerized Centos 7 and running `zonemaster-cli --no-ipv6 --test DNSSEC --level info ed25519.nl`, working fine.

2022-05-23 19:31 UTC, matsduf requested changes
I will update https://github.com/zonemaster/zonemaster/pull/1060 to match the fact that algo 15 and 16 are supported.

2022-05-23 19:31 UTC, matsduf commented on docs/Installation.md
> +
Add something like

> **Please note!** CentOS 7 will only be supported until the release of v2023.1, which is expected to happen during the spring of 2023. Consider Rocky Linux for an alternative Red Hat Linux derivative.

2022-05-24 06:43 UTC, mattias-p commented on docs/Installation.md
> +
Maybe also encourage people to let us know what they're migrating to? Now, I don't expect anyone to actually make an effort to tell us. But I think it's good thing PR-wise to give people a feeling that we care about how they're using Zonemaster.

2022-05-24 06:46 UTC, mattias-p commented on docs/Installation.md
> +4) Install Zonemaster::LDNS with DNSSEC 15 and 16 support:
`DNSSEC 15 and 16` -> `DNSSEC algorithm 15 and 16`?

2022-05-24 07:50 UTC, matsduf commented on docs/Installation.md
> +4) Install Zonemaster::LDNS with DNSSEC 15 and 16 support:
```
Install Zonemaster::LDNS with support for DNSKEY algorithms 15 and 16
```

2022-05-24 09:49 UTC, mattias-p approved these changes
lgtm

2022-05-24 12:22 UTC, merged