Updated and added norwegian translation texts
zonemaster/zonemaster-engine pull request #1083
Opened 2022-05-24 08:43 UTC by repperille

## Purpose

This PR includes new and updated translations to Norwegian language

## Context

Fixes #1078 

## Changes

...

## How to test this PR

...

2022-05-30 13:54 UTC, matsduf requested changes

2022-05-30 13:54 UTC, matsduf commented on share/nb.po
> +"navnetjenere med IP-adressene ({ns_ip_list})."
The part "while still being widely in use" is missing from the translation.

2022-05-30 13:54 UTC, matsduf commented on share/nb.po
> +"Hentet fra navnetjenere med IP-adressene ({ns_ip_list})."
Do you use "feilkode" for RCODE? In RFC 1035 it is called "response code". In next message you have used "RCODE" directly.

2022-06-01 15:30 UTC, mattias-p submitted a review, later dismissed
lgtm

2022-06-20 11:55 UTC, matsduf commented
@repperille, can you look at my comments on your PR? Just small things.

2022-06-21 10:52 UTC, repperille commented on share/nb.po
> +"Hentet fra navnetjenere med IP-adressene ({ns_ip_list})."
I have changed to RCODE in updated PR

2022-06-21 10:56 UTC, repperille commented on share/nb.po
> +"navnetjenere med IP-adressene ({ns_ip_list})."
Is this comment really necessary?
The message is about deprecation: DNSSEC:DS01_DS_ALGO_SHA1_DEPRECATED
The fact that it is widely in use does not change the fact that it is deprecated.

2022-06-22 08:48 UTC, matsduf commented on share/nb.po
> +"navnetjenere med IP-adressene ({ns_ip_list})."
Your objection does have some relevance, but that is rather on the msgid, rather than on the Norwegian translation.

The background is that we decided, two years ago, to lower the level on messges on SHA1 digests from ERROR to WARNING becasue it was too much in use, but then to give it a special message. I do not feel that it is relevant to have such a special treatment anymore, and I think we should have removed that and let SHA1 be given the message DS01_DS_ALGO_DEPRECATED with default level ERROR. I will initiate that for next release.

Given the msgid I still think that you translation excludes a part.

2022-06-22 09:08 UTC, matsduf commented
https://github.com/zonemaster/zonemaster/pull/1073 is the first step to remove the special message for SHA1.

2022-06-23 13:41 UTC, repperille commented on share/nb.po
> +"navnetjenere med IP-adressene ({ns_ip_list})."
I have now added a translation to the excluded part.

2022-06-26 13:06 UTC, matsduf commented on share/nb.po
> +"navnetjenere med IP-adressene ({ns_ip_list})."
Thanks!

2022-06-26 13:06 UTC, matsduf approved these changes

2022-07-06 14:07 UTC, merged