Missing update of ns args in SYSTEM messages
zonemaster/zonemaster-engine pull request #1097
Opened 2022-07-19 15:54 UTC by pnax

## Purpose

Commit 766c1116 (PR #792) missed some messages. This fixes it (and reverted the argument based on the conversation here, from "ns_list" to "ns").
Also the query type is logged as well.

## Context

Follow-up on #792 

## Changes

* Test/Zone.pm
* Zone.pm
* Translator.pm: the msgid for SKIP_IPV[46]_DISABLED is updated
* Some refactoring as well

## How to test this PR

The following command should not display `{ns_list}` anymore:
```
zonemaster-cli --no-ipv4 --test zone nic.fr --level DEBUG --show-testcase --show-testcase --locale en_US.UTF-8 | grep "disabled"
```
And the query type should also be logged.

2022-07-19 16:07 UTC, matsduf commented on lib/Zonemaster/Engine/Test/Zone.pm
> +        Zonemaster::Engine->logger->add( SKIP_IPV4_DISABLED => { ns_list => "$ns" } );
Isn't $ns a single name server? If so it should be "ns" not "ns_list".

2022-07-19 21:21 UTC, matsduf commented on lib/Zonemaster/Engine/Test/Zone.pm
> +        Zonemaster::Engine->logger->add( SKIP_IPV4_DISABLED => { ns_list => "$ns" } );
I agree, but I think the correction should be the other way around. It should be "ns" in all places, not "ns_list". See https://github.com/zonemaster/zonemaster-engine/blob/master/docs/logentry_args.md

```
    SKIP_IPV4_DISABLED => sub {
        __x    # SYSTEM:SKIP_IPV4_DISABLED
          "IPv4 is disabled, not sending query to {ns_list}.", @_;
    },
    SKIP_IPV6_DISABLED => sub {
        __x    # SYSTEM:SKIP_IPV6_DISABLED
          "IPv6 is disabled, not sending query to {ns_list}.", @_;
    },
```
(https://github.com/zonemaster/zonemaster-engine/blob/develop/lib/Zonemaster/Engine/Translator.pm#L74-L81)

```
$ grep SKIP_IPV4_DISABLED lib/Zonemaster/Engine/Zone.pm lib/Zonemaster/Engine/Test/Zone.pm
lib/Zonemaster/Engine/Zone.pm:            Zonemaster::Engine->logger->add( SKIP_IPV4_DISABLED => { ns_list => "$ns" } );
lib/Zonemaster/Engine/Zone.pm:        Zonemaster::Engine->logger->add( SKIP_IPV4_DISABLED => { ns_list => ( join ';', map { "$_" } @nope ) } );
lib/Zonemaster/Engine/Zone.pm:            Zonemaster::Engine->logger->add( SKIP_IPV4_DISABLED => { ns_list => "$ns" } );
lib/Zonemaster/Engine/Zone.pm:            Zonemaster::Engine->logger->add( SKIP_IPV4_DISABLED => { ns_list => "$ns" } );
lib/Zonemaster/Engine/Test/Zone.pm:        Zonemaster::Engine->logger->add( SKIP_IPV4_DISABLED => { ns => "$ns" } );
```

2022-07-20 10:58 UTC, pnax commented on lib/Zonemaster/Engine/Test/Zone.pm
> +        Zonemaster::Engine->logger->add( SKIP_IPV4_DISABLED => { ns_list => "$ns" } );
> ```
>  [...]->add( SKIP_IPV4_DISABLED => { ns_list => ( join ';', map { "$_" } @nope ) } );
> ```

This pretty much looks like `@nope` is a list of NS here.

2022-07-20 11:50 UTC, matsduf requested changes

2022-07-20 11:50 UTC, matsduf commented on lib/Zonemaster/Engine/Translator.pm
> +          "IPv6 is disabled, not sending \"{rrtype}\" query to {ns_list}.", @_;
"ns_list" => "ns" both for IPv4 and IPv6

2022-07-20 14:42 UTC, pnax commented on lib/Zonemaster/Engine/Test/Zone.pm
> +        Zonemaster::Engine->logger->add( SKIP_IPV4_DISABLED => { ns_list => "$ns" } );
Ok I found a solution. Instead of joining the NS into a single list, I chose to display on message per item.

2022-07-20 14:52 UTC, matsduf commented on lib/Zonemaster/Engine/Test/Zone.pm
> +        Zonemaster::Engine->logger->add( SKIP_IPV4_DISABLED => { ns_list => "$ns" } );
When a message (msgid) is created it is important to know if it is a list of NS or just a single NS. If it is a list it must be put at the end to make the message readable. If you know that it is just a single NS then you can make a more readable message by putting it earlier.

If a message is by default on INFO or higher level I prefer list to prevent the result to have 5-10 message with the same thing. On DEBUG level I think that multiple messages with single NS makes more sense.

2022-07-27 16:08 UTC, tgreenx approved these changes

2022-08-01 13:45 UTC, matsduf approved these changes

2022-08-01 13:52 UTC, matsduf commented
Do you plan to do anything more in this area?

1. Not all test cases output IPVx_DISABLED.
2. There is another message, SKIP_IPV6_DISABLED
   1. Should there be two different messages?
   2. That message actually means the opposite that it sounds, SKIP_IPV6_DISABLED == IPV6_DISABLED. It is not skipped disabling, it is skipped IPv6.

2022-08-17 10:05 UTC, mattias-p approved these changes
LGTM

2022-09-19 12:32 UTC, merged