Make root hints file configurable
zonemaster/zonemaster-engine pull request #1132
Opened 2022-09-28 13:10 UTC by matsduf

## Purpose

In current code the root hints are hard coded. This PR opens for use cases where private root must be used, see #850. The driving use case for this PR is the possibility to use it for unit tests.

## Context

Fixes #850.

## Changes

Default root hints file is found in shared dist directory, and is used in the normal case. If a root hints file is found in /etc/zonemaster or /usr/local/etc/zonemaster that is used instead. The file name must be `root-hints.json`. Highest priority has the environment variable `ZONEMASTER_ENGINE_ROOT_HINTS_FILE` that can point at any file name, and that file will be used as the root hints file.

## How to test this PR

1. Run a default configuration and validate that nothing breaks.
2. Create a private root zone file and a zone file for some non-existent TLD, e.g. .xa
3. In the root zone, delegate to .xa and load the zones.
4. Create a root hints file in /etc/zonemaster or /usr/local/etc/zonemaster that points at the private root.
5. Run `zonemaster-cli xa --level INFO` and verify that .xa is reported as an existing domain.
6. Rename the root hints file and use `ZONEMASTER_ENGINE_ROOT_HINTS_FILE` and verify that you can still test the .xa domain.

2022-09-28 13:34 UTC, mvw-afnic requested changes

2022-09-28 13:34 UTC, mvw-afnic commented on lib/Zonemaster/Engine/Recursor.pm
> +        $ENV{ZONEMASTER_ENGINE_ROOT_HINTS_FILE}              ? $ENV{ZONEMASTER_ENGINE_ROOT_HINTS_FILE}
Suppose I want to load a root hints file called `0` (unlikely, but still): if I set `ZONEMASTER_ENGINE_ROOT_HINTS_FILE=0` in my environment, that variable won’t be taken into account because "0" is coerced to boolean false.

Using `length $ENV{ZONEMASTER_ENGINE_ROOT_HINTS_FILE}` should work as a test for both existence and non-emptiness of the environment variable.

2022-09-28 13:34 UTC, mvw-afnic commented on lib/Zonemaster/Engine/Recursor.pm
> +file..
There’s an extraneous full stop at the end of this line.

2022-09-28 13:51 UTC, matsduf commented on lib/Zonemaster/Engine/Recursor.pm
> +        $ENV{ZONEMASTER_ENGINE_ROOT_HINTS_FILE}              ? $ENV{ZONEMASTER_ENGINE_ROOT_HINTS_FILE}
I think we had some similar case when the zone name was `0`. I will fix that. I copied the solution from Backend, where loading backend configuration file has the same issue, but I guess it is more theoretical since it is very unlikely that you would name the file `0`.

2022-09-28 14:01 UTC, mvw-afnic approved these changes

2022-09-28 14:41 UTC, pnax commented on lib/Zonemaster/Engine/Recursor.pm
> +If this environment variable is set ot a truthy value, that path is returned.
typo: "ot" -> "at"

2022-09-28 14:41 UTC, pnax commented on lib/Zonemaster/Engine/Recursor.pm
> +=head2 Other mothods
typo: "mothods" -> "methods"

Did you consider promoting all following methods to `=head2` instead?

2022-09-28 14:55 UTC, matsduf commented on lib/Zonemaster/Engine/Recursor.pm
> +If this environment variable is set ot a truthy value, that path is returned.
Re-written.

2022-09-28 14:55 UTC, matsduf commented on lib/Zonemaster/Engine/Recursor.pm
> +=head2 Other mothods
I did, but took the easy path. Updated with `=head2` now.

2022-09-28 15:05 UTC, pnax approved these changes
Nice feature!

2022-10-07 14:34 UTC, matsduf commented
See #1134 for a more complete solution.

2022-10-07 14:34 UTC, closed without merging