Add logentry arguments for SOA SERIAL
zonemaster/zonemaster-engine pull request #1138
Opened 2022-10-12 09:22 UTC by tgreenx

## Purpose

This PR defines logentry arguments for the values of the SERIAL field in an SOA record.

## Context

Needed for https://github.com/zonemaster/zonemaster/pull/1032

## Changes

The following arguments are defined in the [Arguments ](https://github.com/zonemaster/zonemaster-engine/blob/master/docs/logentry_args.md)specification:

- soaserial
- soaserial_list

## How to test this PR

N/A. Documentation only.

2022-10-12 09:54 UTC, matsduf requested changes

2022-10-12 09:54 UTC, matsduf commented on docs/logentry_args.md
> +| soaserial_list | Non-zero positive integers               | A list of numeric values, as specified by "soaserial", separated by ";".|
In the type of value, it should rather be non-negative integer. Zero is a legal value for SOA serial. And the second type of value I suggest "List of non-negative integers".

2022-10-12 12:01 UTC, tgreenx commented on docs/logentry_args.md
> +| soaserial_list | Non-zero positive integers               | A list of numeric values, as specified by "soaserial", separated by ";".|
Indeed, I was unsure at first, but now I found references in RFC1982 indicating that 0 is a legal value. Updated.

2022-10-12 12:22 UTC, pnax approved these changes

2022-10-14 11:41 UTC, matsduf requested changes

2022-10-14 11:41 UTC, matsduf commented on docs/logentry_args.md
> +| soaserial_list | Non-negative integers                    | A list of non-negative integers, as specified by "soaserial", separated by ";".|
Since this is specific SOA serial "Integer in range 0-4,294,967,295" could make sense.

About the second line, in all other cases it says "List of (...)" and to be consistent it should do that here too.

2022-10-18 08:16 UTC, tgreenx commented on docs/logentry_args.md
> +| soaserial_list | Non-negative integers                    | A list of non-negative integers, as specified by "soaserial", separated by ";".|
Updated

2022-10-18 08:27 UTC, matsduf approved these changes

2022-10-19 08:10 UTC, pnax approved these changes

2022-10-19 08:33 UTC, merged