expose the init methods
zonemaster/zonemaster-engine pull request #1151
Opened 2022-11-24 10:18 UTC by blacksponge

## Purpose

In backend (RPCAPI) the INIT block is not run:

```
Too late to run INIT block at /home/../lib/Zonemaster/Engine/Recursor.pm line 28.
```

This PR expose the init methods to make it possible to call it in backend.

## Context

Following a change in https://github.com/zonemaster/zonemaster-engine/pull/1134

## Changes

* Move root hint initialization to a dedicated method
* Expose a global `init_engine` for environment where INIT is not run (when the module is imported at run time).

## How to test this PR

Automatic root hint loading should still work:

```
% perl -MZonemaster::Engine -MData::Dumper -e 'print Data::Dumper::Dumper( [ map { { ns => $_->name->string, ip => $_->address->short} } @{Zonemaster::Engine->zone( "afnic.fr" )->glue} ] )'
$VAR1 = [
          {
            'ns' => 'ns1.nic.fr',
            'ip' => '192.134.4.1'
          },
          {
            'ns' => 'ns1.nic.fr',
            'ip' => '2001:67c:2218:2::4:1'
          },
          {
            'ip' => '192.93.0.4',
            'ns' => 'ns2.nic.fr'
          },
          {
            'ip' => '2001:660:3005:1::1:2',
            'ns' => 'ns2.nic.fr'
          },
          {
            'ip' => '192.134.0.49',
            'ns' => 'ns3.nic.fr'
          },
          {
            'ns' => 'ns3.nic.fr',
            'ip' => '2001:660:3006:1::1:1'
          }
        ];
```

2022-11-24 23:23 UTC, matsduf requested changes

2022-11-24 23:23 UTC, matsduf commented on lib/Zonemaster/Engine.pm
> +    return if $init_done ++;
It should be `$init_done++` not `$init_done ++`, shouldn't it?

2022-11-28 08:38 UTC, blacksponge commented on lib/Zonemaster/Engine.pm
> +    return if $init_done ++;
I don't see what would be the difference, I still changed it to `$init_done++` just in case.

2022-11-28 09:07 UTC, matsduf commented on lib/Zonemaster/Engine.pm
> +    return if $init_done ++;
It seems like "$VAR ++" is accepted in some cases but not in other cases. "$VAR++" is always accepted. In the following code exampel even "$ VAR ++" is accepted. Thank you for updating. It decreases the risk of confusion.
```
% perl -E '$a=1; $ a ++; say $a++;' 
2
```

2022-11-28 10:47 UTC, matsduf approved these changes

2022-11-28 12:14 UTC, merged