Update Nameserver11 to check for OPTION-CODE in EDNS response
zonemaster/zonemaster-engine pull request #1177
Opened 2023-01-12 09:51 UTC by tgreenx

## Purpose

This PR proposes an update to Nameserver11 to check for the OPTION-CODE in an EDNS response.
This requires 

## Context

Fixes #1173 

## Changes

...

## How to test this PR

1) Checkout and install https://github.com/zonemaster/zonemaster-ldns/pull/166 in Zonemaster-LDNS.
2) Checkout this PR in Zonemaster-Engine.

```
$ zonemaster-cli --show-testcase --test nameserver/nameserver11 abundo.se --level info --no-ipv6
Seconds Level     Testcase       Message
======= ========= ============== =======
   0.00 INFO      UNSPECIFIED    Using version v4.6.0 of the Zonemaster engine.
```

3) Change OPT-CODE in query from 137 to 3, in line 1168 of lib/Zonemaster/Engine/Test/Nameserver.pm :
`    my $opt_code = 3;`

4) Then run:
```
$ zonemaster-cli --show-testcase --test nameserver/nameserver11 zonemaster.fr --level info
Seconds Level     Testcase       Message
======= ========= ============== =======
   0.00 INFO      UNSPECIFIED    Using version v4.6.0 of the Zonemaster engine.
   5.59 WARNING   NAMESERVER11   The DNS response contains an unknown EDNS option-code. Returned from name servers "192.134.0.49;192.134.4.1".
```

2023-01-18 07:50 UTC, marc-vanderwal submitted a review, later dismissed
Looks good to me.

2023-01-18 11:05 UTC, matsduf commented
I am waiting for https://github.com/zonemaster/zonemaster-ldns/pull/166 to be completed.

2023-01-19 06:48 UTC, marc-vanderwal requested changes

2023-01-19 06:48 UTC, marc-vanderwal commented on lib/Zonemaster/Engine/Test/Nameserver.pm
> +                my @unpacked_opt = unpack("(n n/a)*", $p_opt);
`unpack` may die if `$p_opt` contains malformed data, which could cause the Zonemaster test case to crash. It’s safer to wrap the call to `unpack` in an `eval { … }` block. That way, `@unpacked_opt` gets assigned the empty list if the OPT RDATA could not be decoded:

```perl
my @unpacked_opt = eval { unpack("(n n/a)*", $p_opt) };
```

2023-01-19 08:59 UTC, tgreenx commented on lib/Zonemaster/Engine/Test/Nameserver.pm
> +                my @unpacked_opt = unpack("(n n/a)*", $p_opt);
Updated

2023-01-19 09:04 UTC, marc-vanderwal approved these changes
Looks good to me.

2023-01-19 15:10 UTC, tgreenx commented
@matsduf please review

2023-01-24 15:41 UTC, pnax approved these changes

2023-01-26 10:26 UTC, merged