Fix bug in Zone01
zonemaster/zonemaster-engine pull request #1178
Opened 2023-01-12 15:52 UTC by tgreenx

## Purpose

This PR proposes an update to Test Case Zone01 following an oversight in #1035.

## Context

Fixes #1175 

## Changes

- Fix missing library import
- Fix code for message tag Z01_MNAME_NOT_MASTER
- Add unit tests
- Add function `serial_gt` in Zonemaster::Util, and its documentation
- Refactoring

## How to test this PR

Unit tests should pass.

But if you want to test manually with zonemaster-cli, create a file (e.g. `local.hints`) with the following content:
```
$ more local.hints
.                              3600000      NS    IBDNS01.LABS.PRIVE.NIC.FR.
IBDNS01.LABS.PRIVE.NIC.FR.     3600000      A     10.1.72.23
.                              3600000      NS    IBDNS01-24.LABS.PRIVE.NIC.FR.
IBDNS01-24.LABS.PRIVE.NIC.FR.  3600000      A     10.1.72.24
```
Then you can do:
```
$ zonemaster-cli --test zone/zone01 --hints local.hints mname-not-master.zone01.xa --level=INFO
Seconds Level     Message
======= ========= =======
   0.00 INFO      Using version v4.6.0 of the Zonemaster engine.
   0.07 WARNING   SOA MNAME name server(s) "ns1.mname-not-master.zone01.xa/10.1.72.23" do not have the highest SOA SERIAL (expected "2022122300" but got "2022122300;2022122301")
```

Also, taken from https://github.com/zonemaster/zonemaster-engine/issues/1175#issuecomment-1380227232:
(note that I disable IPv6 due to my machine limitations at the moment)
```
$ zonemaster-cli --test zone/zone01 hwcdn.net --level=INFO --no-ipv6
Seconds Level     Message
======= ========= =======
   0.00 INFO      Using version v4.6.0 of the Zonemaster engine.
   0.56 WARNING   SOA MNAME name server(s) "ns1.hwcdn.net/69.16.174.10" do not have the highest SOA SERIAL (expected "1673538139" but got "1673538139;1673538142")
```

2023-01-16 07:40 UTC, marc-vanderwal reviewed
Just one small detail, otherwise it looks good to me.

2023-01-16 07:40 UTC, marc-vanderwal commented on lib/Zonemaster/Engine/Test/Zone.pm
> -                    if ( $serial > $mname_serial and ( ($serial - $mname_serial) < 2**($serial_bits - 1) ) ){
That was the only use of the `$serial_bits` variable defined on line 536. It isn’t used anymore, so it can be removed.

2023-01-16 09:29 UTC, marc-vanderwal approved these changes
Looks good to me.

2023-01-16 16:26 UTC, matsduf requested changes

2023-01-16 16:26 UTC, matsduf commented on lib/Zonemaster/Engine/Util.pm
> +}
Let us say 
$sa == 1
$sb == (2^32) -1 = 4,294,967,295

serial_gt ($sa, $sb) will return false, but $sa is a higher SOA serial than $sb.

2023-01-16 16:26 UTC, matsduf commented on lib/Zonemaster/Engine/Util.pm
> +    return ( $sa > $sb and ( ($sa - $sb) < 2**(32 - 1) ) );
Why `2**(32 - 1)` instead of `2**31`?

2023-01-16 17:13 UTC, tgreenx commented on lib/Zonemaster/Engine/Util.pm
> +}
Yes, there are undefined results. From [RFC1982, section 3.2](https://www.rfc-editor.org/rfc/rfc1982#section-3.2):

>    Note that there are some pairs of values s1 and s2 for which s1 is
>    not equal to s2, but for which s1 is neither greater than, nor less
>    than, s2.  An attempt to use these ordering operators on such pairs
>    of values produces an undefined result.

2023-01-17 17:27 UTC, matsduf commented on lib/Zonemaster/Engine/Util.pm
> +}
My example is not undefined. $sa is greater than $sb when compared as SOA serial values.

What is undefined is if two SOA serial values, s1 and s2 meet the following equation:
```
| s1 - s2 | = 2^31
```

2023-01-17 17:29 UTC, matsduf commented on lib/Zonemaster/Engine/Util.pm
> +    return ( $sa > $sb and ( ($sa - $sb) < 2**(32 - 1) ) );
If there as a constant $SERIAL_BITS = 32 then is would make more sense. Maybe references to the RFC could be added?

2023-01-18 07:58 UTC, marc-vanderwal requested changes

2023-01-18 07:58 UTC, marc-vanderwal commented on lib/Zonemaster/Engine/Util.pm
> +}
@matsduf is right: this code won’t take into account rollovers. With serial arithmetic, 4 294 967 295 + 2 equals 1, and according to the definition, 1 > 4 294 967 295.

The correct code is:

```perl
return ( $sa < $sb and ( ($sb - $sa) > 2**31 ) ) or
       ( $sa > $sb and ( ($sa - $sb) < 2**31 ) );
```

2023-01-18 11:13 UTC, tgreenx commented on lib/Zonemaster/Engine/Util.pm
> +    return ( $sa > $sb and ( ($sa - $sb) < 2**(32 - 1) ) );
> If there as a constant $SERIAL_BITS = 32 then is would make more sense. Maybe references to the RFC could be added?

I added such a constant and updated documentation to refer to the relevant RFC section.

2023-01-18 12:24 UTC, marc-vanderwal approved these changes
Looks good to me.

2023-01-18 12:32 UTC, matsduf approved these changes

2023-01-18 12:32 UTC, matsduf commented on lib/Zonemaster/Engine/Constants.pm
> +C<$SERIAL_BITS>
I can see that none of the constants are defined or described, but I think it would make sense to have a short definition or description of the constant. Preferably here in the POD, or else in the code where it is set.

2023-01-18 17:15 UTC, tgreenx commented on lib/Zonemaster/Engine/Constants.pm
> +C<$SERIAL_BITS>
Added documentation

2023-01-18 21:57 UTC, matsduf approved these changes

2023-01-19 06:49 UTC, marc-vanderwal approved these changes

2023-01-19 08:51 UTC, merged