Provide a rule `new-po` to create an empty PO file
zonemaster/zonemaster-engine pull request #1185
Opened 2023-02-01 11:31 UTC by pnax

## Purpose

New Makefile rule to create an empty PO file using the basename provided in the ZM_POLANG variable.

## Context

Addresses https://github.com/zonemaster/zonemaster/issues/1131

## Changes

share/GNUMakefile: add a `new-po` rule

## How to test this PR

Run `make ZM_POLANG=rs new-po` and make sure that the file `rs.po` has been created with empty _msgstr_.

2023-02-01 13:24 UTC, marc-vanderwal commented on share/GNUmakefile
> +new-po: extract-pot
Don’t forget to add `new-po` to the list of [phony targets](https://www.gnu.org/software/make/manual/html_node/Phony-Targets.html) on line 3 in this Makefile.

2023-02-01 14:38 UTC, pnax commented on share/GNUmakefile
> +new-po: extract-pot
Good point. This is added.

2023-02-01 16:10 UTC, marc-vanderwal approved these changes
Looks good to me.

2023-02-01 21:30 UTC, matsduf requested changes
Should really create an error?
```
$ make new-po
gmake[1]: Entering directory '/usr/home/matsd/git/zonemaster-engine/share'
Usage: make POLANG=xx new-po
gmake[1]: *** [GNUmakefile:30: new-po] Error 1
gmake[1]: Leaving directory '/usr/home/matsd/git/zonemaster-engine/share'
*** Error code 2

Stop.
make: stopped in /usr/home/matsd/git/zonemaster-engine/share
```
```
$ make POLANG=sr new-po
gmake[1]: Entering directory '/usr/home/matsd/git/zonemaster-engine/share'
sed: 1: "sr.po": unterminated substitute pattern
gmake[1]: *** [GNUmakefile:32: new-po] Error 1
gmake[1]: Leaving directory '/usr/home/matsd/git/zonemaster-engine/share'
*** Error code 2

Stop.
make: stopped in /usr/home/matsd/git/zonemaster-engine/share
```

2023-02-02 09:31 UTC, pnax commented
> Should really create an error?

Yes for the first error, no for the second. There seems to be an error with the `sed` command. Could you run the following commands?

```
make extract-pot
cp Zonemaster-Engine.pot rs.po
sed -i 's/^"Language: /&rs/' rs.po
```

2023-02-02 10:44 UTC, matsduf commented
> There seems to be an error with the `sed` command. Could you run the following commands?
> 
> ```
> make extract-pot
> cp Zonemaster-Engine.pot rs.po
> sed -i 's/^"Language: /&rs/' rs.po
> ```

```
$ git status --ignored
HEAD detached at pnax/translation-new-po
nothing to commit, working tree clean
$ make extract-pot
gmake[1]: Entering directory '/usr/home/matsd/git/zonemaster-engine/share'
gmake[1]: Leaving directory '/usr/home/matsd/git/zonemaster-engine/share'
$ cp Zonemaster-Engine.pot rs.po
$ sed -i 's/^"Language: /&rs/' rs.po
sed: -I or -i may not be used with stdin
```

Please note that the language code for Serbian is "sr". The country code for Serbia is "rs".

2023-02-02 10:47 UTC, matsduf commented
Here is maybe a fix. FreeBSD requires the suffix to be given, here as ''. Is that OK in Linux?
```
$ cp Zonemaster-Engine.pot rs.po
$ sed -i '' 's/^"Language: /&rs/' rs.po
diff Zonemaster-Engine.pot rs.po 
15c15
< "Language: \n"
---
> "Language: rs\n"
```

2023-02-02 12:47 UTC, matsduf commented on share/GNUmakefile
> +	@sed -i 's/^"Language: /&$(POLANG)/' $(POLANG).po
I think the following will work in both FreeBSD and Linux:
```
        @perl -pi -e 's/^("Language: )/\1$(POLANG)/' $(POLANG).po
```

2023-02-02 13:09 UTC, pnax reviewed
> Please note that the language code for Serbian is "sr". The country code for Serbia is "rs".

Good point, I mixed things up. Thanks for the reminder.

2023-02-02 13:09 UTC, pnax commented on share/GNUmakefile
> +	@sed -i 's/^"Language: /&$(POLANG)/' $(POLANG).po
Indeed, the `-i` sed option is not defined the same way. I've provided an update with your suggestion.

2023-02-02 17:24 UTC, matsduf approved these changes
This works fine. Maybe the GNUmakefile should be extended to update more fields in the header (besides "Language"). Here are the candiate fields for update:
```
"Project-Id-Version: PACKAGE VERSION\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Content-Type: text/plain; charset=CHARSET\n"
```
The values could be same as in sv.po and fr.po, or something else that we decide and then update all PO files to match.

2023-02-08 12:47 UTC, merged

2023-02-08 13:45 UTC, pnax commented
For the automatic update of the header fields, see https://github.com/zonemaster/zonemaster-engine/pull/1191

2023-06-05 14:07 UTC, mattias-p commented
I've successfully tested this as part of release testing for 2023.1.