Add Nameserver15 implementation
zonemaster/zonemaster-engine pull request #1218
Opened 2023-05-02 15:57 UTC by tgreenx

## Purpose

This PR proposes an implementation of the newly specified [Nameserver15](https://github.com/zonemaster/zonemaster/blob/develop/docs/public/specifications/tests/Nameserver-TP/nameserver15.md) Test Case.

## Context

https://github.com/zonemaster/zonemaster/pull/1150

## Changes

`lib/Zonemaster/Engine/Test/Nameserver.pm` + `profile.json`
- Add implementation
- Add documentation

`docs/logentry_args.md`
- Update message arguments list

`t/Test-nameserver15.t` + `t/Test-nameserver15.data`
- Add unitary tests

## How to test this PR

Unit tests should pass. All message tags are covered, however note that they are not using "controlled" zones.

Also:
```
$ zonemaster-cli --show-testcase --test nameserver/nameserver15 zonemaster.net --level INFO
Seconds Level     Testcase       Message
======= ========= ============== =======
   0.00 INFO      UNSPECIFIED    Using version v4.6.2 of the Zonemaster engine.
   1.33 INFO      NAMESERVER15   The following name server(s) respond to software version query "version.bind" with string "9.18.13". Returned from name servers: "ns2.nic.fr/192.93.0.4;ns2.nic.fr/2001:660:3005:1::1:2"
   1.34 INFO      NAMESERVER15   The following name server(s) do not respond to software version queries. Returned from name servers: "nsa.dnsnode.net/194.58.192.46;nsa.dnsnode.net/2a01:3f1:46::53;nsp.dnsnode.net/194.58.198.32;nsp.dnsnode.net/2a01:3f1:3032::53;nsu.dnsnode.net/185.42.137.98;nsu.dnsnode.net/2a01:3f0:400::32"
```

2023-05-09 14:52 UTC, blacksponge approved these changes
It works as excepted from what I can see.

2023-05-09 22:05 UTC, matsduf requested changes
Some minor comments, but in general it looks fine, but I have to test too.

2023-05-09 22:05 UTC, matsduf commented on docs/logentry_args.md
> +| string         | Text                                     | The content of the RDATA of a TXT ressource record.                     |
"resource" is misspelled.

2023-05-09 22:05 UTC, matsduf commented on docs/logentry_args.md
>  [sv.po]:                                     ../share/fr.po
Could you fix the typo here (not from this PR): `../share/fr.po` -->  `../share/sv.po`

2023-05-10 09:51 UTC, blacksponge approved these changes

2023-05-10 12:58 UTC, matsduf approved these changes

2023-05-10 13:14 UTC, merged