Add CNAME followage in Recursor
zonemaster/zonemaster-engine pull request #1288
Opened 2023-09-07 16:58 UTC by tgreenx

## Purpose

This PR makes the recursive lookup functionality of Zonemaster able to follow CNAME redirections.

Attempts to follow CNAMEs will be made when all of the following are true:
- the response has RCODE "NoError"
- the answer section of the response does not contain records of the queried type, but does contain at least one CNAME record for the query name
- the answer section of the response does not contain multiple CNAME records with the same owner name
- the final target of the CNAME record(s) chain has not been followed before
- there are no records of the queried type with owner name as the final target of the CNAME record(s)

## Context

Necessary for https://github.com/zonemaster/zonemaster-engine/pull/1257 (https://github.com/zonemaster/zonemaster-engine/pull/1257#issuecomment-1710444437)

Test Zones specification: https://github.com/zonemaster/zonemaster/pull/1220

## Changes

- Update recursive lookup code (`lib/Zonemaster/Engine/Recursor.pm`)
- Add system debug message tags `CNAME_START`, `CNAME_RECORDS_DUPLICATES`, `CNAME_CHAIN_TOO_LONG`, `CNAME_LOOP_INNER`, `CNAME_LOOP_OUTER`, `CNAME_NO_MATCH`, `CNAME_RECORDS_CHAIN_BROKEN`, `CNAME_MULTIPLE_FOR_NAME` and `CNAME_RECORDS_TOO_MANY`
- Add constants `CNAME_MAX_CHAIN_LENGTH` and `CNAME_MAX_RECORDS`
- Update test cases related to CNAME (where applicable): Syntax06 and Zone07
- Add and update unitary tests
- Add and update documentation

## How to test this PR

Unit tests are updated and should pass (based on https://github.com/zonemaster/zonemaster/pull/1220).

**Manual testing:**
You can can test any zone by providing it to `Zonemaster::Engine->recurse()`, e.g. with any of the zones from https://github.com/zonemaster/zonemaster/pull/1220. See below:
```
$ perl -MZonemaster::Engine -E 'Zonemaster::Engine->add_fake_delegation( ( "." => { ns1 => [ "127.1.0.1", "fda1:b2:c3::127:1:0:1" ], ns2 => [ "127.1.0.2", "fda1:b2:c3::127:1:0:2" ] } ) ); my $p = Zonemaster::Engine->recurse("good-cname-1.cname.recursor.engine.xa"); for my $entry ( @{ Zonemaster::Engi
ne->logger->entries } ) { say "\n", $entry if index($entry->tag, "CNAME") != -1 }; say "\n", $p->string if defined $p'

;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 24524
;; flags: qr aa ; QUERY: 1, ANSWER: 2, AUTHORITY: 1, ADDITIONAL: 0
;; QUESTION SECTION:
;; good-cname-1.cname.recursor.engine.xa.       IN      A

;; ANSWER SECTION:
good-cname-1.cname.recursor.engine.xa.  3600    IN      CNAME   good-cname-1-target.cname.recursor.engine.xa.
good-cname-1-target.cname.recursor.engine.xa.   3600    IN      A       127.0.0.1

;; AUTHORITY SECTION:
cname.recursor.engine.xa.       3600    IN      NS      ns1.cname.recursor.engine.xa.

;; ADDITIONAL SECTION:

;; Query time: 0 msec
;; EDNS: version 0; flags: ; udp: 512
;; SERVER: fda1:b2:c3:0:127:30:1:31
;; WHEN: Tue Nov 28 12:30:33 2023
;; MSG SIZE  rcvd: 287
```

```
$ perl -MZonemaster::Engine -E 'Zonemaster::Engine->add_fake_delegation( ( "." => { ns1 => [ "127.1.0.1", "fda1:b2:c3::127:1:0:1" ], ns2 => [ "127.1.0.2", "fda1:b2:c3::127:1:0:2" ] } ) ); my $p = Zonemaster::Engine->recurse("mult-cname.cname.recursor.engine.xa"); for my $entry ( @{ Zonemaster::Engine
->logger->entries } ) { say "\n", $entry if index($entry->tag, "CNAME") != -1 }; say "\n", $p->string if defined $p'

SYSTEM:UNSPECIFIED:CNAME_MULTIPLE_FOR_NAME name=mult-cname.cname.recursor.engine.xa
```

```
$ perl -MZonemaster::Engine -E 'Zonemaster::Engine->add_fake_delegation( ( "." => { ns1 => [ "127.1.0.1", "fda1:b2:c3::127:1:0:1" ], ns2 => [ "127.1.0.2", "fda1:b2:c3::127:1:0:2" ] } ) ); my $p = Zonemaster::Engine->recurse("looped-cname-out-of-zone.sub2.cname.recursor.engine.xa"); for my $entry ( @{ Zonemaster::Engine->logger->entries } ) { say "\n", $entry if index($entry->tag, "CNAME") != -1 }; say "\n", $p->string if defined $p'

SYSTEM:UNSPECIFIED:CNAME_LOOP_OUTER cnames=looped-cname-out-of-zone.sub2.cname.recursor.engine.xa;looped-cname-out-of-zone.sub3.cname.recursor.engine.xa; name=looped-cname-out-of-zone.sub2.cname.recursor.engine.xa; target="looped-cname-out-of-zone.sub3.cname.recursor.engine.xa"
```

2023-10-31 16:02 UTC, matsduf commented on share/profile.json
> +            "CNAME_MULTIPLE_FOR_NAME" : "DEBUG",
Can these three be defined or described in Recursor.pm?

2023-11-02 16:57 UTC, matsduf commented
What is the purpose of mixing case in
```
illegal1                IN  CNAME  target0
ILLEGAL1                IN  CNAME  target1
```
and others?

2023-11-02 21:27 UTC, matsduf commented
> Generally it is to test case-insensitivity of the implementation. But here it is also about testing that several CNAME records with the same owner name (with different cases) lead to an error, i.e. that the implementation outputs `CNAME_MULTIPLE_FOR_NAME` (this [part of the code](https://github.com/zonemaster/zonemaster-engine/pull/1288/files#diff-f67b3e26b5365bb9e63dc0831b878f5e86f0d66f5b1dbc50d220c586b1938bc3R198-R202)).

Then, shouldn't there be a test where the two CNAME records have identical owner names in a case sensitive comparison. too?

2023-11-03 17:05 UTC, matsduf commented on share/profile.json
> +            "CNAME_MULTIPLE_FOR_NAME" : "DEBUG",
I do not think it is necessary to have a message ID on those, which would put a burden on the translators. Definition or description in POD would be fine.

2023-11-05 23:09 UTC, matsduf commented
@tgreenx, How should the unit tests react on NODATA and NXDOMAIN responses, respectively?

NODATA:

```
; <<>> DiG 9.18.18-0ubuntu0.22.04.1-Ubuntu <<>> @127.31.1.31 alias-nodata.recursor.core.xa A
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 38985
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 1, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
; COOKIE: a15d870f95dcc703 (echoed)
;; QUESTION SECTION:
;alias-nodata.recursor.core.xa.	IN	A

;; ANSWER SECTION:
alias-nodata.recursor.core.xa. 3600 IN	CNAME	target-nodata.recursor.core.xa.

;; AUTHORITY SECTION:
recursor.core.xa.	3600	IN	NS	ns1.recursor.core.xa.

;; Query time: 0 msec
;; SERVER: 127.31.1.31#53(127.31.1.31) (UDP)
;; WHEN: Sun Nov 05 23:02:53 UTC 2023
;; MSG SIZE  rcvd: 193
```

NXDOMAIN:
```
; <<>> DiG 9.18.18-0ubuntu0.22.04.1-Ubuntu <<>> @127.31.1.31 alias-nxdomain.recursor.core.xa A
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 11309
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 1, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
; COOKIE: c82ff6fab047c6dc (echoed)
;; QUESTION SECTION:
;alias-nxdomain.recursor.core.xa. IN	A

;; ANSWER SECTION:
alias-nxdomain.recursor.core.xa. 3600 IN CNAME	target-nxdomain.recursor.core.xa.

;; AUTHORITY SECTION:
recursor.core.xa.	3600	IN	NS	ns1.recursor.core.xa.

;; Query time: 0 msec
;; SERVER: 127.31.1.31#53(127.31.1.31) (UDP)
;; WHEN: Sun Nov 05 23:02:45 UTC 2023
;; MSG SIZE  rcvd: 199
```

And how will the code handle broken chain (and here with a duplicate CNAME record)?

broken-chain.recursor.core.xa. --> broken-chain2.recursor.core.xa. --> broken-chain3.recursor.core.xa. --> NULL

NULL --> broken-chain-target.recursor.core.xa. 100 IN A	127.0.0.1

```
; <<>> DiG 9.18.18-0ubuntu0.22.04.1-Ubuntu <<>> @127.31.1.31 broken-chain.recursor.core.xa A
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 54152
;; flags: qr aa rd; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
; COOKIE: 83ca9efec06ee54d (echoed)
;; QUESTION SECTION:
;broken-chain.recursor.core.xa.	IN	A

;; ANSWER SECTION:
broken-chain.recursor.core.xa. 100 IN	CNAME	broken-chain2.recursor.core.xa.
broken-chain2.recursor.core.xa.	3600 IN	CNAME	broken-chain3.recursor.core.xa.
broken-chain2.recursor.core.xa.	100 IN	CNAME	broken-chain3.recursor.core.xa.
broken-chain-target.recursor.core.xa. 100 IN A	127.0.0.1

;; Query time: 0 msec
;; SERVER: 127.31.1.31#53(127.31.1.31) (UDP)
;; WHEN: Sun Nov 05 23:02:21 UTC 2023
;; MSG SIZE  rcvd: 343
```

2023-11-06 16:14 UTC, matsduf commented on t/recursor-A.t
> +is( name( ($p->answer)[0]->owner ), 'target.good-cname.recursor.xa', 'RR name ok' );
So if there are three A records in `target.good-cname.recursor.xa` then that would match `is( scalar( $p->answer ), 3, 'three answer records' );`

2023-11-15 09:41 UTC, matsduf commented on t/recursor-A.t
> +is( name( ($p->answer)[0]->owner ), 'target.good-cname.recursor.xa', 'RR name ok' );
I get two records in the response and the unit test fails:

```
$ perl -MZonemaster::Engine -E 'Zonemaster::Engine::Recursor->remove_fake_addresses("."); Zonemaster::Engine->add_fake_delegation( ( "." => { ns1 => [ "127.1.0.1" ] } ) ); my $p = Zonemaster::Engine->recurse("good-cname-1.cname.recursor.engine.xa", "A"); for my $entry ( @{ Zonemaster::Engine->logger->entries } ) { say "\n", $entry if index($entry->tag, "CNAME") != -1 }; say $p->string;'
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 45265
;; flags: qr aa ; QUERY: 1, ANSWER: 2, AUTHORITY: 1, ADDITIONAL: 0 
;; QUESTION SECTION:
;; good-cname-1.cname.recursor.engine.xa.	IN	A

;; ANSWER SECTION:
good-cname-1.cname.recursor.engine.xa.	3600	IN	CNAME	good-cname-1-target.cname.recursor.engine.xa.
good-cname-1-target.cname.recursor.engine.xa.	3600	IN	A	127.0.0.1

;; AUTHORITY SECTION:
cname.recursor.engine.xa.	3600	IN	NS	ns1.cname.recursor.engine.xa.

;; ADDITIONAL SECTION:

;; Query time: 0 msec
;; EDNS: version 0; flags: ; udp: 512
;; SERVER: fda1:b2:c3:0:127:30:1:31
;; WHEN: Wed Nov 15 09:40:41 2023
;; MSG SIZE  rcvd: 287
```

2023-11-15 18:44 UTC, matsduf commented
@tgreenx, see https://github.com/zonemaster/zonemaster/pull/1220

2023-11-29 13:42 UTC, matsduf commented
There are still two unit tests that fail (my update in the `t` file to print out the scenario name):
```
ok 56 - undefined as expected (LOOPED-CNAME-IN-ZONE-1)
not ok 57 - should emit CNAME_LOOP_INNER (LOOPED-CNAME-IN-ZONE-1)

#   Failed test 'should emit CNAME_LOOP_INNER (LOOPED-CNAME-IN-ZONE-1)'
#   at t/recursor-A.t line 121.
ok 58 - undefined as expected (LOOPED-CNAME-IN-ZONE-2)
not ok 59 - should emit CNAME_LOOP_INNER (LOOPED-CNAME-IN-ZONE-2)

#   Failed test 'should emit CNAME_LOOP_INNER (LOOPED-CNAME-IN-ZONE-2)'
#   at t/recursor-A.t line 127.
```

What is wrong with `LOOPED-CNAME-IN-ZONE-2` with the following response?
```
; <<>> DiG 9.18.18-0ubuntu0.22.04.1-Ubuntu <<>> @127.30.1.31 looped-cname-in-zone-2.cname.recursor.engine.xa
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 25162
;; flags: qr aa rd; QUERY: 1, ANSWER: 3, AUTHORITY: 1, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
; COOKIE: f6c515b68ac2fe36 (echoed)
;; QUESTION SECTION:
;looped-cname-in-zone-2.cname.recursor.engine.xa. IN A

;; ANSWER SECTION:
looped-cname-in-zone-2.cname.recursor.engine.xa. 3600 IN CNAME looped-cname-in-zone-2-a.cname.recursor.engine.xa.
looped-cname-in-zone-2-a.cname.recursor.engine.xa. 3600	IN CNAME looped-cname-in-zone-2-b.cname.recursor.engine.xa.
looped-cname-in-zone-2-b.cname.recursor.engine.xa. 3600	IN CNAME looped-cname-in-zone-2-a.cname.recursor.engine.xa.

;; AUTHORITY SECTION:
cname.recursor.engine.xa. 3600	IN	NS	ns1.cname.recursor.engine.xa.

;; Query time: 0 msec
;; SERVER: 127.30.1.31#53(127.30.1.31) (UDP)
;; WHEN: Wed Nov 29 13:41:55 UTC 2023
;; MSG SIZE  rcvd: 488
```

2023-11-29 16:21 UTC, mattias-p commented on lib/Zonemaster/Engine/Recursor.pm
> +                    return ( undef, $state ) if $state->{count} > 100; # Loop protection
1. Shouldn't this check be postponed until just before we actually recurse?
2. The max count is 100 here but 20 in another place. Shouldn't they be the same? Maybe define a constant for this number and refer to it in both places?

2023-11-29 16:31 UTC, mattias-p commented on t/recursor-A.t
> +# GOOD-CNAME-1
I suggest using [subtest](https://perldoc.perl.org/Test::More#subtest) here instead of simple comments. That way we'll get better diagnostics when running `prove -Ilib -v t/recursor-A.t`.

2023-11-29 20:46 UTC, mattias-p commented on lib/Zonemaster/Engine/Recursor.pm
> +            if ( not $p->has_rrs_of_type_for_name( $type, $name ) and $p->has_rrs_of_type_for_name( 'CNAME', $name ) ) {
Sure, I agree with all that. However my comment was not about how servers are supposed to behave but rather how Zonemaster should behave when a server misbehaves. That said I had another look at this and realized that I read the code too quickly the first time. It does in fact abort, which is reasonable.

2023-11-30 12:34 UTC, matsduf commented
How will the code react if the answer section has a CNAME pointing at a target name, but the `A` record has another owner name?

```
;; ANSWER SECTION:
cname-one.cname.recursor.engine.xa.   3600 IN CNAME cname-two.cname.recursor.engine.xa.
cname-three.cname.recursor.engine.xa. 3600 IN A 127.0.0.1
```

How will the code react if the answer section has a broken CNAME chain, i.e. a CNAME is missing in the chain?

```
;; ANSWER SECTION:
cname-one.cname.recursor.engine.xa.   3600 IN CNAME cname-two.cname.recursor.engine.xa.
cname-three.cname.recursor.engine.xa. 3600 IN CNAME cname-four.cname.recursor.engine.xa.
cname-four.cname.recursor.engine.xa.   3600 IN A 127.0.0.1
```

I could easily try to create these and other scenarios.

2023-11-30 12:46 UTC, matsduf commented on lib/Zonemaster/Engine/Recursor.pm
> +    return ( undef, $state ) if $state->{tcount} > 100; # Safe-guard against anormaly long CNAME chains; no need to recurse
Instead of just breaking, why not outputting e.g. CNAME_TOO_LONG_CHAIN (ERROR) at 10 (changed my mind from 12 to 10).

Maybe even a outputting e.g. CNAME_LONG_CHAIN (WARNING) at 5, but not breaking.

2023-11-30 13:32 UTC, pnax commented on lib/Zonemaster/Engine/Recursor.pm
> +    return ( undef, $state ) if $state->{tcount} > 100; # Safe-guard against anormaly long CNAME chains; no need to recurse
Suggestion: make this chain length configurable with an entry in the profile (e.g. `resolver.defaults.cname_chain_length`). This could be done at a later stage if this adds too much work to this PR.

2023-11-30 15:15 UTC, matsduf commented on t/recursor-A.t
> +    ok( $res{CNAME_LOOP_INNER}, q{should emit CNAME_LOOP_INNER} );
Would it be helpful if the scenario name is included in the message? E.g.
```
    is( $p, undef, "undefined as expected (LOOPED-CNAME-IN-ZONE-2)");
```
```
    ok( $res{CNAME_LOOP_INNER}, q{should emit CNAME_LOOP_INNER (LOOPED-CNAME-IN-ZONE-2)} );
```

2023-11-30 15:35 UTC, matsduf commented on lib/Zonemaster/Engine/Recursor.pm
> +    return ( undef, $state ) if $state->{tcount} > 100; # Safe-guard against anormaly long CNAME chains; no need to recurse
> It is not about the length of a CNAME chain (i.e. number of CNAME resource records) in a single response. That could be another safe-guard counter though. Are we on the same page?

Yes, sure. Doing another lookup should only be done if the target is outside the zone or zones in which the CNAME record or records reside.

2023-11-30 15:36 UTC, matsduf commented on lib/Zonemaster/Engine/Recursor.pm
> +    return ( undef, $state ) if $state->{tcount} > 100; # Safe-guard against anormaly long CNAME chains; no need to recurse
> Suggestion: make this chain length configurable with an entry in the profile (e.g. `resolver.defaults.cname_chain_length`). This could be done at a later stage if this adds too much work to this PR.

That could always be nice, but it makes it more complicated to create unit tests to catch the function.

2023-11-30 15:55 UTC, mattias-p commented on lib/Zonemaster/Engine/Recursor.pm
> +    $state->{tcount} += 1;
I just realized we don't have any documentation of the fields of the state hash. I think we should, though. I tried to think about the right place for such documentation and I believe it's the pod documentation for _recurse(). Would you consider adding descriptions there for the new state fields added in this PR?

2023-11-30 16:18 UTC, matsduf commented
@mattias-p wrote in https://github.com/zonemaster/zonemaster-engine/pull/1288#discussion_r1409339655:

> I believe we need to protect ourselves from an infinite loop here. E.g. when getting a response like this:
> 
> ```
> ;; QUESTION SECTION:
> ;a.example. IN A
> ;; ANSWER SECTION:
> a.example. IN CNAME b.example.
> b.example. IN CNAME a.example.
> ```

Due to a bug (I think) in CoreDNS this cannot be produced by CoreDNS unless the following is acceptable, but I do not think the code likes it.
```
;; QUESTION SECTION:
;a.example. IN A
;; ANSWER SECTION:
a.example. IN CNAME b.example.
b.example. IN CNAME a.example.
a.example. IN CNAME b.example.
b.example. IN CNAME a.example.
a.example. IN CNAME b.example.
b.example. IN CNAME a.example.
a.example. IN CNAME b.example.
b.example. IN CNAME a.example.
a.example. IN CNAME b.example.
b.example. IN CNAME a.example.
```

2023-11-30 16:48 UTC, matsduf commented
> > I could easily try to create these and other scenarios.
> 
> Yes please do.

I have added three more scenarios. I guess you will updated the unit tests.

2023-12-01 12:21 UTC, matsduf commented
Three new scenarios, LOOPED-CNAME-IN-ZONE-3, WRONG-CNAME-OWNER-NAME and EXTRA-CNAME-IN-ANSWER, have been added to the test zone (https://github.com/zonemaster/zonemaster/pull/1220).

2023-12-07 10:38 UTC, matsduf commented on lib/Zonemaster/Engine/Recursor.pm
> +        $cnames{$rr_owner} = $rr_target;
Maybe normalize in terms of upper and lower case?

2023-12-07 13:25 UTC, matsduf commented on t/recursor-A.t
> +# subtest 'TOO-LONG-CNAME-CHAIN' => sub {
I suggest that the limit is set to >9 instead. 10 is too many. In that way we have test data.

2023-12-07 13:26 UTC, matsduf commented on t/recursor-A.t
> +# subtest 'LOOPED-CNAME-IN-ZONE-1' => sub {
Would it be wrong to let the code reduce repeated records into one?

2023-12-07 17:09 UTC, matsduf commented on lib/Zonemaster/Engine/Recursor.pm
> +        Zonemaster::Engine->logger->add( CNAME_FOLLOWED_OOB => { name => $name, target => $target } );
How should OOB be interpreted? Are the new tags defined somewhere?

2023-12-11 13:34 UTC, matsduf commented on lib/Zonemaster/Engine/Recursor.pm
> +        Zonemaster::Engine->logger->add( CNAME_FOLLOWED_OOB => { name => $name, target => $target } );
I feel it is wrong to use the terms "in-bailiwick" and "out-of-bailiwick" here. In a DNS context they refer to namn server names in delegation. See the term "Bailiwick" in https://datatracker.ietf.org/doc/html/rfc8499, section 7 on page 25.

Also see my comment on Recursor.pm.

2023-12-11 13:42 UTC, matsduf requested changes

2023-12-11 13:42 UTC, matsduf commented on lib/Zonemaster/Engine/Recursor.pm
> +CNAME_NO_MATCH, CNAME_RECORDS_CHAIN_BROKEN, CNAME_RECORDS_MULTIPLE_FOR_NAME, CNAME_RECORDS_TOO_MANY.
I suggest CNAME_FOLLOWED_IZ ("in zone") and CNAME_FOLLOWED_OOZ ("out-of-zone"), respectively, instead of  CNAME_FOLLOWED_IB and CNAME_FOLLOWED_OOB. That would capture the meaning, wouldn't it?

Could you make a list of the tags with one tag per "=item" and include a short description of what the tag stands for?

2024-04-10 07:53 UTC, matsduf commented
@tgreenx, could we complete this together with [Test zones for the CNAME function in Recursor.pm in Engine]?

[Test zones for the CNAME function in Recursor.pm in Engine]: https://github.com/zonemaster/zonemaster/pull/1220

2024-05-21 12:59 UTC, marc-vanderwal commented on lib/Zonemaster/Engine/Recursor.pm
> +        my $rr_hash = $rr->class . '/' . $rr->ttl . '/CNAME/' . $rr->owner . '/' . $rr->cname;
Suppose a response contains two identical CNAME records that only differ by TTL. Should we consider them as duplicates? I’d say yes.

And how about two CNAME records that only differ by case in the owner name, CNAME name, or both? I think they should be considered duplicate too.

2024-05-21 12:59 UTC, marc-vanderwal commented on lib/Zonemaster/Engine/Recursor.pm
> +        if ( lc( $rr_owner ) eq lc( $rr_target ) or exists $seen_targets{lc( $rr_target )} or grep( /^$rr_target$/, keys %forbidden_targets ) ) {
The `grep` can have odd side-effects if `$rr_target` contains names with special characters in them. It was also missing a conversion to lowercase. It’s better to do:
```perl
grep { lc( $_ ) eq $rr_target } ( keys %forbidden_targets )
```

2024-05-21 12:59 UTC, marc-vanderwal commented on lib/Zonemaster/Engine/Recursor.pm
> +        $cnames{$rr_owner} = $rr_target;
We should do case-insensitive comparisons when checking whether we’ve already queried the name before (and thus, detect loops). But we should also be case-preserving: if `foo.example` is an alias to `BAR.example`, we should query `BAR.example`, not `bar.example`, even though both of these QNAMEs should in theory get us the same RRset.

2024-05-22 09:05 UTC, marc-vanderwal commented on lib/Zonemaster/Engine/Recursor.pm
> +                            { ns => [ root_servers() ], count => 0, common => 0, seen => { $cname => 1 }, glue => {} });
Given the date of that comment: yes, apparently I forgot I already started a review eons ago.

2024-05-22 11:44 UTC, matsduf commented on lib/Zonemaster/Engine/Recursor.pm
> +        my $rr_hash = $rr->class . '/' . $rr->ttl . '/CNAME/' . $rr->owner . '/' . $rr->cname;
I agree.

2024-05-22 11:46 UTC, matsduf commented
Is case preservation really needed here? I cannot see that is wrong to query for `bar.xa` even it RDATA of the CNAME record was `BAR.XA`.

2024-05-24 09:11 UTC, marc-vanderwal commented
> Is case preservation really needed here? I cannot see that is wrong to query for `bar.xa` even it RDATA of the CNAME record was `BAR.XA`.

RFC 1034 does, in fact, state that:

> When you receive a domain name or label, you should preserve its case.

My understanding is that when you “receive” a CNAME, if the resolver decides to follow it, the follow-up query’s QNAME should retain the case exactly as it was received in the previous response.

So in a nutshell: it’s better to preserve case here. If not, I feel like we are adding an assumption to `Recursor` that the name server will give identical RRsets when queried for `BAR.XA` and `bar.xa`. For the initial use case of this code, it’s probably overkill. But if we decide to use the same Recursor to query untrusted nameservers, than anything goes.

2024-06-12 07:25 UTC, marc-vanderwal approved these changes

2024-07-04 15:03 UTC, matsduf approved these changes

2024-07-04 15:04 UTC, matsduf commented
I think this can be merged now.

2024-07-16 09:42 UTC, merged

2024-12-03 10:21 UTC, marc-vanderwal commented
Release testing for 2024.2: no issues found.