Update Delegation01
zonemaster/zonemaster-engine pull request #1290
Opened 2023-09-12 12:55 UTC by tgreenx

## Purpose

This PR updates Delegation01 by updating some message tags/ids to report name server names and addresses together instead of separately.

## Context

Fixes https://github.com/zonemaster/zonemaster/issues/1203

## Changes

- `ENOUGH_IPV{4/6}_NS_CHILD`
- `NOT_ENOUGH_IPV{4/6}_NS_CHILD`
- `ENOUGH_IPV{4/6}_NS_DEL`
- `NOT_ENOUGH_IPV{4/6}_NS_DEL`
- `ENOUGH_NS_{CHILD/DEL}`
- `NOT_ENOUGH_NS_{CHILD/DEL}`

## How to test this PR

Unit tests should pass.

Also:
```
$ zonemaster-cli --show-testcase --test delegation/delegation01 --level info ripe.net
Seconds Level    Testcase       Message
======= ======== ============== =======
   0.00 INFO     UNSPECIFIED    Using version v4.7.2 of the Zonemaster engine.
   0.73 INFO     DELEGATION01   Parent lists enough (5) nameservers. Lower limit set to 2. Name servers: manus.authdns.ripe.net;ns3.afrinic.net;ns3.lacnic.net;ns4.apnic.net;rirns.arin.net
   2.88 INFO     DELEGATION01   Child lists enough (5) nameservers. Lower limit set to 2. Name servers: manus.authdns.ripe.net;ns3.afrinic.net;ns3.lacnic.net;ns4.apnic.net;rirns.arin.net
   2.88 INFO     DELEGATION01   Child lists enough (5) nameservers that resolve to IPv4 addresses. Lower limit set to 2. Name servers: manus.authdns.ripe.net/193.0.9.7;ns3.afrinic.net/204.61.216.100;ns3.lacnic.net/200.3.13.14;ns4.apnic.net/202.12.31.53;rirns.arin.net/199.253.249.53
   2.88 INFO     DELEGATION01   Child lists enough (5) nameservers that resolve to IPv6 addresses. Lower limit set to 2. Name servers: manus.authdns.ripe.net/2001:67c:e0::7;ns3.afrinic.net/2001:500:14:6100:ad::1;ns3.lacnic.net/2001:13c7:7002:3000::14;ns4.apnic.net/2001:dd8:12::53;rirns.arin.net/2620:38:2000::53
   2.92 INFO     DELEGATION01   Delegation lists enough (5) nameservers that resolve to IPv4 addresses. Lower limit set to 2. Name servers: manus.authdns.ripe.net/193.0.9.7;ns3.afrinic.net/204.61.216.100;ns3.lacnic.net/200.3.13.14;ns4.apnic.net/202.12.31.53;rirns.arin.net/199.253.249.53
   2.92 INFO     DELEGATION01   Delegation lists enough (5) nameservers that resolve to IPv6 addresses. Lower limit set to 2. Name servers: manus.authdns.ripe.net/2001:67c:e0::7;ns3.afrinic.net/2001:500:14:6100:ad::1;ns3.lacnic.net/2001:13c7:7002:3000::14;ns4.apnic.net/2001:dd8:12::53;rirns.arin.net/2620:38:2000::53
```
And :
```
$ zonemaster-cli --show-testcase --test delegation/delegation01 --level info --ns ns1.m.delegation01.exempelvis.se/46.21.97.97 --ns ns1.m.delegation01.exempelvis.se/194.18.226.122 m.delegation01.exempelvis.se
Seconds Level    Testcase       Message
======= ======== ============== =======
   0.00 INFO     UNSPECIFIED    Using version v4.7.2 of the Zonemaster engine.
   0.09 ERROR    DELEGATION01   Parent does not list enough (1) nameservers. Lower limit set to 2. Name servers: ns1.m.delegation01.exempelvis.se
   0.33 ERROR    DELEGATION01   Child does not list enough (1) nameservers. Lower limit set to 2. Name servers: ns1.m.delegation01.exempelvis.se
   0.34 ERROR    DELEGATION01   Child does not list enough (1) nameservers that resolve to IPv4 addresses. Lower limit set to 2. Name servers: ns1.m.delegation01.exempelvis.se/194.18.226.122;ns1.m.delegation01.exempelvis.se/46.21.97.97
   0.34 NOTICE   DELEGATION01   Child lists no nameserver that resolves to an IPv6 address. If any were present, the minimum allowed would be 2.
   0.34 ERROR    DELEGATION01   Delegation does not list enough (1) nameservers that resolve to IPv4 addresses. Lower limit set to 2. Name servers: ns1.m.delegation01.exempelvis.se/194.18.226.122;ns1.m.delegation01.exempelvis.se/46.21.97.97
   0.34 NOTICE   DELEGATION01   Delegation lists no nameserver that resolves to an IPv6 address. If any were present, the minimum allowed would be 2.
```

Note that one side effect is that when there is a single name server with several IP addresses, the message might not be obvious at first (counts one name server name, but shows two):
>    2.14 ERROR    DELEGATION01   Child does not list enough (1) nameservers (ns1.m.delegation01.exempelvis.se/194.18.226.122;ns1.m.delegation01.exempelvis.se/46.21.97.97) that resolve to IPv4 addresses. Lower limit set to 2.

2023-09-18 13:27 UTC, marc-vanderwal commented
I think it would be nice if names resolving to multiple IP addresses could be represented in a less verbose way, and with the IP addresses sorted according to their 32- or 128-bit integer values. For example, instead of having:
```
ns1.m.delegation01.exempelvis.se/194.18.226.122;ns1.m.delegation01.exempelvis.se/46.21.97.97
```
use this representation:
```
ns1.m.delegation01.exempelvis.se/46.21.97.97,194.18.226.122
```

Otherwise, name server names and IP tuples would be excessively hard to read. Especially when IPv6 is involved.

2023-09-18 13:50 UTC, matsduf commented
> I think it would be nice if names resolving to multiple IP addresses could be represented in a less verbose way, and with the IP addresses sorted according to their 32- or 128-bit integer values. For example, instead of having:

I think it is uncommon to have multiple IP addresses for the same name server name. The example that you give is a test zone.

If this is to be changed, then it should be specified first so that we do not get an ad-hoc format for one test case.

I agree that it can be hard to read when there is a long list of name servers. For GUI I have created an issue with a suggestion to make it easier to digest: https://github.com/zonemaster/zonemaster-gui/issues/315

2023-09-18 13:54 UTC, marc-vanderwal submitted a review, later dismissed

2023-09-18 14:04 UTC, matsduf commented on lib/Zonemaster/Engine/Test/Delegation.pm
> +          . "that resolve to IPv4 addresses. Lower limit set to {minimum}.",
A long list is better to have at the end of the msgid. I suggest:
```
          "Child lists enough ({count}) nameservers that resolve to IPv4 "
          . "addresses. Lower limit set to {minimum}. The name servers are {ns_list}",
```

2023-09-18 14:06 UTC, matsduf requested changes

2023-09-18 14:06 UTC, matsduf commented on lib/Zonemaster/Engine/Test/Delegation.pm
> +          . "that resolve to IPv4 addresses. Lower limit set to {minimum}.",
A long list is better to have at the end of the msgid. I suggest:
```
          "Child lists enough ({count}) nameservers that resolve to IPv4 "
          . "addresses. Lower limit set to {minimum}. The name servers are {ns_list}",
```

2023-09-29 07:17 UTC, matsduf commented on lib/Zonemaster/Engine/Test/Delegation.pm
> +          "Parent lists enough ({count}) nameservers. Lower limit set to {minimum}. Name servers: {nsname_list}", @_;
To be consistent, "parent" should be updated to "delegation".

2023-09-29 07:17 UTC, matsduf commented on lib/Zonemaster/Engine/Test/Delegation.pm
> +          "Parent does not list enough ({count}) nameservers. Lower limit set to {minimum}. Name servers: {nsname_list}", @_;
To be consistent, "parent" should be updated to "delegation".

2023-11-27 10:54 UTC, matsduf approved these changes

2023-11-28 14:47 UTC, merged

2024-01-10 14:52 UTC, pnax commented
### v2023.2 release testing

Tested using the "How to test section" and works as expected.