Update test module interface documentation
zonemaster/zonemaster-engine pull request #1325
Opened 2024-03-14 13:14 UTC by mattias-p

## Purpose

I started out making this update because I felt we need a good and up to date definition of the test module interface.

## Context

Having a clear definition of the test module interface will be useful when we design the custom test module feature and in turn when people make use of it.

## Changes

The justification for this PR is the added and updated details. While this PR contains some amount of new details most of the diff comes from formatting and editing and moving things around. Some older language and terminology is also updated to be more precise and contemporary. I may have got a little carried away but I believe the end result is good.

## How to test this PR

N/A

2024-04-30 09:30 UTC, mattias-p commented
@matsduf @marc-vanderwal @tgreenx Please review. I've rebased this on top of latest develop.

2024-04-30 09:37 UTC, tgreenx submitted a review, later dismissed

2024-04-30 11:55 UTC, matsduf requested changes
Related issues are referred to as "localization", "translation" and "internationalization". Unnecessary confusion. I suggest that translation is used in all places.

2024-04-30 11:55 UTC, matsduf commented on lib/Zonemaster/Engine/Localization.pod
> +=head1 FOR TRANSLATORS
The file name is "Localization" but it is only about translation.

2024-04-30 11:55 UTC, matsduf commented on lib/Zonemaster/Engine/TestModuleInterface.pod
> +=head2 Internationalization
It is not about internationalization. It is related to translation, but mostly about the mechanism where a tag is replaced by human language, humanization?

2024-04-30 11:55 UTC, matsduf commented on lib/Zonemaster/Engine/TestModuleInterface.pod
> +The zone object it's given has a parent.
Not necessarily. The root zone has no parent. And a undelegated zone can be tested even if it is not possible to determine its parent-to-be.

2024-04-30 11:55 UTC, matsduf commented on lib/Zonemaster/Engine/TestModuleInterface.pod
> +The zone object it's given has glue records.
Not necessarily. But then testing will fail at Basic02.

2024-05-06 13:13 UTC, mattias-p commented
@matsduf

Regarding "internationalization" and "localization", I didn't make this up. It's actually well established terminology in the industry. See https://en.wikipedia.org/wiki/Internationalization_and_localization.

Regarding the "Make few assumptions" section, I didn't make this up either. It is what our current documentation says. I simply moved it to a better place. It's good that you spotted these flaws in our documentation but I feel they're out of scope for this PR.

2024-05-06 15:18 UTC, matsduf commented
Even if "internationalization" and "localization" are established terms the documentation could be less confusing if it concretely explains what it is all about.

2024-05-07 06:11 UTC, mattias-p commented
@matsduf I believe the documentation is quite concrete already. It explains what translators and developers need to do and what they need to think about, and I believe we have a decent linking structure that directs people to the right places. I'll add a link to the Wikipedia page. Would that be enough or do you have anything else in mind?

2024-05-13 06:54 UTC, marc-vanderwal commented on lib/Zonemaster/Engine/TestModuleInterface.pod
> +=head2 Internationalization
“Internationalization” is the industry-standard term for the process of modifying software so as to make it adaptable to different languages and customs (e.g. right-to-left scripts, formatting of numbers, etc.). The use of message tags instead of hard-coded messages in English is the way Zonemaster implements internationalization.

2025-10-20 14:49 UTC, matsduf commented
@mattias-p, please look at again as we agreed on the meeting 2025-10-15.

2026-06-09 13:20 UTC, matsduf commented
@mattias-p, what is the status of this PR?

2026-06-11 12:25 UTC, closed without merging