Remove planned deprecated 'resolver.source' profile property
zonemaster/zonemaster-engine pull request #1343
Opened 2024-05-07 18:17 UTC by tgreenx

## Purpose

This PR removes the planned deprecated `resolver.source` profile property. It also adds a proper IP validation module (and functions) in `Zonemaster::Engine::Validation`.

Other related changes to the `resolver.source{4,6}` profile properties and `Zonemaster::Engine::Nameserver source_address{4,6}` attributes are made. See the Changes section.

## Context

Fixes #1360 
Also fixes Perl warnings from #1342 

## Changes

This PR removes the `source_address{4,6}` and `source_address` attributes of `Zonemaster::Engine::Nameserver` objects.

Other related changes:
- Changes `resolver.source_address{4,6}` profile properties to not accept illegal values.
- Removes now unused constant `$RESOLVER_SOURCE_OS_DEFAULT`
- Removes now unused function `Zonemaster::Engine::Profile::check_validity()`
- ~~Rename `Zonemaster::Engine::Nameserver::source_address()` to `Zonemaster::Engine::Nameserver::_build_source_address()`~~
- Add IP validation module and functions `Zonemaster::Engine::Validation::validate_ipv{4,6}()`
- Refactoring
- Add and updates documentation
- Add and updates unit tests

## How to test this PR

Unit tests are updated and should pass.

2024-05-16 08:12 UTC, marc-vanderwal approved these changes

2024-06-04 09:25 UTC, mattias-p submitted a review, later dismissed
Looks great!

Once this is merged I'll rebase #1356 on top of it.

2024-06-04 10:03 UTC, matsduf requested changes

2024-06-04 10:03 UTC, matsduf commented on lib/Zonemaster/Engine/Profile.pm
> +                die "Property resolver.source4 must be a valid IPv4 address";
Both accept 10.0.1 as an IPv4 address. Will that work?

2024-06-05 05:41 UTC, marc-vanderwal commented on lib/Zonemaster/Engine/Profile.pm
> +                die "Property resolver.source4 must be a valid IPv4 address";
There are alternative notations for IPv4 addresses that allow bytes to be left out, so 10.0.1 should be valid (try that as an argument to a `ping` command on Linux or FreeBSD to see what happens). But it should be converted to 10.0.0.1, not 10.0.1.0.

I’ve also seen regular expressions attempting to validate IPv4 and IPv6 addresses in the codebase, with varying results, so there is an opportunity for refactoring to seize. I suggest, however, that this be done in another PR.

2024-06-05 16:54 UTC, mattias-p reviewed
It seems I went too fast reviewing this the first time. When I had a look at it again I realized there is a problem with how the resolver.source4 and resolver.source6 properties are defined.

2024-06-10 17:32 UTC, matsduf submitted a review, later dismissed

2024-06-11 09:06 UTC, mattias-p commented on lib/Zonemaster/Engine/Constants.pm
> +Readonly our $IPV6_RE => qr/^[0-9a-f:]*:[0-9a-f:]+(:[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3})?$/i;
The Zonemaster::Engine::Constants is a "module holding constants used in Test modules". Since we don't want anyone to use these regexes direcly, except the IP validation function(s), it's probably better to define them in Zonemaster::Engine::Util and not export them.

2024-06-11 09:06 UTC, mattias-p commented on lib/Zonemaster/Engine/Profile.pm
> +            unless ( validate_ip( $_[0], 4 ) ) {
We need to accept the empty string here as well.

2024-06-11 13:32 UTC, mattias-p reviewed
I had another look at this PR and started questioning the use of an accessor for the source address. The following review comments are this topic.

2024-06-11 13:32 UTC, mattias-p commented on lib/Zonemaster/Engine/Nameserver.pm
> -    $lazy_attrs{source_address6} = delete $attrs->{source_address6} if exists $attrs->{source_address6};
When cleaning up the source_address accessor the `$lazy_attrs{source_address}` should also be cleaned up.

2024-06-11 13:32 UTC, mattias-p commented on lib/Zonemaster/Engine/Nameserver.pm
> -    $obj->{_source_address6} = $lazy_attrs{source_address6} if exists $lazy_attrs{source_address6};
When cleaning up the source_address accessor the `$obj->{_source_address}` should also be cleaned up.

2024-06-11 13:32 UTC, mattias-p commented on lib/Zonemaster/Engine/Nameserver.pm
> +        $self->{_source_address} = Zonemaster::Engine::Profile->effective->get( "resolver.source$ip_version" );
Since the effective profile may change from test run to test run we shouldn't cache the calculated source address.

2024-06-11 13:32 UTC, mattias-p commented on lib/Zonemaster/Engine/Nameserver.pm
>      my ( $self, $ip_version ) = @_;
* Since this method isn't used to initialize the source_address accessor, we probably shouldn't call it _build_source_address. I think keeping `source_address` as the name would be more appropriate.
* It doesn't make any sense to return a source address that has a different IP version than $self->address, so instead of taking `$ip_version` as an argument, it's better to just call `Net::IP::XS::ip_get_version( $self->address->ip )` inside this function.

2024-06-12 07:19 UTC, marc-vanderwal submitted a review, later dismissed

2024-06-12 09:10 UTC, marc-vanderwal approved these changes

2024-06-12 09:45 UTC, marc-vanderwal submitted a review, later dismissed

2024-06-12 13:45 UTC, mattias-p reviewed
I reviewing the test code I found one place where relevant tests are removed and a couple of places of missing tests that we should add. I feel bad about asking you to fix stuff in this PR that you didn't introduce. If you don't feel like fixing those, just say so and I'll make my own PR.

2024-06-12 13:45 UTC, mattias-p commented on t/profiles.t
> -
The empty strings for `resolver.source4` and `resolver.source6` are also sentinel values, so we need an example profile where those values are present.

```perl
# JSON representation of an example profile where all set values are sentinels
Readonly my $EXAMPLE_PROFILE_3 => qq(
  {
    "resolver": {
      "source4": "",
      "source6": ""
    }
  }
);
```

2024-06-12 13:45 UTC, mattias-p commented on t/profiles.t
> -};
We should test parsing of the sentinel values for `resolver.source4` and `resolver.source6` too.

```perl
subtest 'from_json() parses sentinel values from a string' => sub {
    my $profile = Zonemaster::Engine::Profile->from_json( $EXAMPLE_PROFILE_3 );

    is $profile->get( 'resolver.source4' ), '', 'resolver.source4 was parsed from JSON';
    is $profile->get( 'resolver.source6' ), '', 'resolver.source6 was parsed from JSON';
};
```

2024-06-12 13:45 UTC, mattias-p commented on t/profiles.t
> -
We should keep the checks for `resolver.source4` and `resolver.source6`.

```perl
subtest 'set() accepts sentinel values' => sub {
    my $profile = Zonemaster::Engine::Profile->new;

    $profile->set( 'resolver.source4', '' );
    is $profile->get( 'resolver.source4' ), '', 'resolver.source4 was updated';

    $profile->set( 'resolver.source6', '' );
    is $profile->get( 'resolver.source6' ), '', 'resolver.source6 was updated';
};
```

2024-06-13 15:31 UTC, matsduf approved these changes

2024-06-17 05:51 UTC, marc-vanderwal approved these changes

2024-06-17 09:31 UTC, merged

2024-06-27 08:00 UTC, matsduf commented
## Release testing for v2024.1

I have verified that there is no more `resolver.source` support.