Update Swedish translation
zonemaster/zonemaster-engine pull request #1416
Opened 2024-12-12 08:12 UTC by mattias-p

## Purpose

This PR updates the Swedish translation.

## Context

Fixes #1409.

## Changes

Translations in `sv.po` are updated to correspond to current develop branch.

## How to test this PR

N/A

2024-12-12 12:01 UTC, matsduf requested changes

2024-12-12 12:30 UTC, mattias-p commented on share/sv.po
> +"barnzonen."
I like "inkonsekvent" better too. I found it in couple more places. I'll fix those too.

2024-12-12 13:22 UTC, matsduf reviewed
There is a risk that the changes to the non-sv PO files will create conflicts with other translators. It might be better to do that reformatting at the end after translation?

2024-12-12 13:50 UTC, mattias-p commented on share/sv.po
> +"barnzonen."
Fixed.

2024-12-12 13:50 UTC, mattias-p commented on share/sv.po
> +"barnzonen."
Fixed.

2024-12-12 13:50 UTC, mattias-p commented on share/sv.po
> +"barnzonen."
Fixed.

2024-12-12 13:51 UTC, mattias-p commented on share/sv.po
> +"Inkonsistent saltlängd i NSEC3 i svar från olika namnservrar för barnzonen."
Fixed.

2024-12-12 13:52 UTC, mattias-p commented on share/sv.po
> +"namnservrarna \"{ns_list}\"."
I agree. I couldn't come up with anything better either.

2024-12-12 13:52 UTC, mattias-p commented
@matsduf I've resolved all comments and fixed CI. Please review again.

2024-12-13 08:12 UTC, matsduf approved these changes

2024-12-13 08:59 UTC, merged