Validate use of arguments in translated messages
zonemaster/zonemaster-engine pull request #776
Opened 2020-08-28 11:59 UTC by mattias-p

This adds a util (check-msg-args) that verifies that the args used in the msgstr are the same ones that are used in the msgid for perl-brace-format messages.
The utility is hooked up to the `make check-msg-args` target in `share/Makefile`. That target is in turn hooked up in the unit tests.

In order for the unit test not to immediately fail on these new checks, I had to fix the PO files. In doing so I found a couple of msgids where arguments were available but unused, and one where the word "Nameserver" hadn't been added before {ns}/{address}, so I fixed those as well. In the Danish translation I found a msgstr that didn't correspond to its msgid - instead of trying to fix that I just removed it. In the French translation I found a couple of messages that used arguments that weren't available. In those cases I just removed the arguments hoping that I didn't butcher the grammar or the meaning of the sentences. Please look extra closely at those when reviewing.

A new test-time dependency is introduced: Locale::PO. It's packaged for all supported platforms except CentOS.

The translation documentation should be updated with instructions to use this utility, but I don't want to touch it at the moment because of #772.

2020-09-08 12:15 UTC, matsduf requested changes

2020-09-08 12:15 UTC, matsduf commented on share/Makefile
> +
This does not seem to work, at least not in FreeBSD:

```
[~/git/zonemaster-engine/share]$ make check-msg-args
/bin/sh: /../util/check-msg-args: not found
*** Error code 127

Stop.
make: stopped in /usr/home/matsd/git/zonemaster-engine/share
[~/git/zonemaster-engine/share]$ ls -l ../util/check-msg-args 
-rwxr-xr-x  1 matsd  matsd  2098 sep.  8 13:56 ../util/check-msg-args
```

2020-09-08 12:15 UTC, matsduf commented on util/check-msg-args
> +}
There is no documentation what so ever in this script. Even though this script is meant to be run from Makefile there should be a paragraph explaining the purpose of it and that it is hooked from share/Makefile. Also, there could be situations when this is run outside Makefile, so at least explain what parameters it expects would be good.

2020-09-08 12:24 UTC, matsduf commented
> This check should not be run as a unit test because it would be impossible to update msgids without also updating the translations for all languages.

Is that really true? If the message IDs are updated in the Perl modules it will not spread to the PO files until translation work is done.

>  The translation documentation should be amended with installation of Local::PO, which is a new translation-time dependency. Locale::PO is packaged for all supported platforms except CentOS.

If this tool is only run during translation work, then there is no need to install it for normal installation.

2020-09-08 12:27 UTC, matsduf requested changes

2020-09-08 12:27 UTC, matsduf commented on docs/Installation.md
> +   sudo cpanm Email::Valid Locale::Msgfmt Locale::PO Module::Install Module::Install::XSUtil Test::More
Is the addition needed if the tool is only used during translation work? Even if it is run by Travis it should not be run during normal installation because the PO files are not available at that time (from CPAN files).

2020-09-08 12:34 UTC, mattias-p commented on share/Makefile
> +
Good catch. I'll take another look.

2020-09-08 12:35 UTC, mattias-p commented on util/check-msg-args
> +}
I'll add some basic usage documentation.

2020-09-08 12:45 UTC, mattias-p commented
Github is being funny. I can't reply to the top-level review comment so I'm quoting it here instead.

>>    This check should not be run as a unit test because it would be impossible to update msgids without also updating the translations for all languages.

> Is that really true? If the message IDs are updated in the Perl modules it will not spread to the PO files until translation work is done. It is only meaningful to run the script when the PO files are available, and they are not when installation is done from CPAN..

Maybe you're right. I'll hook up the check as a unit test again.

>>    The translation documentation should be amended with installation of Local::PO, which is a new translation-time dependency. Locale::PO is packaged for all supported platforms except CentOS.

> If this tool is only run during translation work, then there is no need to install it for normal installation.

That's correct. There's no need at installation-time to install tools and dependencies that are only used at translation-time. But since I'm re-including this tool in the unit tests, and since we're running our tests as part of the normal installation, these dependencies will need to be installed at installation-time anyway.

2020-09-08 13:19 UTC, mattias-p commented on docs/Installation.md
> +   sudo cpanm Email::Valid Locale::Msgfmt Locale::PO Module::Install Module::Install::XSUtil Test::More
You make a good point that we don't need Locale::PO at installation-time if check-msg-args is only executed at translation-time. At least in theory.

However if we execute check-msg-args as part of a unit test, we should have a `test_requires 'Locale::PO'` entry in Makefile.PL. And then `cpanm Zonemaster::Engine` would install it even if check-msg-args is never invoked by the unit tests because there are no PO files.

I guess we could add something to the Travis configuration to explicitly run the check-msg-args checks, or we could add `--notest` to the `cpanm Zonemaster::Engine` command, but I feel both of those are out of scope for this PR.

I feel the right thing for this PR is to remove Locale::PO from the `cpanm`, `apt` and `pkg` commands.

2020-09-10 07:20 UTC, mattias-p commented on share/Makefile
> +
Fixed.

2020-09-10 07:20 UTC, mattias-p commented on util/check-msg-args
> +}
Fixed.

2020-09-10 07:21 UTC, mattias-p commented on docs/Installation.md
> +   sudo cpanm Email::Valid Locale::Msgfmt Locale::PO Module::Install Module::Install::XSUtil Test::More
Fixed.

2020-09-16 08:24 UTC, mattias-p commented
I rebased to fix a merge conflict. I also took the opportunity to squash some of the commits.

@matsduf, @sandoche2k, @vlevigneron Please (re)review..

2020-09-16 08:42 UTC, sandoche2k approved these changes

2020-09-16 19:00 UTC, matsduf commented on share/Makefile
> +
Now it works in FreeBSD

2020-09-16 19:01 UTC, matsduf approved these changes

2020-09-17 08:46 UTC, merged