- Implementation of DNSSEC02 updated
zonemaster/zonemaster-engine pull request #783
Opened 2020-09-18 13:10 UTC by vlevigneron

- Implementation is now conformant with the last spec of this test case.
- Fixes zonemaster/zonemaster-engine#619

2020-09-18 13:12 UTC, vlevigneron commented
**TRANSLATION** not yet done

The following MSGID has been added:

```
              BROKEN_DS
              BROKEN_RRSIG
              DNSKEY_KSK_NOT_SEP
              DNSKEY_NOT_ZONE_SIGN
              DS_MATCHES
              NO_MATCHING_DNSKEY
              NO_MATCHING_RRSIG
              NO_RRSIG_DNSKEY
```
The following MSGID has been deleted:

```
              NO_DS
              DS_FOUND
              DS_RFC4509_NOT_VALID
              COMMON_KEYTAGS
              NO_COMMON_KEYTAGS
              DS_MATCHES_DNSKEY
              DS_DOES_NOT_MATCH_DNSKEY
              DS_MATCH_FOUND
              DS_MATCH_NOT_FOUND
```

2020-09-21 12:54 UTC, matsduf requested changes

2020-09-21 12:54 UTC, matsduf commented on lib/Zonemaster/Engine/Test/DNSSEC.pm
> +          @_;
'DNSKEY record with tag {keytag} returned by nameserver {ns}/{address} does not match the algorithm and hash
values in a DS record with same tag in parent zone.'

2020-09-21 12:54 UTC, matsduf commented on lib/Zonemaster/Engine/Test/DNSSEC.pm
> +          'Found DS records matching DNSKEY records.',  @_;
'The DS records in the parent zone match DNSKEY records in the child zone.'

2020-09-21 12:54 UTC, matsduf commented on lib/Zonemaster/Engine/Test/DNSSEC.pm
> +          @_;
'Nameserver {ns}/{address} returned no DNSKEY record matching the DS record with tag {keytag} found in the parent zone.'

2020-09-21 12:54 UTC, matsduf commented on lib/Zonemaster/Engine/Test/DNSSEC.pm
> +          @_;
'Nameserver {ns}/{address} returned no signature on the DNSKEY RRset that corresponds to the DNSKEY with tag {keytag} even though there is a DS record in the parent zone for that DNSKEY record.'

2020-09-21 12:54 UTC, matsduf commented on lib/Zonemaster/Engine/Test/DNSSEC.pm
> +          @_;
'The RRSIG of the DNSKEY RRset created by tag {keytag} returned by nameserver {ns}/{address} failed to be verified with error \'{error}\' (a DS redord with same tag is present in the parent zone).'

          'Signature for DNSKEY with tag {keytag} returned by nameserver {ns}/{address} failed'
          . 'to verify with error \'{error}\' although DS with same tag is present in parent.'

2020-09-21 13:23 UTC, matsduf commented on lib/Zonemaster/Engine/Test/DNSSEC.pm
> +          'The DS records in the parent zone match DNSKEY records in the child zone..',  @_;
One dot too many, "zone.."

2020-09-21 13:37 UTC, matsduf approved these changes

2020-09-21 14:24 UTC, merged