Norwegian language fix after reveiw
zonemaster/zonemaster-engine pull request #786
Opened 2020-09-22 11:36 UTC by repperille

Updated after a review by the language department

2020-09-22 13:19 UTC, matsduf requested changes
There could be more explicit ("\n") line breaks that should be removed.

If possible, and if you are working in an updated develop branch, please verify the PO file with the following command from the share directory:

../util/check-msg-args nb.po

2020-09-22 13:19 UTC, matsduf commented on share/nb.po
> +"Navnetjener {ns}/{address} svarte med feil \"owner name\",\n"
There should not be an explicit ("\n") line break here.

2020-09-22 13:19 UTC, matsduf commented on share/nb.po
> +"Callback-funksjonen for loggmodulen stoppet med feilmelding:  {exception}"
Remove extra space ("  " -> " "). Missing final dot.

2020-09-22 13:19 UTC, matsduf commented on share/nb.po
> +"DNS-spørring til {ns} for {name}/{type}/{class} mislyktes med\n"
There should not be an explicit ("\n") line break here.

2020-09-22 13:19 UTC, matsduf commented on share/nb.po
> +"Delegeringen av domenet {domain} innholder en navnetjener {ns} som\n"
There should not be an explicit ("\n") line break here.

2020-09-22 13:19 UTC, matsduf commented on share/nb.po
> +"Delegeringen av domenet {domain} innholder en navnetjener {ns} som\n"
There should not be an explicit ("\n") line break here.

2020-09-22 13:19 UTC, matsduf commented on share/nb.po
> +"Underdomene har ekstra IP-adress(er) for navnetjener som ikke er publisert\n"
There should not be an explicit ("\n") line break here.

2020-09-22 13:19 UTC, matsduf commented on share/nb.po
> +"Foreldredomene har ekstra IP-adress(er) for navnetjener som ikke er\n"
There should not be an explicit ("\n") line break here.

2020-09-22 13:19 UTC, matsduf commented on share/nb.po
> +"foreldredomenet ({parent_addresses})\n"
There should not be an explicit ("\n") line break here.

2020-09-22 13:19 UTC, matsduf commented on share/nb.po
>  "Ingen felles navnetjener-IP-adresse mellom underdomene ({child}) og\n"
There should not be an explicit ("\n") line break here.

2020-09-22 13:19 UTC, matsduf commented on share/nb.po
> +"Verifiseringen av signaturen for DNSKEY-posten med \"key tag\" {signature}\n"
There should not be an explicit ("\n") line break here.

2020-09-22 13:43 UTC, repperille commented
Aaargh! I have removed the line breaks and the missing dots

2020-09-22 14:01 UTC, matsduf commented
Did you see my question/request?
> If possible, and if you are working in an updated develop branch, please verify the PO file with the following command from the share directory:
>
> ../util/check-msg-args nb.po

2020-09-22 14:04 UTC, matsduf commented
@repperille, there were also some missing final dots that you have not corrected.

2020-09-22 14:14 UTC, repperille commented on share/nb.po
> +msgstr "Det er ikke mulig å følge delegeringen av domenet"
But there is no final dot in the msgid line ?!

2020-09-22 14:14 UTC, repperille commented on share/nb.po
> +msgstr "Alle IP-addresser som brukes av navnetjenerne er unike"
But there is no final dot in the msgid line ?!

2020-09-22 14:34 UTC, matsduf commented on share/nb.po
> +msgstr "Det er ikke mulig å følge delegeringen av domenet"
"All" msgid's have final dot. This an exception, maybe because it is a short none phrase without verb, but I will make an update. Good catch.

2020-09-22 14:35 UTC, matsduf commented on share/nb.po
> +msgstr "Alle IP-addresser som brukes av navnetjenerne er unike"
This is definitely a mistake since the other similar msgid's have a final dot. I will correct that.

2020-09-23 07:43 UTC, sandoche2k approved these changes

2020-09-23 14:06 UTC, mattias-p approved these changes

2020-09-23 14:45 UTC, matsduf approved these changes
I approve now. The missing dots can be added in a second step. There might come some more minor changes.

2020-09-23 14:45 UTC, merged