Update ns args in SYSTEM messages
zonemaster/zonemaster-engine pull request #792
Opened 2020-09-29 11:09 UTC by mattias-p

This is a follow-up to #790 with the corresponding updates to the SYSTEM messages.

It is also a step towards solving #713.

2020-09-29 12:31 UTC, matsduf requested changes

2020-09-29 12:31 UTC, matsduf commented on lib/Zonemaster/Engine/Translator.pm
>      },
ADDED_FAKE_DELEGATION and FAKE_DELEGATION_TO_SELF, a few lines up, should also be updated.

2020-09-29 12:31 UTC, matsduf commented on lib/Zonemaster/Engine/Translator.pm
>      FAKE_DELEGATION => sub {
Defined without arguments, but used with. (Just an observation, not for this PR.)

2020-09-29 13:52 UTC, mattias-p commented on lib/Zonemaster/Engine/Translator.pm
>      },
In what way should they be updated?

2020-09-29 14:25 UTC, matsduf commented on lib/Zonemaster/Engine/Translator.pm
>      },
I assumed that "ns" was a name server name, as it has usually been used for, not a name server name / IP address pair. Where ADDED_FAKE_DELEGATION and FAKE_DELEGATION_TO_SELF are used it says `ns => "$self"` and I am not sure what `$self` will return there.

2020-09-30 07:53 UTC, mattias-p commented on lib/Zonemaster/Engine/Translator.pm
>      },
It evaluates to a name / IP address string.

2020-09-30 07:59 UTC, matsduf approved these changes

2020-09-30 08:03 UTC, merged