Rename more message args
zonemaster/zonemaster-engine pull request #799
Opened 2020-10-05 15:12 UTC by mattias-p

Renames a bunch more name server related message arguments. No new argument names are introduced, except suffixes are appended to previously documented names, in order to provide disambiguation and context.

This is a step towards solving #713.

2020-10-05 19:01 UTC, matsduf requested changes

2020-10-06 09:56 UTC, mattias-p commented on lib/Zonemaster/Engine/Test/Consistency.pm
> +          . '({ns_list_parent}) and any equivalent address record in child zone ({ns_list_zone}).',
The way I see this is that ns_list_parent (or parent_ns_list) is a variant of ns_list. I don't it's necessary to list all variant names.

If we use suffixes for variants instead of prefixes, it's easier to find the canonical name in the list.

2020-10-06 10:00 UTC, mattias-p commented on lib/Zonemaster/Engine/Test/Consistency.pm
> +          'Saw NS set ({nsname_list_response}) on following nameserver set : {ns_list_servers}.', @_;
We could have nsname_list and ns_list here - there's no technical need for disambiguation. I only added the suffixes for extra clarity, but we could also go for shorter names and leave it to the msgid to provide context.

2020-10-06 10:16 UTC, mattias-p commented
I'll update the documentation to clarify the usage of suffixes.

2020-10-06 12:00 UTC, matsduf requested changes

2020-10-08 14:21 UTC, mattias-p commented on lib/Zonemaster/Engine/Test/Consistency.pm
> +          "A single NS set was found ({nsname_list}).", @_;
I don't get this. Can you elaborate?

2020-10-08 14:21 UTC, mattias-p commented on lib/Zonemaster/Engine/Test/Consistency.pm
>      },
I don't get this. Can you elaborate?

2020-10-08 14:33 UTC, mattias-p commented
@matsduf Can you review again?

2020-10-09 07:12 UTC, matsduf requested changes
I think we should have as few argument names as possible. They should focus on the kind of data. That is what the translators need.

2020-10-09 07:44 UTC, mattias-p commented
@matsduf Can you approve?

2020-10-09 09:53 UTC, matsduf approved these changes

2020-10-09 10:17 UTC, sandoche2k approved these changes

2020-10-12 06:53 UTC, merged