Update of Connectivity/connectivity03
zonemaster/zonemaster-engine pull request #802
Opened 2020-10-08 21:08 UTC by vlevigneron

- Fixes zonemaster/zonemaster-engine#592
- Add RIPE ASN lookup and change TC connectivity03 after spec updates

Not yet finished. For the moment it is backward compatible with previous way to define list of server in profile (asnroots). If we decide to change that, I will clean the code.

2020-10-09 14:59 UTC, matsduf requested changes
"share/profile_example_logfilter.json" should be updated too, shouldn't it?

2020-10-09 14:59 UTC, matsduf commented on lib/Zonemaster/Engine/Test/Connectivity.pm
> +          'AS Database error. No data to analyze.', @_;
'AS Database error. No data to analyze for {ns_ip}.'

In the specification we rather use "ASN". I do not know if it could create confusion. I guess that those who understand AS/ASN have seen both, and those who do not understand would not notice.

2020-10-09 14:59 UTC, matsduf commented on lib/Zonemaster/Engine/Test/Connectivity.pm
> +          'All nameservers in the delegation have IPv4 addresses in the same AS set ({asn_list}).', @_;
'All authoritative nameservers have the IPv4 addresses in the same AS set ({asn_list}).'

2020-10-09 14:59 UTC, matsduf commented on lib/Zonemaster/Engine/Test/Connectivity.pm
> +          'All nameservers in the delegation have IPv4 addresses in the same AS ({asn}).', @_;
'All authoritative nameservers have the IPv4 addresses in the same AS ({asn}).'

2020-10-09 14:59 UTC, matsduf commented on lib/Zonemaster/Engine/Test/Connectivity.pm
> +          'Authoritative IPv4 nameservers are in more than one AS ({asn_list}).', @_;
'At least two IPv4 addresses of the authoritative nameservers are announce by different AS sets. A merged list of all AS: ({asn_list}).'

I here assume that "asn_list" is a list of all AS of the IPv4 addresses.

2020-10-09 14:59 UTC, matsduf commented on lib/Zonemaster/Engine/Test/Connectivity.pm
> +          'All nameservers in the delegation have IPv6 addresses in the same AS set ({asn_list}).', @_;
'All authoritative nameservers have the IPv6 addresses in the same AS set ({asn_list}).'

2020-10-09 14:59 UTC, matsduf commented on lib/Zonemaster/Engine/Test/Connectivity.pm
> +          'All nameservers in the delegation have IPv6 addresses in the same AS ({asn}).', @_;
'All authoritative nameservers have the IPv6 addresses in the same AS ({asn}).'

2020-10-09 14:59 UTC, matsduf commented on lib/Zonemaster/Engine/Test/Connectivity.pm
> +          'Authoritative IPv6 nameservers are in more than one AS ({asn_list}).', @_;
'At least two IPv6 addresses of the authoritative nameservers are announce by different AS sets. A merged list of all AS: ({asn_list}).'

2020-10-09 14:59 UTC, matsduf commented on share/profile.json
> +        }
The string for "cymru" is not a server. For "ripe" it is a server name. May "names" is better? Or "base_string"?

I suggest "cymru" and "ripe" in lower case.

2020-10-09 14:59 UTC, matsduf commented on share/profile.json
> +            "IPV4_ONE_ASN" : "ERROR",
It is according to the specification, but is probably too hard. See zonemaster/zonemaster/pull/892

2020-10-09 14:59 UTC, matsduf commented on share/profile.json
> +            "IPV6_ONE_ASN" : "ERROR",
It is according to the specification, but is probably too hard. See zonemaster/zonemaster/pull/892

2020-10-09 14:59 UTC, matsduf commented on t/profiles/Test-all-levels.json
> +            "IPV4_ONE_ASN" : "ERROR",
It is according to the specification, but is probably too hard. See zonemaster/zonemaster/pull/892

2020-10-09 14:59 UTC, matsduf commented on t/profiles/Test-all-levels.json
> +            "IPV6_ONE_ASN" : "ERROR",
It is according to the specification, but is probably too hard. See zonemaster/zonemaster/pull/892

2020-10-09 15:43 UTC, vlevigneron commented on lib/Zonemaster/Engine/ASNLookup.pm
> +        }
While I agree on the preference for the new model, there is a problem because we have default values for the new model. So the oild model will be never used even if present in profile.

For the file in share, I agree, it is not very usefull to keep old model.

2020-10-09 16:28 UTC, vlevigneron commented on lib/Zonemaster/Engine/ASNLookup.pm
> +    }
It is not possible to have a wrong value unless we do not check all values allowed in Profile. I'll add a die.

2020-10-09 16:37 UTC, vlevigneron commented on share/profile.json
> +        }
I'll change "servers" by "sources".

2020-10-09 16:57 UTC, vlevigneron commented on lib/Zonemaster/Engine/Test/Connectivity.pm
> +          'Authoritative IPv6 nameservers are in more than one AS ({asn_list}).', @_;
Changed.

2020-10-09 16:58 UTC, vlevigneron commented on lib/Zonemaster/Engine/Test/Connectivity.pm
> +          'All nameservers in the delegation have IPv6 addresses in the same AS ({asn}).', @_;
Changed.

2020-10-09 16:59 UTC, vlevigneron commented on lib/Zonemaster/Engine/Test/Connectivity.pm
> +          'All nameservers in the delegation have IPv6 addresses in the same AS set ({asn_list}).', @_;
Changed.

2020-10-09 17:00 UTC, vlevigneron commented on lib/Zonemaster/Engine/Test/Connectivity.pm
> +          'All nameservers in the delegation have IPv4 addresses in the same AS ({asn}).', @_;
Changed.

2020-10-09 17:01 UTC, vlevigneron commented on lib/Zonemaster/Engine/Test/Connectivity.pm
> +          'Authoritative IPv4 nameservers are in more than one AS ({asn_list}).', @_;
Changed.

2020-10-09 17:02 UTC, vlevigneron commented on lib/Zonemaster/Engine/Test/Connectivity.pm
> +          'All nameservers in the delegation have IPv4 addresses in the same AS set ({asn_list}).', @_;
Changed.

2020-10-09 17:04 UTC, vlevigneron commented on lib/Zonemaster/Engine/Test/Connectivity.pm
> +          'AS Database error. No data to analyze.', @_;
Changed.

To be consistent, I changed to ASN

2020-10-09 17:17 UTC, vlevigneron commented on lib/Zonemaster/Engine/ASNLookup.pm
> +    foreach my $db_server ( @db_servers ) {
I was wondering the same thing. In the new specs, we just query the first one. In old specs we query one by one and go to the next one in case of failure.
I guess we should try the next server in case of "ERROR_ASN_DATABASE" issue.

2020-10-09 17:17 UTC, vlevigneron commented on lib/Zonemaster/Engine/ASNLookup.pm
> +    foreach my $db_server ( @db_servers ) {
Same answer... :-)

2020-10-10 21:08 UTC, matsduf requested changes

2020-10-10 21:08 UTC, matsduf commented on share/profile.json
>      "asnroots" : [ "asnlookup.zonemaster.net", "asnlookup.iis.se", "asn.cymru.com"],
I do not see why this should be kept. We should move to the new style.

2020-10-10 21:08 UTC, matsduf commented on share/profile.json
> +            "Cymru" : [ "asnlookup.zonemaster.net" ],
```
"Cymru" : [ "asnlookup.zonemaster.net", "asn.cymru.com" ],
```

2020-10-10 21:08 UTC, matsduf commented on share/profile_example_logfilter.json
>      "asnroots" : [ "asnlookup.zonemaster.net", "asnlookup.iis.se", "asn.cymru.com"],
I do not see why this should be kept. We should move to the new style.

2020-10-10 21:08 UTC, matsduf commented on share/profile_example_logfilter.json
> +            "Cymru" : [ "asnlookup.zonemaster.net" ],
```
"Cymru" : [ "asnlookup.zonemaster.net", "asn.cymru.com" ],
```

2020-10-10 21:08 UTC, matsduf commented on share/profile_example_logfilter.json
> +    },
On lines 91-112 in this file I find message tags that should be updated just as in profile.json:
```
        "CONNECTIVITY" : {
            "IPV4_DISABLED" : "DEBUG",
            "IPV6_DISABLED" : "DEBUG",
            "NAMESERVER_HAS_TCP_53" : "INFO",
            "NAMESERVER_HAS_UDP_53" : "INFO",
            "NAMESERVER_NO_TCP_53" : "ERROR",
            "NAMESERVER_NO_UDP_53" : "ERROR",
            "NAMESERVERS_IPV4_NO_AS" : "INFO",
            "NAMESERVERS_IPV4_WITH_MULTIPLE_AS" : "INFO",
            "NAMESERVERS_IPV4_WITH_UNIQ_AS" : "WARNING",
            "NAMESERVERS_IPV6_NO_AS" : "INFO",
            "NAMESERVERS_IPV6_WITH_MULTIPLE_AS" : "INFO",
            "NAMESERVERS_IPV6_WITH_UNIQ_AS" : "WARNING",
            "NAMESERVERS_NO_AS" : "INFO",
            "NAMESERVERS_WITH_UNIQ_AS" : "WARNING",
            "NAMESERVERS_WITH_MULTIPLE_AS" : "INFO",
            "IPV4_ASN" : "INFO",
            "IPV6_ASN" : "INFO",
            "ASN_INFOS_RAW" : "DEBUG",
            "ASN_INFOS_ANNOUNCE_BY" : "DEBUG",
            "ASN_INFOS_ANNOUNCE_IN" : "DEBUG"
        },
```

2020-10-10 21:44 UTC, vlevigneron commented on lib/Zonemaster/Engine/ASNLookup.pm
> +        }
If there is a default in the code it is because it is what it is written in specs:
```
"ASN Database" - The database of ASN data to be used. Possible values are "RIPE" and "Cymru" (the default value).
"Cymru Base Name" - If the ASN Database is "Cymru", the default value is "asnlookup.zonemaster.net".
"Ris Whois Server" - If the ASN Database is "RIPE", the default value is "riswhois.ripe.net".
```

2020-10-10 22:04 UTC, vlevigneron commented on lib/Zonemaster/Engine/ASNLookup.pm
> +    } ## end foreach my $db_source ( @db_sources )
I changed it that way.

2020-10-11 14:11 UTC, matsduf approved these changes

2020-10-11 14:18 UTC, matsduf commented
Travis complaints in two places, but they do not seem to be related to this PR. The first error seems to be ignored, but the second results in the formal error.

```
cd share && make touch-po all
make[2]: Entering directory '/home/travis/build/zonemaster/zonemaster-engine/build_dir/share'
ln: failed to access '*.mo': No such file or directory
Makefile:37: recipe for target '*.mo' failed
make[2]: *** [*.mo] Error 1
make[2]: Leaving directory '/home/travis/build/zonemaster/zonemaster-engine/build_dir/share'
Makefile:775: recipe for target 'pure_all' failed
make[1]: *** [pure_all] Error 2
make[1]: Leaving directory '/home/travis/build/zonemaster/zonemaster-engine/build_dir'
Makefile:554: recipe for target 'subdirs' failed
make: *** [subdirs] Error 2
```

```
t/Test-dnssec.t ........... 240/? 
#   Failed test 'afnic.fr gives ALL_ALGO_SIGNED'
#   at t/Test-dnssec.t line 25.
#   Failed test 'afnic.fr does not give RRSIG_BROKEN'
#   at t/Test-dnssec.t line 36.
```

2020-10-11 14:29 UTC, matsduf requested changes
I realized that the documentation in Profile.pm is not yet updated:
```
=head2 asnroots
An arrayref of domain names. Default C<["asnlookup.zonemaster.net",
"asnlookup.iis.se", "asn.cymru.com"]>.
The domains will be assumed to be Cymru-style AS lookup zones.
Normally only the first name in the list will be used, the rest are
backups in case the earlier ones don't work.
```

That also needs to be handled, but the update as such looks fine.

2020-10-12 06:29 UTC, matsduf approved these changes

2020-10-12 07:13 UTC, merged