Naming of message args
zonemaster/zonemaster-engine pull request #853
Opened 2020-11-26 11:59 UTC by mattias-p

This is another step towards solving #60 and #713.

2020-11-28 14:10 UTC, matsduf requested changes
There are several data types that are actually a non-negative, decimal integer (e.g. keytag and SOA serial). One possibility is to have a common data type to have fewer data types. Another (the path you have taken) is to have specific data type for each use.

This is a good work, and when more is completed we will see if this path will give too many data types.

2020-11-28 14:10 UTC, matsduf commented on lib/Zonemaster/Engine/Test/DNSSEC.pm
> +          @_;
Indentation looks wrong.

2020-11-28 14:10 UTC, matsduf commented on lib/Zonemaster/Engine/Test/DNSSEC.pm
> +          @_;
Indentation looks wrong.

2020-11-28 14:10 UTC, matsduf commented on lib/Zonemaster/Engine/Test/DNSSEC.pm
> +          @_;
Indentation.

2020-11-30 09:06 UTC, mattias-p commented on docs/logentry_args.md
> +| algo_mnemo  | Text                 | The mnemonic of a DNSKEY algorithm.                         |
Is it good enough if I change it to "DNSSEC algorithm" and link to https://www.iana.org/assignments/dns-sec-alg-numbers/dns-sec-alg-numbers.xhtml?

2020-11-30 09:35 UTC, mattias-p commented on docs/logentry_args.md
> +| module      | A Zonemaster test module, or `all` | The name of a Zonemaster test module.         |
I'd prefer not to consider argument value syntax as part of this series of pull requests, keeping to a narrow reading #713, limited to names and semantics. Syntax is also important, of course, but I'd like to deal with that in a separate issue. Would you be okay with that?

2020-11-30 10:42 UTC, matsduf commented on docs/logentry_args.md
> +| algo_mnemo  | Text                 | The mnemonic of a DNSKEY algorithm.                         |
For now, yes. Later I think we should define it in the test case specification and then use the same string in the implementation.

2020-11-30 10:43 UTC, matsduf commented on docs/logentry_args.md
> +| module      | A Zonemaster test module, or `all` | The name of a Zonemaster test module.         |
I do not fully understand, but I think it is acceptable that this update does not create the perfect solution and that we come back later with improvements.

2020-11-30 10:47 UTC, matsduf approved these changes

2020-11-30 10:48 UTC, merged