Add new feature in Profiles to customize some variables values
zonemaster/zonemaster-engine pull request #860
Opened 2020-12-29 16:37 UTC by vlevigneron

Fix issue zonemaster/zonemaster-engine#200

2020-12-29 17:30 UTC, matsduf requested changes
Issue #200 also asks for more standardized date expression. If that is not to be included here, it should be noted.

We also should update the test case since the limits are configurable.

2020-12-29 17:30 UTC, matsduf commented on lib/Zonemaster/Engine/Profile.pm
> +=head3 dnssec04.DURATION_LONG_LIMIT
I think it makes more sense to have the second level identical to the message tag. I am not sure if you want another level below that or not.
* dnssec04.DURATION_LONG.posint

2020-12-29 17:30 UTC, matsduf commented on lib/Zonemaster/Engine/Profile.pm
> +than DURATION_LONG_LIMIT.
Shouldn't it be *more than*?

2020-12-29 17:30 UTC, matsduf commented on lib/Zonemaster/Engine/Profile.pm
> +=head3 dnssec04.REMAINING_LONG_LIMIT
* dnssec04.REMAINING_LONG.posint

2020-12-29 17:30 UTC, matsduf commented on lib/Zonemaster/Engine/Profile.pm
> +=head3 dnssec04.REMAINING_SHORT_LIMIT
* dnssec04.REMAINING_SHORT.posint

2020-12-29 17:30 UTC, matsduf commented on lib/Zonemaster/Engine/Profile.pm
> +                    ${$_[0]}{$test_name}{uc($var_name)} = delete ${$_[0]}{$test_name}{$var_name};
This puts a heavy burden on this module. Wouldn't be better if the code just verifies that the first level matches a test case ID in this profile, the second a message tag in the profile and the third level be valid data type specification. And the data matches that data. Now we only define one datatype, positive integer:

* testcase00.MESSAGE_TAG.posint : 1234

If someone adds a message tag which does not use the feature, then nothing will break. The support can be added by just updating the test case module.

2020-12-29 18:14 UTC, vlevigneron commented on lib/Zonemaster/Engine/Profile.pm
> +                    ${$_[0]}{$test_name}{uc($var_name)} = delete ${$_[0]}{$test_name}{$var_name};
Ok, I'll try to do something more generic.

2021-01-04 11:04 UTC, vlevigneron commented
The last commit should address @matsduf remarks.
BUT it has a drawback... It does not pass "make test" with success, and zonemaster-cli does not work anymore. 
That's why I sent it, I do not get  the problem... If one of you could have a look and help me to find what is wrong.

2021-01-04 12:59 UTC, matsduf commented
The documentation that you have added to `Profile.pm` should be split up between that and `DNSSEC.pm`.

General documentation about the feature should reside in `Profile.pm`:

> =head2 test_cases_vars
> A complex data structure.
> Specify some variable values used in test cases.
> At the top level of this data structure are two levels of nested hashrefs.
> The keys of the top level hash are names of test cases.
> The keys of the second level hashes are variable names (and their associated 
> type) that should be used in test case in place of test case encoded values.
> The values of the second level hashes are values of those variables.

The specific variables that have been implemented should reside in the same module as has it implemented, in this case `DNSSEC.pm`:

> =head3 dnssec04.DURATION_LONG.postint
> Positive integer value.
> Returns DURATION_LONG message tag in case signature lifetime is less
> than DURATION_LONG.posint.
>
> =head3 dnssec04.REMAINING_LONG.posint
> Positive integer value.
> Returns REMAINING_LONG message tag in case signature remaining time is
> more than REMAINING_LONG.posint (in seconds).
>
> =head3 dnssec04.REMAINING_SHORT.posint
> Positive integer value.
> Returns REMAINING_SHORT message tag in case signature remaining time is
> less than DURATION_LONG.posint (in seconds).

2021-01-07 17:30 UTC, mattias-p requested changes

2021-01-07 17:30 UTC, mattias-p commented on lib/Zonemaster/Engine/Test/DNSSEC.pm
> +less than the value provided (in seconds).
I had to read this sentence several times to understand its meaning. Here's my take on rewording it to make it clearer:

> If the remaining validity time of the signature is less than `test_cases_vars.dnssec04.REMAINING_SHORT` (in seconds) this test case returns the REMAINING_SHORT message tag.

2021-01-08 08:53 UTC, mattias-p commented on lib/Zonemaster/Engine/Profile.pm
> +    use Data::Dumper;print Data::Dumper::Dumper($new);
This should be removed, right?

2021-01-08 08:53 UTC, mattias-p commented on lib/Zonemaster/Engine/Profile.pm
> +=head2 test_cases_vars.dnssec04.REMAINING_SHORT (Positive integer value)
The text on =head2 lines are anchors you can link to. When the data type is on the =head2 line and you want to link to the heading, you have to include the data type in the link. So, could you put "Positive integer value" on its own line?

2021-01-08 08:53 UTC, mattias-p commented on lib/Zonemaster/Engine/Profile.pm
> +this test case returns the REMAINING_SHORT message tag.
Could you also spell out the default value here so people updating their profile configuration don't have to figure out where it is in the code?

2021-01-08 15:11 UTC, mattias-p approved these changes

2021-01-08 15:55 UTC, matsduf reviewed
I do not think this is a good solution. Values specific to DNSSEC04 should stay in the DNSSEC.pm module, not in the general Profile.pm. If these three values are the only ones, it could be OK, but in the general case it is not good.

2021-01-11 10:59 UTC, mattias-p commented
@matsduf As problems arise when we add more test case specific properties we should revisit the design of the Profile module. I can't see any problems at this point, so I claim YAGNI.

2021-01-11 11:03 UTC, matsduf commented
> (...) YAGNI.

Yagni? What language is that?

2021-01-11 11:13 UTC, matsduf commented
@vlevigneron, this PR also fixes  `t/Test-dnssec.data` and  `t/Test-dnssec.t`. Those fixes are too important to be hidden in this PR. The changes are not even in a commit by themselves with some description. Can you please update the description of this PR with the problem and the fixes? We have been haunted by this type of errors several times. Does your correct solve it for good? Or do we have a problem that signatures expires? Should these unit tests run with a fixed clock, i.e. reset to the time when the data was collected?

2021-01-11 11:23 UTC, mattias-p commented
@matsduf said:

> Should these unit tests run with a fixed clock, i.e. reset to the time when the data was collected?

That would be great! I'll create an issue for that.

2021-01-11 11:25 UTC, vlevigneron commented
@matsduf For the moment it is more a workaround than a fix. I have disabled the dnnsec unit test that triggers this issue. So with that  `t/Test-dnssec.data` and  `t/Test-dnssec.t` files, the problem will no longer occur but I have to configure a new testing zone that will have a very long signature lifetime if we want to enable again this unit test.

2021-01-11 11:27 UTC, mattias-p commented
[YAGNI](https://en.wikipedia.org/wiki/YAGNI) is English.

2021-01-11 11:30 UTC, matsduf commented
> @matsduf For the moment it is more a workaround than a fix. I have disabled the dnnsec unit test that triggers this issue. So with that `t/Test-dnssec.data` and `t/Test-dnssec.t` files, the problem will no longer occur but I have to configure a new testing zone that will have a very long signature lifetime if we want to enable again this unit test.

Please write some sentences in the description of this PR that is has resolved the issue and what you have described here.

2021-01-11 11:31 UTC, vlevigneron commented
Good idea.

le 11 janv., Mattias Päivärinta a ?crit :
> @matsduf said:
> 
> > Should these unit tests run with a fixed clock, i.e. reset to the time when the data was collected?
> 
> That would be great! I'll create an issue for that.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/zonemaster/zonemaster-engine/pull/860#issuecomment-757888318

-- 
	Vincent Levigneron  A.F.N.I.C.  Vincent.Levigneron@afnic.fr

2021-01-11 11:41 UTC, matsduf approved these changes
This is good enough as a "pilot" and POC.

2021-01-11 11:43 UTC, matsduf commented
@vlevigneron, please merge so that we can get the solution on the unit tests for other PRs.

2021-01-11 12:51 UTC, merged