Implementation of Basic04
zonemaster/zonemaster-engine pull request #892
Opened 2021-04-30 13:04 UTC by vlevigneron

Fixes zonemaster/zonemaster-engine#763

Need to be done:
=> Unit tests
=> translation of new messages

2021-04-30 15:45 UTC, matsduf requested changes

2021-04-30 15:45 UTC, matsduf commented on lib/Zonemaster/Engine/Test/Basic.pm
> +          'Nameserver {ns} repond to a NS query with no records in answer.', @_;
What data type is `ns`? According to [logentry_args] `ns` should be "domain name and IP address pair", but I do not get that impression from the code below were it is used.

```
The name and IP address of a name server, separated by "/".
```






[logentry_args]: https://github.com/zonemaster/zonemaster-engine/blob/master/docs/logentry_args.md

2021-04-30 15:45 UTC, matsduf commented on lib/Zonemaster/Engine/Test/Basic.pm
> +test cases, these tests should be done only here.
"Initially" --> "previously"?

2021-04-30 15:45 UTC, matsduf commented on lib/Zonemaster/Engine/Test/Basic.pm
> +        push @results, $class->basic04( $zone );
This should before basic02 according to the specification.

2021-04-30 15:59 UTC, matsduf commented on lib/Zonemaster/Engine/Test/Basic.pm
> +          'Nameserver {ns} repond to a NS query with no records in answer.', @_;
'Nameserver {ns} reponds to an NS query with no NS records in the answer section.', @_;

2021-04-30 15:59 UTC, matsduf commented on lib/Zonemaster/Engine/Test/Basic.pm
> +          'Nameserver {ns} repond to a SOA query with no records in answer.', @_;
'Nameserver {ns} reponds to an SOA query with no SOA record in answer section.'

2021-04-30 15:59 UTC, matsduf commented on lib/Zonemaster/Engine/Test/Basic.pm
> +          'Nameserver {ns} did not respond over UDP and TCP.', @_;
'Nameserver {ns} does not respond over neither UDP nor TCP.'

2021-04-30 15:59 UTC, matsduf commented on lib/Zonemaster/Engine/Test/Basic.pm
> +          'No response from nameserver {ns} on NS queries.', @_;
'Nameserver {ns} does not respond to NS queries.'

2021-04-30 15:59 UTC, matsduf commented on lib/Zonemaster/Engine/Test/Basic.pm
> +          'No response from nameserver {ns} on SOA queries.', @_;
'Nameserver {ns} does not respond to SOA queries.'

2021-04-30 15:59 UTC, matsduf commented on lib/Zonemaster/Engine/Test/Basic.pm
> +          'Nameserver {ns} response is not authoritative on NS query.', @_;
'Nameserver {ns} does not give an authoritative response on an NS query.'

2021-04-30 15:59 UTC, matsduf commented on lib/Zonemaster/Engine/Test/Basic.pm
> +          'Nameserver {ns} did not respond over UDP.', @_;
'Nameserver {ns} does not respond over UDP.'

2021-04-30 15:59 UTC, matsduf commented on lib/Zonemaster/Engine/Test/Basic.pm
> +          'Nameserver {ns} responds with an unexpected RCODE ({rcode}) on a NS query.', @_;
"an NS query"

2021-04-30 16:13 UTC, vlevigneron commented on lib/Zonemaster/Engine/Test/Basic.pm
> +          'Nameserver {ns} repond to a NS query with no records in answer.', @_;
@matsduf I just double checked and 'ns' is as expected (The name and IP address of a name server, separated by "/").

2021-04-30 16:14 UTC, vlevigneron commented on lib/Zonemaster/Engine/Test/Basic.pm
> +test cases, these tests should be done only here.
Doone

2021-04-30 16:15 UTC, vlevigneron commented on lib/Zonemaster/Engine/Test/Basic.pm
> +        push @results, $class->basic04( $zone );
Fixed in next commit

2021-05-06 15:45 UTC, matsduf approved these changes

2021-05-06 19:46 UTC, merged

2021-05-30 21:40 UTC, matsduf commented
## Release testing for v2021.1

Works as expected.