DNSSEC16 test case implementation
zonemaster/zonemaster-engine pull request #900
Opened 2021-05-11 15:38 UTC by vlevigneron

- The code is now ready to be merged
- Only one message tag not tested for the moment (should be added on a later PR).

Updated 2021-05-17:
## How to test this PR

Read the test case specification for DNSSEC16 and verify that the implementation correctly reports issues and non-issues on selected zones to cover as many message tags as possible.

2021-05-12 20:11 UTC, vlevigneron commented
@matsduf implementation "finished" (no translation yet). We have to add new unit tests when we will find broken zone or when we will be able to configure these broken zone.

2021-05-15 17:32 UTC, vlevigneron commented
@matsduf Can you have a look ? I will not add more unit tests (only one message tage is not covered for the moment, I made some modification on Bind to prevent some checks that allow to load broken zones). I start to work on dnssec17. If we can merge dnssec16 before, it will be easier for the merge.

2021-05-17 09:00 UTC, matsduf requested changes
I will do some "live" tests too.

2021-05-17 09:15 UTC, vlevigneron commented on lib/Zonemaster/Engine/Test/DNSSEC.pm
> +          . 'is signed with an invalid RRSIG created by tag {keytag}.', @_;
Fixed

2021-05-17 09:16 UTC, vlevigneron commented on lib/Zonemaster/Engine/Test/DNSSEC.pm
> +          . '({ns_ip_list}) does not match any DNSKEY in DNSKEY RRset.',
Fixed

2021-05-17 09:17 UTC, vlevigneron commented on lib/Zonemaster/Engine/Test/DNSSEC.pm
> +          . 'signed but not by a key in DNSKEY RRset.',
Fixed

2021-05-17 09:17 UTC, vlevigneron commented on lib/Zonemaster/Engine/Test/DNSSEC.pm
> +          . 'is not signed.',
Fixed

2021-05-17 09:18 UTC, vlevigneron commented on lib/Zonemaster/Engine/Test/DNSSEC.pm
> +          . 'to IP addresses ({ns_ip_list}).',
Fixed

2021-05-17 09:19 UTC, vlevigneron commented on lib/Zonemaster/Engine/Test/DNSSEC.pm
> +          . 'has a "delete" CDS record as a single record.',
Fixed

2021-05-17 09:20 UTC, vlevigneron commented on lib/Zonemaster/Engine/Test/DNSSEC.pm
> +          . 'is not signed by the key that the CDS record with tag {keytag} points to.',
Fixed

2021-05-17 09:26 UTC, vlevigneron commented on lib/Zonemaster/Engine/Test/DNSSEC.pm
> +          . 'addresses ({ns_ip_list}) is mixed with normal CDS record.',
Fixed

2021-05-17 09:31 UTC, matsduf commented
> $ make distcheck
> "/usr/local/bin/perl" "-Iinc" "-MExtUtils::Manifest=fullcheck" -e fullcheck
> **Not in MANIFEST**: t/profiles/Test-dnssec16-only.json

2021-05-17 09:32 UTC, matsduf commented on t/profiles/Test-dnssec16-only.json
> +{
$ make distcheck
"/usr/local/bin/perl" "-Iinc" "-MExtUtils::Manifest=fullcheck" -e fullcheck
Not in MANIFEST: t/profiles/Test-dnssec16-only.json

2021-05-17 09:34 UTC, vlevigneron commented on t/profiles/Test-dnssec16-only.json
> +{
The one I always forget... Fixed in next commit.

2021-05-17 09:44 UTC, matsduf commented on t/profiles/Test-dnssec16-only.json
> +{
All  of us do, see #902.

2021-05-17 11:47 UTC, matsduf requested changes

2021-05-17 11:47 UTC, matsduf commented on lib/Zonemaster/Engine/Test/DNSSEC.pm
> +          @_;
To make it easier to understand:
```
The CDS RRset is signed with an RRSIG with tag {keytag}, but the RRSIG does not match the DNSKEY with the same key tag. Fetched from the nameservers with IP addresses "{ns_ip_list}".
```

2021-05-17 11:47 UTC, matsduf commented on t/Test-dnssec.t
> +zone_gives_not('dnssec16', $zone, [qw{DS16_CDS_INVALID_RRSIG DS16_CDS_MATCHES_NO_DNSKEY DS16_CDS_SIGNED_BY_UNKNOWN_DNSKEY DS16_CDS_UNSIGNED DS16_CDS_WITHOUT_DNSKEY DS16_DNSKEY_NOT_SIGNED_BY_CDS DS16_
When I test, it gives no `DS16_DELETE_CDS` message tag.

2021-05-17 11:47 UTC, matsduf commented on t/Test-dnssec.t
> +zone_gives_not('dnssec16', $zone, [qw{DS16_CDS_INVALID_RRSIG DS16_CDS_MATCHES_NO_DNSKEY DS16_CDS_SIGNED_BY_UNKNOWN_DNSKEY DS16_CDS_UNSIGNED DS16_DELETE_CDS DS16_DNSKEY_NOT_SIGNED_BY_CDS DS16_MIXED_DE
To test this, DNSSEC16 must be specified, else the test goes out of the module. I guess we keep as-is, at least as of now.

```
# zonemaster-cli --no-ipv6 --show_testcase --test DNSSEC dnssec16-cds-without-dnskey.zft-root.rd.nic.fr --locale en_US.UTF-8
Seconds Level     Testcase       Message
======= ========= ============== =======
   4.41 NOTICE    DNSSEC07       There are neither DS nor DNSKEY records for the zone.
   4.41 NOTICE    UNSPECIFIED    The zone is not signed with DNSSEC.
```

2021-05-17 11:57 UTC, vlevigneron commented on t/Test-dnssec.t
> +zone_gives_not('dnssec16', $zone, [qw{DS16_CDS_INVALID_RRSIG DS16_CDS_MATCHES_NO_DNSKEY DS16_CDS_SIGNED_BY_UNKNOWN_DNSKEY DS16_CDS_UNSIGNED DS16_CDS_WITHOUT_DNSKEY DS16_DNSKEY_NOT_SIGNED_BY_CDS DS16_
Strange.... I get it:

>    0.01 DEBUG     TEST_CASE_START   testcase=dnssec16
>    0.03 DEBUG     EXTERNAL_QUERY   flags={"class":"IN"}; ip=2001:dc3::35; name=dnssec16-delete-cds.zft-root.rd.nic.fr; type=SOA
> [...]
>    2.88 INFO      DS16_DELETE_CDS   ns_ip_list=145.239.76.199;145.239.76.201
>    2.88 DEBUG     TEST_CASE_END   testcase=dnssec16

2021-05-17 12:04 UTC, vlevigneron commented on t/Test-dnssec.t
> +zone_gives_not('dnssec16', $zone, [qw{DS16_CDS_INVALID_RRSIG DS16_CDS_MATCHES_NO_DNSKEY DS16_CDS_SIGNED_BY_UNKNOWN_DNSKEY DS16_CDS_UNSIGNED DS16_DELETE_CDS DS16_DNSKEY_NOT_SIGNED_BY_CDS DS16_MIXED_DE
The DNSSEC07 Tast case prevents other tests to be executed when the zone has no DNSKEY nor DS records. DNSSEC05 has the same behaviour. I'm not sure that for DS16_CDS_WITHOUT_DNSKEY it will be possible to bypass this.

2021-05-17 13:09 UTC, vlevigneron commented on lib/Zonemaster/Engine/Test/DNSSEC.pm
> +          @_;
Fixed

2021-05-17 13:13 UTC, vlevigneron commented
@matsduf Can you test again with dnssec16-delete-cds.zft-root.rd.nic.fr broken zone ? I do not understand why you have not the DS16_DELETE_CDS message tag.

2021-05-17 13:21 UTC, vlevigneron commented on lib/Zonemaster/Engine/Test/DNSSEC.pm
> +          @_;
Fixed

2021-05-17 13:54 UTC, matsduf commented
> @matsduf Can you test again with dnssec16-delete-cds.zft-root.rd.nic.fr broken zone ? I do not understand why you have not the DS16_DELETE_CDS message tag.

```
# zonemaster-cli --no-ipv6 --show_testcase --test DNSSEC dnssec16-delete-cds.zft-root.rd.nic.fr --locale en_US.UTF-8
Seconds Level     Testcase       Message
======= ========= ============== =======
   4.93 WARNING   DNSSEC05       The DNSKEY with tag 64275 uses an algorithm number 5 (RSA/SHA1) which is not recommended to be used.
   4.93 WARNING   DNSSEC05       The DNSKEY with tag 37774 uses an algorithm number 5 (RSA/SHA1) which is not recommended to be used.
   4.94 WARNING   DNSSEC05       The DNSKEY with tag 37774 uses an algorithm number 5 (RSA/SHA1) which is not recommended to be used.
   4.94 WARNING   DNSSEC05       The DNSKEY with tag 64275 uses an algorithm number 5 (RSA/SHA1) which is not recommended to be used.
   5.23 WARNING   DNSSEC14       DNSKEY with tag 64275 and using algorithm 5 (RSA/SHA1) has a size (1024) smaller than the recommended one (2048).
   5.40 NOTICE    DNSSEC15       CDS RRset is found on nameservers that resolve to IP addresses (145.239.76.199;145.239.76.201), but no CDNSKEY RRset.
```

2021-05-17 14:08 UTC, vlevigneron commented
@matsduf that's because you should add "--level info" to see this kind (INFO) of message tag.

2021-05-17 14:25 UTC, matsduf commented
> @matsduf that's because you should add "--level info" to see this kind (INFO) of message tag.

Correct. Missed that.

2021-05-17 14:43 UTC, matsduf commented on t/Test-dnssec.t
> +zone_gives_not('dnssec16', $zone, [qw{DS16_CDS_INVALID_RRSIG DS16_CDS_MATCHES_NO_DNSKEY DS16_CDS_SIGNED_BY_UNKNOWN_DNSKEY DS16_CDS_UNSIGNED DS16_DELETE_CDS DS16_DNSKEY_NOT_SIGNED_BY_CDS DS16_MIXED_DE
It is fine for now. We can look at that later.

2021-05-17 14:53 UTC, merged

2021-05-30 18:40 UTC, matsduf commented
## Release testing for v2021.1
Works as expected.