DNSSEC17 test case implementation
zonemaster/zonemaster-engine pull request #906
Opened 2021-05-17 15:32 UTC by vlevigneron

The code is not ready to be merged
Some unit test are still missing :
- DS17_CDNSKEY_MATCHES_NO_DNSKEY
- DS17_CDNSKEY_SIGNED_BY_UNKNOWN_DNSKEY
- DS17_DELETE_CDNSKEY
- DS17_MIXED_DELETE_CDNSKEY

2021-05-17 20:47 UTC, matsduf requested changes

2021-05-17 20:47 UTC, matsduf commented on lib/Zonemaster/Engine/Test/DNSSEC.pm
> +          'The CDS RRset is a mixture between "delete" record and other records. '
"CDS" => "CDNSKEY"

2021-05-17 20:47 UTC, matsduf commented on share/profile_example.json
> +            "DS17_MIXED_DELETE_CDNSKEY" : "ERROR",
Below, after line 491, there should be a line "dnssec17", shouldn't there?

2021-05-17 21:13 UTC, matsduf commented on t/Test-dnssec.t
> +$zone = Zonemaster::Engine->zone( 'dnssec17-cdnskey-unsigned.zft-root.rd.nic.fr' );
Something is probably missing in delegation:
```
  20.08 WARNING   DNSSEC01       Nameserver vps430862.ovh.net/145.239.76.202 responded with an unexpected rcode (NXDOMAIN) on a DS query for zone dnssec17-cdnskey-unsigned.zft-root.rd.nic.fr.
  20.08 WARNING   DNSSEC02       Nameserver vps430862.ovh.net/145.239.76.202 responded with an unexpected rcode (NXDOMAIN) on a DS query for zone dnssec17-cdnskey-unsigned.zft-root.rd.nic.fr.
```

2021-05-17 21:49 UTC, vlevigneron commented on share/profile_example.json
> +            "DS17_MIXED_DELETE_CDNSKEY" : "ERROR",
Yes. Fixed.

2021-05-17 21:50 UTC, vlevigneron commented on lib/Zonemaster/Engine/Test/DNSSEC.pm
> +          'The CDS RRset is a mixture between "delete" record and other records. '
Fixed

2021-05-17 21:57 UTC, vlevigneron commented on t/Test-dnssec.t
> +$zone = Zonemaster::Engine->zone( 'dnssec17-cdnskey-unsigned.zft-root.rd.nic.fr' );
Fixed

2021-05-18 12:04 UTC, matsduf commented
So far it looks good. Will the remaining unit tests be created, or should that be postponed? If postponed, an issue should be created stating that.

2021-05-18 13:19 UTC, vlevigneron commented
@matsduf I will not have time this week for the missing unit tests. It will be better to merge without it and create an issue for that.

2021-05-18 13:22 UTC, vlevigneron commented
Issue created https://github.com/zonemaster/zonemaster-engine/issues/907

2021-05-18 15:51 UTC, matsduf approved these changes

2021-05-18 16:00 UTC, merged

2021-05-27 19:55 UTC, matsduf commented
Resolves #898

2021-05-30 18:40 UTC, matsduf commented
## Release testing for v2021.1
Works as expected.