update installation doc
zonemaster/zonemaster-engine pull request #996
Opened 2021-11-04 13:03 UTC by blacksponge

## Purpose

Update installation instruction

## Changes

* Replace Centos by Rocky Linux
  * Replace yum by dnf
  * Install Test::More (provided by Test::Simple) and Module::Install using binary package
* Add missing Class::Accessor dependency

## How to test this PR

* Install the engine

2021-11-08 13:18 UTC, mattias-p submitted a review, later dismissed

2021-11-11 09:53 UTC, mattias-p approved these changes
LGTM

2021-11-11 10:16 UTC, matsduf submitted a review, later dismissed

2021-11-12 10:18 UTC, blacksponge commented
I merged develop to resolve the conflict, please re-review

2021-11-12 10:32 UTC, matsduf requested changes
Please update the description with a reference to the PR that added the Class::Accessor dependency to the code to make it possible to trace back.

2021-11-12 10:32 UTC, matsduf commented on docs/Translation-translators.md
>    ```
On line 27, should it `yum`, not `dnf`?

2021-11-15 16:42 UTC, mattias-p commented on docs/Translation-translators.md
>    ```
I'll be going over the Rocky parts again anyway.

2021-11-15 17:19 UTC, blacksponge commented on docs/Translation-translators.md
>    ```
it should be `dnf`, good catch

2021-11-15 17:34 UTC, mattias-p submitted a review, later dismissed

2021-11-15 18:14 UTC, matsduf approved these changes
I approve.

2021-11-16 08:53 UTC, matsduf commented
@blacksponge, please resolve conflict so it can be merge.

2021-11-17 16:37 UTC, mattias-p approved these changes

2021-11-17 16:38 UTC, matsduf approved these changes

2021-11-17 17:03 UTC, merged